/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { OpenRouterCore } from "../core.js";
import { apiKeysCreate } from "../funcs/apiKeysCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useOpenRouterContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ApiKeysCreateMutationVariables = {
  request: operations.CreateKeysRequest;
  options?: RequestOptions;
};

export type ApiKeysCreateMutationData = operations.CreateKeysResponse;

/**
 * Create a new API key
 */
export function useApiKeysCreateMutation(
  options?: MutationHookOptions<
    ApiKeysCreateMutationData,
    Error,
    ApiKeysCreateMutationVariables
  >,
): UseMutationResult<
  ApiKeysCreateMutationData,
  Error,
  ApiKeysCreateMutationVariables
> {
  const client = useOpenRouterContext();
  return useMutation({
    ...buildApiKeysCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyApiKeysCreate(): MutationKey {
  return ["@openrouter/sdk", "API Keys", "create"];
}

export function buildApiKeysCreateMutation(
  client$: OpenRouterCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ApiKeysCreateMutationVariables,
  ) => Promise<ApiKeysCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyApiKeysCreate(),
    mutationFn: function apiKeysCreateMutationFn({
      request,
      options,
    }): Promise<ApiKeysCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(apiKeysCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
