/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { OpenRouterCore } from "../core.js";
import { apiKeysGetAuthKey } from "../funcs/apiKeysGetAuthKey.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useOpenRouterContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";

export type ApiKeysGetAuthKeyQueryData = operations.GetAuthKeyResponse;

/**
 * Get current API key
 *
 * @remarks
 * Get information on the API key associated with the current authentication session
 */
export function useApiKeysGetAuthKey(
  options?: QueryHookOptions<ApiKeysGetAuthKeyQueryData>,
): UseQueryResult<ApiKeysGetAuthKeyQueryData, Error> {
  const client = useOpenRouterContext();
  return useQuery({
    ...buildApiKeysGetAuthKeyQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get current API key
 *
 * @remarks
 * Get information on the API key associated with the current authentication session
 */
export function useApiKeysGetAuthKeySuspense(
  options?: SuspenseQueryHookOptions<ApiKeysGetAuthKeyQueryData>,
): UseSuspenseQueryResult<ApiKeysGetAuthKeyQueryData, Error> {
  const client = useOpenRouterContext();
  return useSuspenseQuery({
    ...buildApiKeysGetAuthKeyQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function prefetchApiKeysGetAuthKey(
  queryClient: QueryClient,
  client$: OpenRouterCore,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildApiKeysGetAuthKeyQuery(
      client$,
    ),
  });
}

export function setApiKeysGetAuthKeyData(
  client: QueryClient,
  data: ApiKeysGetAuthKeyQueryData,
): ApiKeysGetAuthKeyQueryData | undefined {
  const key = queryKeyApiKeysGetAuthKey();

  return client.setQueryData<ApiKeysGetAuthKeyQueryData>(key, data);
}

export function invalidateAllApiKeysGetAuthKey(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["openrouter", "API Keys", "getAuthKey"],
  });
}

export function buildApiKeysGetAuthKeyQuery(
  client$: OpenRouterCore,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ApiKeysGetAuthKeyQueryData>;
} {
  return {
    queryKey: queryKeyApiKeysGetAuthKey(),
    queryFn: async function apiKeysGetAuthKeyQueryFn(
      ctx,
    ): Promise<ApiKeysGetAuthKeyQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(apiKeysGetAuthKey(
        client$,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyApiKeysGetAuthKey(): QueryKey {
  return ["openrouter", "API Keys", "getAuthKey"];
}
