/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { OpenRouterCore } from "../core.js";
import { creditsPostCreditsCoinbase } from "../funcs/creditsPostCreditsCoinbase.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useOpenRouterContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CreditsPostCreditsCoinbaseMutationVariables = {
  security: operations.PostCreditsCoinbaseSecurity;
  request?: operations.PostCreditsCoinbaseRequest | undefined;
  options?: RequestOptions;
};

export type CreditsPostCreditsCoinbaseMutationData =
  operations.PostCreditsCoinbaseResponse;

/**
 * Create a Coinbase charge for crypto payment
 */
export function useCreditsPostCreditsCoinbaseMutation(
  options?: MutationHookOptions<
    CreditsPostCreditsCoinbaseMutationData,
    Error,
    CreditsPostCreditsCoinbaseMutationVariables
  >,
): UseMutationResult<
  CreditsPostCreditsCoinbaseMutationData,
  Error,
  CreditsPostCreditsCoinbaseMutationVariables
> {
  const client = useOpenRouterContext();
  return useMutation({
    ...buildCreditsPostCreditsCoinbaseMutation(client, options),
    ...options,
  });
}

export function mutationKeyCreditsPostCreditsCoinbase(): MutationKey {
  return ["@openrouter/sdk", "Credits", "postCreditsCoinbase"];
}

export function buildCreditsPostCreditsCoinbaseMutation(
  client$: OpenRouterCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CreditsPostCreditsCoinbaseMutationVariables,
  ) => Promise<CreditsPostCreditsCoinbaseMutationData>;
} {
  return {
    mutationKey: mutationKeyCreditsPostCreditsCoinbase(),
    mutationFn: function creditsPostCreditsCoinbaseMutationFn({
      security,
      request,
      options,
    }): Promise<CreditsPostCreditsCoinbaseMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(creditsPostCreditsCoinbase(
        client$,
        security,
        request,
        mergedOptions,
      ));
    },
  };
}
