/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { OpenRouterCore } from "../core.js";
import { modelsListModelsCount } from "../funcs/modelsListModelsCount.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useOpenRouterContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";

export type ModelsListModelsCountQueryData = operations.ListModelsCountResponse;

/**
 * Get total count of available models
 */
export function useModelsListModelsCount(
  options?: QueryHookOptions<ModelsListModelsCountQueryData>,
): UseQueryResult<ModelsListModelsCountQueryData, Error> {
  const client = useOpenRouterContext();
  return useQuery({
    ...buildModelsListModelsCountQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get total count of available models
 */
export function useModelsListModelsCountSuspense(
  options?: SuspenseQueryHookOptions<ModelsListModelsCountQueryData>,
): UseSuspenseQueryResult<ModelsListModelsCountQueryData, Error> {
  const client = useOpenRouterContext();
  return useSuspenseQuery({
    ...buildModelsListModelsCountQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function prefetchModelsListModelsCount(
  queryClient: QueryClient,
  client$: OpenRouterCore,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildModelsListModelsCountQuery(
      client$,
    ),
  });
}

export function setModelsListModelsCountData(
  client: QueryClient,
  data: ModelsListModelsCountQueryData,
): ModelsListModelsCountQueryData | undefined {
  const key = queryKeyModelsListModelsCount();

  return client.setQueryData<ModelsListModelsCountQueryData>(key, data);
}

export function invalidateAllModelsListModelsCount(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@openrouter/sdk", "Models", "listModelsCount"],
  });
}

export function buildModelsListModelsCountQuery(
  client$: OpenRouterCore,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ModelsListModelsCountQueryData>;
} {
  return {
    queryKey: queryKeyModelsListModelsCount(),
    queryFn: async function modelsListModelsCountQueryFn(
      ctx,
    ): Promise<ModelsListModelsCountQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(modelsListModelsCount(
        client$,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyModelsListModelsCount(): QueryKey {
  return ["@openrouter/sdk", "Models", "listModelsCount"];
}
