name: 'Validate SDK'
description: 'Run build, typecheck, and tests for the SDK'

inputs:
  openrouter-api-key:
    description: 'OpenRouter API key for running tests'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Build SDK
      shell: bash
      run: pnpm run build

    - name: Install examples dependencies
      shell: bash
      working-directory: examples
      run: pnpm install

    # TODO: Re-enable when Speakeasy fixes generated code type errors
    - name: Typecheck examples root
      shell: bash
      working-directory: examples
      run: pnpm exec tsc

    - name: Install nextjs-example dependencies
      shell: bash
      working-directory: examples/nextjs-example
      run: pnpm install

    - name: Typecheck nextjs-example
      shell: bash
      working-directory: examples/nextjs-example
      run: pnpm exec tsc --noEmit

    - name: Run unit tests
      shell: bash
      env:
        OPENROUTER_API_KEY: ${{ inputs.openrouter-api-key }}
      run: pnpm exec vitest --run --exclude 'tests/e2e/**'

    - name: Run e2e tests
      shell: bash
      env:
        OPENROUTER_API_KEY: ${{ inputs.openrouter-api-key }}
      run: pnpm exec vitest --run tests/e2e/
