name: 'Validate SDK'
description: 'Run build, typecheck, and tests for the SDK'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Build SDK
      shell: bash
      run: npm run build

    # - name: Typecheck tests directory
    #   shell: bash
    #   run: npx tsc --noEmit --skipLibCheck --esModuleInterop --moduleResolution node --module esnext --target es2020 tests/**/*.ts

    - name: Install examples dependencies
      shell: bash
      working-directory: examples
      run: npm install

    - name: Typecheck examples root
      shell: bash
      working-directory: examples
      run: npx tsc --noEmit --skipLibCheck --esModuleInterop --moduleResolution node --module esnext --target es2020 *.ts

    - name: Install nextjs-example dependencies
      shell: bash
      working-directory: examples/nextjs-example
      run: npm install

    - name: Typecheck nextjs-example
      shell: bash
      working-directory: examples/nextjs-example
      run: npx tsc --noEmit

    - name: Run tests
      shell: bash
      run: npx vitest
