/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 254a218f7d6b
 */

import { batchCreateBatches } from "../funcs/batchCreateBatches.js";
import { batchDelete } from "../funcs/batchDelete.js";
import { batchGetBatches } from "../funcs/batchGetBatches.js";
import { batchList } from "../funcs/batchList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Batch extends ClientSDK {
  /**
   * List batches
   *
   * @remarks
   * Lists batches in the workspace of the authenticating API key, newest first. To fetch the next page, pass the previous page's `last_id` as `after`. List items omit `results`. Use `GET /batches/{id}` to get them. See the [Batch API Quickstart](https://openrouter.ai/docs/batch-quickstart).
   */
  async list(
    request?: operations.ListBatchesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListBatchesResponse, { cursor: string }>> {
    return unwrapResultIterator(batchList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a batch
   *
   * @remarks
   * Creates a batch of requests that run asynchronously against a single endpoint (`/v1/chat/completions`, `/v1/responses`, `/v1/messages`, `/v1/embeddings`). Returns `202` with `status: "validating"`. Poll `GET /batches/{id}` for progress and results. See the [Batch API Quickstart](https://openrouter.ai/docs/batch-quickstart).
   */
  async createBatches(
    request: operations.CreateBatchesRequest,
    options?: RequestOptions,
  ): Promise<models.BatchObject> {
    return unwrapAsync(batchCreateBatches(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a batch
   *
   * @remarks
   * Deletes a batch in a terminal status (`completed`, `failed`, `expired`, or `cancelled`) and its stored requests and results. Batches still in progress return `409`. Billing and usage records are kept. See the [Batch API Quickstart](https://openrouter.ai/docs/batch-quickstart).
   */
  async delete(
    request: operations.DeleteBatchRequest,
    options?: RequestOptions,
  ): Promise<models.BatchDeletedObject> {
    return unwrapAsync(batchDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a batch
   *
   * @remarks
   * Returns a batch with its status and request counts. Batches in a terminal status include `results`. Failed batches report the reason in `error.message`. See the [Batch API Quickstart](https://openrouter.ai/docs/batch-quickstart).
   */
  async getBatches(
    request: operations.GetBatchesRequest,
    options?: RequestOptions,
  ): Promise<models.BatchObject> {
    return unwrapAsync(batchGetBatches(
      this,
      request,
      options,
    ));
  }
}
