/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: afeac65e28f8
 */

import { ClientSDK } from "../lib/sdks.js";
import { BetaAnalytics } from "./betaanalytics.js";
import { BetaResponses } from "./betaresponses.js";

export class Beta extends ClientSDK {
  private _analytics?: BetaAnalytics;
  get analytics(): BetaAnalytics {
    return (this._analytics ??= new BetaAnalytics(this._options));
  }

  private _responses?: BetaResponses;
  /**
   * @deprecated Use `client.responses.send()` instead. Scheduled for removal (sunset date TBD).
   */
  get responses(): BetaResponses {
    return (this._responses ??= new BetaResponses(this._options));
  }
}
