/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f772470024e6
 */

import { containersDownloadContainerFileContent } from "../funcs/containersDownloadContainerFileContent.js";
import { containersGetContainerFile } from "../funcs/containersGetContainerFile.js";
import { containersListContainerFiles } from "../funcs/containersListContainerFiles.js";
import { containersPromoteContainerFile } from "../funcs/containersPromoteContainerFile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Containers extends ClientSDK {
  /**
   * List container files
   *
   * @remarks
   * Lists the files in a container, in lexicographic path order. The container id is the canonical id returned in bash/shell tool results; a restarted session is a separate container with its own id. Paginate with `limit` and `after` (pass the previous page’s `last_id`); `has_more: true` always means the next page is fetchable that way.
   */
  async listContainerFiles(
    request: operations.ListContainerFilesRequest,
    options?: RequestOptions,
  ): Promise<models.ContainerFileListResponse> {
    return unwrapAsync(containersListContainerFiles(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a container file
   *
   * @remarks
   * Returns the metadata of a single file in a container.
   */
  async getContainerFile(
    request: operations.GetContainerFileRequest,
    options?: RequestOptions,
  ): Promise<models.ContainerFile> {
    return unwrapAsync(containersGetContainerFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Download container file content
   *
   * @remarks
   * Streams the raw bytes of a file in a container.
   */
  async downloadContainerFileContent(
    request: operations.DownloadContainerFileContentRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(containersDownloadContainerFileContent(
      this,
      request,
      options,
    ));
  }

  /**
   * Promote a container file into workspace documents
   *
   * @remarks
   * Copies a file from the container's sandbox prefix into the workspace's durable document storage, so it outlives the container. Returns the new document in the Files API shape, with a durable file id in the documents namespace. The copy counts against the workspace's storage quota exactly like an upload. An optional filename overrides the container-relative path in the promoted document metadata.
   */
  async promoteContainerFile(
    request: operations.PromoteContainerFileRequest,
    options?: RequestOptions,
  ): Promise<models.FileResponse> {
    return unwrapAsync(containersPromoteContainerFile(
      this,
      request,
      options,
    ));
  }
}
