/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e28b205da063
 */

import type { RequestOptions } from '../lib/sdks.js';
import type * as operations from '../models/operations/index.js';

import { generationsGetGeneration } from '../funcs/generationsGetGeneration.js';
import { ClientSDK } from '../lib/sdks.js';
import { unwrapAsync } from '../types/fp.js';

export class Generations extends ClientSDK {
  /**
   * Get request & usage metadata for a generation
   */
  async getGeneration(
    request: operations.GetGenerationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetGenerationResponse> {
    return unwrapAsync(generationsGetGeneration(this, request, options));
  }
}
