/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fc3b4e6c5008
 */

import { internsChat } from "../funcs/internsChat.js";
import { internsCreateIntern } from "../funcs/internsCreateIntern.js";
import { internsDeleteIntern } from "../funcs/internsDeleteIntern.js";
import { internsGetIntern } from "../funcs/internsGetIntern.js";
import { internsGetInternDaemonAccess } from "../funcs/internsGetInternDaemonAccess.js";
import { internsInvoke } from "../funcs/internsInvoke.js";
import { internsListInterns } from "../funcs/internsListInterns.js";
import { internsProvisionIntern } from "../funcs/internsProvisionIntern.js";
import { internsSuspendIntern } from "../funcs/internsSuspendIntern.js";
import { internsUpdateIntern } from "../funcs/internsUpdateIntern.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Interns extends ClientSDK {
  /**
   * List interns
   *
   * @remarks
   * Lists interns visible to the authenticated key, newest first. Filter by workspace and one or more lifecycle statuses. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async listInterns(
    request?: operations.ListInternsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.InternListResponse> {
    return unwrapAsync(internsListInterns(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an intern
   *
   * @remarks
   * Creates an intern in an explicit workspace. The operation also creates its private vault. It can start provisioning immediately or wait for a later provision call. A retry with the same idempotency key and body resumes unfinished work. The request body is capped at 1048576 bytes and a larger body is refused with 413. A non-empty body must declare `Content-Type: application/json` or it is refused with 415. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async createIntern(
    request: operations.CreateInternRequest,
    options?: RequestOptions,
  ): Promise<models.Intern> {
    return unwrapAsync(internsCreateIntern(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an intern
   *
   * @remarks
   * Starts safe teardown of the intern, its runtime and its private vault. The body is optional. Send `{"acknowledge_workspace_loss": true}` to delete a `destroy_failed` intern whose `last_failure_message` names `workspace_archive_failed`, accepting that its workspace is not backed up. The request body is capped at 1048576 bytes and a larger body is refused with 413. A non-empty body must declare `Content-Type: application/json` or it is refused with 415. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async deleteIntern(
    request: operations.DeleteInternRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteInternResponse> {
    return unwrapAsync(internsDeleteIntern(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an intern
   *
   * @remarks
   * Returns the public lifecycle state and settings for one visible intern. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async getIntern(
    request: operations.GetInternRequest,
    options?: RequestOptions,
  ): Promise<models.Intern> {
    return unwrapAsync(internsGetIntern(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an intern
   *
   * @remarks
   * Changes the intern name, description, instructions or model. Omitted fields stay unchanged. The request body is capped at 1048576 bytes and a larger body is refused with 413. A non-empty body must declare `Content-Type: application/json` or it is refused with 415. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async updateIntern(
    request: operations.UpdateInternRequest,
    options?: RequestOptions,
  ): Promise<models.Intern> {
    return unwrapAsync(internsUpdateIntern(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an intern's daemon access
   *
   * @remarks
   * Returns the origin and daemon token that attach `ori tui --host` to one visible, running intern. The token is a credential: the response is sent with `Cache-Control: no-store`, each reveal is logged by caller and intern, and a caller may make 10 reveals per minute. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async getInternDaemonAccess(
    request: operations.GetInternDaemonAccessRequest,
    options?: RequestOptions,
  ): Promise<models.InternDaemonAccess> {
    return unwrapAsync(internsGetInternDaemonAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * Provision an intern
   *
   * @remarks
   * Starts the first boot, or resumes an intern after suspension. This operation takes no request body. A body carrying any field is refused with 400 rather than ignored. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async provisionIntern(
    request: operations.ProvisionInternRequest,
    options?: RequestOptions,
  ): Promise<models.ProvisionInternResponse> {
    return unwrapAsync(internsProvisionIntern(
      this,
      request,
      options,
    ));
  }

  /**
   * Suspend an intern
   *
   * @remarks
   * Stops the intern runtime while keeping its disk and configuration for a later provision call. This operation takes no request body. A body carrying any field is refused with 400 rather than ignored. The API key selects the caller, workspace and visible interns. There is no default workspace fallback. Requests on regional hostnames such as `eu.openrouter.ai` are refused. [API key](/docs/api-reference/authentication) required.
   */
  async suspendIntern(
    request: operations.SuspendInternRequest,
    options?: RequestOptions,
  ): Promise<models.SuspendInternResponse> {
    return unwrapAsync(internsSuspendIntern(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream a chat completion with an intern
   *
   * @remarks
   * Sends a prompt to one of your interns and streams the reply as OpenAI-compatible server-sent events ending with `[DONE]`. The run executes on the intern, which may pause to ask you something. It then streams one `openrouter.provide_input` tool call and finishes with `finish_reason: "tool_calls"`, and the run stays open on the intern.
   *
   * Every response, whether it ends with `stop`, `tool_calls` or `error`, is followed by a final chunk with empty `choices` that carries `session_id`, then `data: [DONE]`. That chunk carries the `usage` the intern reported for the run, after `stop` or `error`, and `null` when the intern reported none. After `tool_calls` its `usage` is `null` because the turn is not over. Read through `[DONE]`: the `session_id` you need to reply arrives after the `tool_calls` finish chunk.
   *
   * To answer, send a second request with the same `session_id`, the assistant message echoing that tool call, and a `tool` message whose `tool_call_id` is the tool call id and whose `content` is the answer. The answer is delivered to the run that asked and the stream continues from where it paused. A question stays open for its interaction deadline (5 minutes by default) and the run is cancelled when that passes. Rejected replies do not extend the deadline.
   *
   * Closing the connection after the `[DONE]` that follows `finish_reason: "tool_calls"` keeps the run alive. Disconnecting while a response is still streaming cancels the run. The stream writes a `: keepalive` comment whenever nothing else has been written for 30 seconds, so a disconnect is noticed within that interval even while the intern is silent.
   *
   * A run the intern ends while you are still connected, by cancellation or by a deadline, ends the stream with a `finish_reason: "error"` chunk carrying `410` and reason `run_ended`, then the final empty-`choices` chunk and `[DONE]`. That error reports only an ending the intern confirmed. A connection that breaks without that confirmation ends with reason `stream_severed`, and a client that has already disconnected is promised no final event.
   *
   * Set `approval_mode` to `manual` to have the intern ask before approval-bearing tools such as the shell. Omitted, the run self-drives and consents on your behalf. The mode belongs to the run started by that prompt and must be repeated on later prompts.
   *
   * Available to interns programme members. Callers outside the programme receive `404` for every path under `/api/v1/interns`.
   */
  async chat(
    request: operations.CreateInternChatCompletionRequest & {
      internChatCompletionRequest: { stream?: false | undefined };
    },
    options?: RequestOptions,
  ): Promise<operations.CreateInternChatCompletionResponse>;
  async chat(
    request: operations.CreateInternChatCompletionRequest & {
      internChatCompletionRequest: { stream: true };
    },
    options?: RequestOptions,
  ): Promise<operations.CreateInternChatCompletionResponse>;
  async chat(
    request: operations.CreateInternChatCompletionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateInternChatCompletionResponse>;
  async chat(
    request: operations.CreateInternChatCompletionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateInternChatCompletionResponse> {
    return unwrapAsync(internsChat(
      this,
      request,
      options,
    ));
  }

  /**
   * Start an intern run without waiting for it
   *
   * @remarks
   * Starts a run on one of your interns and answers `202` with the `session_id` as soon as the intern accepts it. The run keeps going on the intern after the response. Nothing about its progress comes back on this request; the intern reports through its own tools, such as Slack.
   *
   * Send the same `session_id` later to continue the conversation, for example to hand the intern a decision on work it started. If that session already has a run going, the prompt is delivered into it and the status is `steered`. A `session_id` is accepted only from the caller it was issued to, on the same intern; any other, including sessions started from Slack or the chat endpoint, is refused with `404`.
   *
   * Runs started here self-drive: the intern consents to its own tool approvals, and a question it asks is answered by its own fallback. A run ends when the intern finishes it or after its execution deadline (1 hour by default).
   *
   * Available to interns programme members. Callers outside the programme receive `404` for every path under `/api/v1/interns`.
   */
  async invoke(
    request: operations.InvokeInternRequest,
    options?: RequestOptions,
  ): Promise<operations.InvokeInternResponse> {
    return unwrapAsync(internsInvoke(
      this,
      request,
      options,
    ));
  }
}
