/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9c0e070af33d
 */

import { observabilityCreate } from "../funcs/observabilityCreate.js";
import { observabilityDelete } from "../funcs/observabilityDelete.js";
import { observabilityGet } from "../funcs/observabilityGet.js";
import { observabilityList } from "../funcs/observabilityList.js";
import { observabilityUpdate } from "../funcs/observabilityUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Observability extends ClientSDK {
  /**
   * List observability destinations
   *
   * @remarks
   * List the observability destinations configured for the authenticated entity's default workspace. Use the `workspace_id` query parameter to scope the result to a different workspace. Only destinations with stable release status are surfaced — destinations of other types are excluded. Requires a [management key](/docs/guides/overview/auth/management-api-keys) — standard API keys used for inference will not work.
   */
  async list(
    request?: operations.ListObservabilityDestinationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.ListObservabilityDestinationsResponse,
      { offset: number }
    >
  > {
    return unwrapResultIterator(observabilityList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an observability destination
   *
   * @remarks
   * Create a new observability destination. A maximum of 5 destinations per type is allowed. Defaults to the authenticated entity's default workspace; use the `workspace_id` body field to scope to a different workspace. Requires a [management key](/docs/guides/overview/auth/management-api-keys) — standard API keys used for inference will not work.
   */
  async create(
    request: operations.CreateObservabilityDestinationRequest,
    options?: RequestOptions,
  ): Promise<models.CreateObservabilityDestinationResponse> {
    return unwrapAsync(observabilityCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an observability destination
   *
   * @remarks
   * Delete an existing observability destination. This performs a soft delete. Requires a [management key](/docs/guides/overview/auth/management-api-keys) — standard API keys used for inference will not work.
   */
  async delete(
    request: operations.DeleteObservabilityDestinationRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteObservabilityDestinationResponse> {
    return unwrapAsync(observabilityDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an observability destination
   *
   * @remarks
   * Fetch a single observability destination by its UUID. Requires a [management key](/docs/guides/overview/auth/management-api-keys) — standard API keys used for inference will not work.
   */
  async get(
    request: operations.GetObservabilityDestinationRequest,
    options?: RequestOptions,
  ): Promise<models.GetObservabilityDestinationResponse> {
    return unwrapAsync(observabilityGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an observability destination
   *
   * @remarks
   * Update an existing observability destination. Only the fields provided in the request body are updated. Requires a [management key](/docs/guides/overview/auth/management-api-keys) — standard API keys used for inference will not work.
   */
  async update(
    request: operations.UpdateObservabilityDestinationRequest,
    options?: RequestOptions,
  ): Promise<models.UpdateObservabilityDestinationResponse> {
    return unwrapAsync(observabilityUpdate(
      this,
      request,
      options,
    ));
  }
}
