/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7ad611b27e9d
 */

import * as z from "zod/v4";
import { EventStream } from "../../lib/event-streams.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateResponsesGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  xTitle?: string | undefined;
};

export type CreateResponsesRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  xTitle?: string | undefined;
  openResponsesRequest: models.OpenResponsesRequest;
};

/**
 * Successful response
 */
export type CreateResponsesResponseBody = {
  /**
   * Union of all possible event types emitted during response streaming
   */
  data: models.OpenResponsesStreamEvent;
};

export type CreateResponsesResponse =
  | models.OpenResponsesNonStreamingResponse
  | EventStream<models.OpenResponsesStreamEvent>;

/** @internal */
export type CreateResponsesRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  "X-Title"?: string | undefined;
  OpenResponsesRequest: models.OpenResponsesRequest$Outbound;
};

/** @internal */
export const CreateResponsesRequest$outboundSchema: z.ZodType<
  CreateResponsesRequest$Outbound,
  CreateResponsesRequest
> = z.object({
  httpReferer: z.string().optional(),
  xTitle: z.string().optional(),
  openResponsesRequest: models.OpenResponsesRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    xTitle: "X-Title",
    openResponsesRequest: "OpenResponsesRequest",
  });
});

export function createResponsesRequestToJSON(
  createResponsesRequest: CreateResponsesRequest,
): string {
  return JSON.stringify(
    CreateResponsesRequest$outboundSchema.parse(createResponsesRequest),
  );
}

/** @internal */
export const CreateResponsesResponseBody$inboundSchema: z.ZodType<
  CreateResponsesResponseBody,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({
        input: v,
        code: "custom",
        message: `malformed json: ${err}`,
      });
      return z.NEVER;
    }
  }).pipe(models.OpenResponsesStreamEvent$inboundSchema),
});

export function createResponsesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateResponsesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateResponsesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateResponsesResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateResponsesResponse$inboundSchema: z.ZodType<
  CreateResponsesResponse,
  unknown
> = z.union([
  models.OpenResponsesNonStreamingResponse$inboundSchema,
  z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true };
        return {
          value: z.lazy(() => CreateResponsesResponseBody$inboundSchema).parse(
            rawEvent,
          )?.data,
        };
      });
    }),
]);

export function createResponsesResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateResponsesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateResponsesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateResponsesResponse' from JSON`,
  );
}
