/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d5a9a6432629
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetAgentContextGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type GetAgentContextRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * The context ID.
   */
  contextId: string;
};

/** @internal */
export type GetAgentContextRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  context_id: string;
};

/** @internal */
export const GetAgentContextRequest$outboundSchema: z.ZodType<
  GetAgentContextRequest$Outbound,
  GetAgentContextRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  contextId: z.string(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    contextId: "context_id",
  });
});

export function getAgentContextRequestToJSON(
  getAgentContextRequest: GetAgentContextRequest,
): string {
  return JSON.stringify(
    GetAgentContextRequest$outboundSchema.parse(getAgentContextRequest),
  );
}
