/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8def1e8eb7b5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListModelsCountGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  xTitle?: string | undefined;
};

export type ListModelsCountRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  xTitle?: string | undefined;
};

/** @internal */
export type ListModelsCountRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  "X-Title"?: string | undefined;
};

/** @internal */
export const ListModelsCountRequest$outboundSchema: z.ZodType<
  ListModelsCountRequest$Outbound,
  ListModelsCountRequest
> = z.object({
  httpReferer: z.string().optional(),
  xTitle: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    xTitle: "X-Title",
  });
});

export function listModelsCountRequestToJSON(
  listModelsCountRequest: ListModelsCountRequest,
): string {
  return JSON.stringify(
    ListModelsCountRequest$outboundSchema.parse(listModelsCountRequest),
  );
}
