/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 37ee24c57c33
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListGuardrailMemberAssignmentsGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  xTitle?: string | undefined;
};

export type ListGuardrailMemberAssignmentsRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  xTitle?: string | undefined;
  /**
   * The unique identifier of the guardrail
   */
  id: string;
  /**
   * Number of records to skip for pagination
   */
  offset?: string | undefined;
  /**
   * Maximum number of records to return (max 100)
   */
  limit?: string | undefined;
};

export type ListGuardrailMemberAssignmentsData = {
  /**
   * Unique identifier for the assignment
   */
  id: string;
  /**
   * Clerk user ID of the assigned member
   */
  userId: string;
  /**
   * Organization ID
   */
  organizationId: string;
  /**
   * ID of the guardrail
   */
  guardrailId: string;
  /**
   * User ID of who made the assignment
   */
  assignedBy: string | null;
  /**
   * ISO 8601 timestamp of when the assignment was created
   */
  createdAt: string;
};

/**
 * List of member assignments
 */
export type ListGuardrailMemberAssignmentsResponse = {
  /**
   * List of member assignments
   */
  data: Array<ListGuardrailMemberAssignmentsData>;
  /**
   * Total number of member assignments
   */
  totalCount: number;
};

/** @internal */
export type ListGuardrailMemberAssignmentsRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  "X-Title"?: string | undefined;
  id: string;
  offset?: string | undefined;
  limit?: string | undefined;
};

/** @internal */
export const ListGuardrailMemberAssignmentsRequest$outboundSchema: z.ZodType<
  ListGuardrailMemberAssignmentsRequest$Outbound,
  ListGuardrailMemberAssignmentsRequest
> = z.object({
  httpReferer: z.string().optional(),
  xTitle: z.string().optional(),
  id: z.string(),
  offset: z.string().optional(),
  limit: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    xTitle: "X-Title",
  });
});

export function listGuardrailMemberAssignmentsRequestToJSON(
  listGuardrailMemberAssignmentsRequest: ListGuardrailMemberAssignmentsRequest,
): string {
  return JSON.stringify(
    ListGuardrailMemberAssignmentsRequest$outboundSchema.parse(
      listGuardrailMemberAssignmentsRequest,
    ),
  );
}

/** @internal */
export const ListGuardrailMemberAssignmentsData$inboundSchema: z.ZodType<
  ListGuardrailMemberAssignmentsData,
  unknown
> = z.object({
  id: z.string(),
  user_id: z.string(),
  organization_id: z.string(),
  guardrail_id: z.string(),
  assigned_by: z.nullable(z.string()),
  created_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
    "organization_id": "organizationId",
    "guardrail_id": "guardrailId",
    "assigned_by": "assignedBy",
    "created_at": "createdAt",
  });
});

export function listGuardrailMemberAssignmentsDataFromJSON(
  jsonString: string,
): SafeParseResult<ListGuardrailMemberAssignmentsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListGuardrailMemberAssignmentsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGuardrailMemberAssignmentsData' from JSON`,
  );
}

/** @internal */
export const ListGuardrailMemberAssignmentsResponse$inboundSchema: z.ZodType<
  ListGuardrailMemberAssignmentsResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => ListGuardrailMemberAssignmentsData$inboundSchema)),
  total_count: z.number(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function listGuardrailMemberAssignmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGuardrailMemberAssignmentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListGuardrailMemberAssignmentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGuardrailMemberAssignmentsResponse' from JSON`,
  );
}
