/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c4b0c0303428
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListKeyAssignmentsRequest = {
  /**
   * Number of records to skip for pagination
   */
  offset?: string | undefined;
  /**
   * Maximum number of records to return (max 100)
   */
  limit?: string | undefined;
};

export type ListKeyAssignmentsData = {
  /**
   * Unique identifier for the assignment
   */
  id: string;
  /**
   * Hash of the assigned API key
   */
  keyHash: string;
  /**
   * ID of the guardrail
   */
  guardrailId: string;
  /**
   * Name of the API key
   */
  keyName: string;
  /**
   * Label of the API key
   */
  keyLabel: string;
  /**
   * User ID of who made the assignment
   */
  assignedBy: string | null;
  /**
   * ISO 8601 timestamp of when the assignment was created
   */
  createdAt: string;
};

/**
 * List of key assignments
 */
export type ListKeyAssignmentsResponse = {
  /**
   * List of key assignments
   */
  data: Array<ListKeyAssignmentsData>;
  /**
   * Total number of key assignments for this guardrail
   */
  totalCount: number;
};

/** @internal */
export type ListKeyAssignmentsRequest$Outbound = {
  offset?: string | undefined;
  limit?: string | undefined;
};

/** @internal */
export const ListKeyAssignmentsRequest$outboundSchema: z.ZodType<
  ListKeyAssignmentsRequest$Outbound,
  ListKeyAssignmentsRequest
> = z.object({
  offset: z.string().optional(),
  limit: z.string().optional(),
});

export function listKeyAssignmentsRequestToJSON(
  listKeyAssignmentsRequest: ListKeyAssignmentsRequest,
): string {
  return JSON.stringify(
    ListKeyAssignmentsRequest$outboundSchema.parse(listKeyAssignmentsRequest),
  );
}

/** @internal */
export const ListKeyAssignmentsData$inboundSchema: z.ZodType<
  ListKeyAssignmentsData,
  unknown
> = z.object({
  id: z.string(),
  key_hash: z.string(),
  guardrail_id: z.string(),
  key_name: z.string(),
  key_label: z.string(),
  assigned_by: z.nullable(z.string()),
  created_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "key_hash": "keyHash",
    "guardrail_id": "guardrailId",
    "key_name": "keyName",
    "key_label": "keyLabel",
    "assigned_by": "assignedBy",
    "created_at": "createdAt",
  });
});

export function listKeyAssignmentsDataFromJSON(
  jsonString: string,
): SafeParseResult<ListKeyAssignmentsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListKeyAssignmentsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListKeyAssignmentsData' from JSON`,
  );
}

/** @internal */
export const ListKeyAssignmentsResponse$inboundSchema: z.ZodType<
  ListKeyAssignmentsResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => ListKeyAssignmentsData$inboundSchema)),
  total_count: z.number(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function listKeyAssignmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListKeyAssignmentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListKeyAssignmentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListKeyAssignmentsResponse' from JSON`,
  );
}
