/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6b5a9008ec50
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateScimGroupMappingGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type UpdateScimGroupMappingRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  id: string;
  updateScimGroupMappingRequest: models.UpdateScimGroupMappingRequest;
};

/** @internal */
export type UpdateScimGroupMappingRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  id: string;
  UpdateScimGroupMappingRequest: models.UpdateScimGroupMappingRequest$Outbound;
};

/** @internal */
export const UpdateScimGroupMappingRequest$outboundSchema: z.ZodType<
  UpdateScimGroupMappingRequest$Outbound,
  UpdateScimGroupMappingRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  id: z.string(),
  updateScimGroupMappingRequest:
    models.UpdateScimGroupMappingRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    updateScimGroupMappingRequest: "UpdateScimGroupMappingRequest",
  });
});

export function updateScimGroupMappingRequestToJSON(
  updateScimGroupMappingRequest: UpdateScimGroupMappingRequest,
): string {
  return JSON.stringify(
    UpdateScimGroupMappingRequest$outboundSchema.parse(
      updateScimGroupMappingRequest,
    ),
  );
}
