/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b6a7d2ff3605
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentMcpServer = {
  /**
   * Optional human-readable name for the MCP server. Surfaced in dashboards but not sent to providers.
   */
  name?: string | undefined;
  /**
   * Remote MCP server URL.
   */
  url: string;
};

/** @internal */
export const AgentMcpServer$inboundSchema: z.ZodType<AgentMcpServer, unknown> =
  z.object({
    name: z.string().optional(),
    url: z.string(),
  });
/** @internal */
export type AgentMcpServer$Outbound = {
  name?: string | undefined;
  url: string;
};

/** @internal */
export const AgentMcpServer$outboundSchema: z.ZodType<
  AgentMcpServer$Outbound,
  AgentMcpServer
> = z.object({
  name: z.string().optional(),
  url: z.string(),
});

export function agentMcpServerToJSON(agentMcpServer: AgentMcpServer): string {
  return JSON.stringify(AgentMcpServer$outboundSchema.parse(agentMcpServer));
}
export function agentMcpServerFromJSON(
  jsonString: string,
): SafeParseResult<AgentMcpServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentMcpServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentMcpServer' from JSON`,
  );
}
