/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d6edb8594120
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AlignmentRuleRecord = {
  /**
   * Whether probability is at or above the threshold.
   */
  broken: boolean;
  /**
   * The evaluator's probability that the turn breaks the rule.
   */
  probability: number;
};

/** @internal */
export const AlignmentRuleRecord$inboundSchema: z.ZodType<
  AlignmentRuleRecord,
  unknown
> = z.object({
  broken: z.boolean(),
  probability: z.number(),
});

export function alignmentRuleRecordFromJSON(
  jsonString: string,
): SafeParseResult<AlignmentRuleRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AlignmentRuleRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AlignmentRuleRecord' from JSON`,
  );
}
