/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e8832cf2f4c5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AnthropicAdvisorToolResult = {
  content: { [k: string]: any };
  toolUseId: string;
  type: "advisor_tool_result";
};

/** @internal */
export const AnthropicAdvisorToolResult$inboundSchema: z.ZodType<
  AnthropicAdvisorToolResult,
  unknown
> = z.object({
  content: z.record(z.string(), z.any()),
  tool_use_id: z.string(),
  type: z.literal("advisor_tool_result"),
}).transform((v) => {
  return remap$(v, {
    "tool_use_id": "toolUseId",
  });
});

export function anthropicAdvisorToolResultFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicAdvisorToolResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicAdvisorToolResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicAdvisorToolResult' from JSON`,
  );
}
