/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8027cdf012a1
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const AnthropicBase64PdfSourceMediaType = {
  ApplicationPdf: "application/pdf",
} as const;
export type AnthropicBase64PdfSourceMediaType = ClosedEnum<
  typeof AnthropicBase64PdfSourceMediaType
>;

export type AnthropicBase64PdfSource = {
  data: string;
  mediaType: AnthropicBase64PdfSourceMediaType;
  type: "base64";
};

/** @internal */
export const AnthropicBase64PdfSourceMediaType$outboundSchema: z.ZodEnum<
  typeof AnthropicBase64PdfSourceMediaType
> = z.enum(AnthropicBase64PdfSourceMediaType);

/** @internal */
export type AnthropicBase64PdfSource$Outbound = {
  data: string;
  media_type: string;
  type: "base64";
};

/** @internal */
export const AnthropicBase64PdfSource$outboundSchema: z.ZodType<
  AnthropicBase64PdfSource$Outbound,
  AnthropicBase64PdfSource
> = z.object({
  data: z.string(),
  mediaType: AnthropicBase64PdfSourceMediaType$outboundSchema,
  type: z.literal("base64"),
}).transform((v) => {
  return remap$(v, {
    mediaType: "media_type",
  });
});

export function anthropicBase64PdfSourceToJSON(
  anthropicBase64PdfSource: AnthropicBase64PdfSource,
): string {
  return JSON.stringify(
    AnthropicBase64PdfSource$outboundSchema.parse(anthropicBase64PdfSource),
  );
}
