/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4c070ad010b0
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnthropicIterationCacheCreation,
  AnthropicIterationCacheCreation$inboundSchema,
} from "./anthropiciterationcachecreation.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AnthropicUnknownUsageIteration = {
  cacheCreation?: AnthropicIterationCacheCreation | null | undefined;
  cacheCreationInputTokens?: number | undefined;
  cacheReadInputTokens?: number | undefined;
  inputTokens?: number | undefined;
  outputTokens?: number | undefined;
  type: string;
};

/** @internal */
export const AnthropicUnknownUsageIteration$inboundSchema: z.ZodType<
  AnthropicUnknownUsageIteration,
  unknown
> = z.object({
  cache_creation: z.nullable(AnthropicIterationCacheCreation$inboundSchema)
    .optional(),
  cache_creation_input_tokens: z.int().optional(),
  cache_read_input_tokens: z.int().optional(),
  input_tokens: z.int().optional(),
  output_tokens: z.int().optional(),
  type: z.string(),
}).transform((v) => {
  return remap$(v, {
    "cache_creation": "cacheCreation",
    "cache_creation_input_tokens": "cacheCreationInputTokens",
    "cache_read_input_tokens": "cacheReadInputTokens",
    "input_tokens": "inputTokens",
    "output_tokens": "outputTokens",
  });
});

export function anthropicUnknownUsageIterationFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicUnknownUsageIteration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicUnknownUsageIteration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicUnknownUsageIteration' from JSON`,
  );
}
