/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e9776d496704
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AnthropicCitationPageLocation = {
  citedText: string;
  documentIndex: number;
  documentTitle: string | null;
  endPageNumber: number;
  fileId: string | null;
  startPageNumber: number;
  type: "page_location";
};

/** @internal */
export const AnthropicCitationPageLocation$inboundSchema: z.ZodType<
  AnthropicCitationPageLocation,
  unknown
> = z.object({
  cited_text: z.string(),
  document_index: z.int(),
  document_title: z.nullable(z.string()),
  end_page_number: z.int(),
  file_id: z.nullable(z.string()),
  start_page_number: z.int(),
  type: z.literal("page_location"),
}).transform((v) => {
  return remap$(v, {
    "cited_text": "citedText",
    "document_index": "documentIndex",
    "document_title": "documentTitle",
    "end_page_number": "endPageNumber",
    "file_id": "fileId",
    "start_page_number": "startPageNumber",
  });
});

export function anthropicCitationPageLocationFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicCitationPageLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicCitationPageLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicCitationPageLocation' from JSON`,
  );
}
