/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86635cf190c0
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AnthropicTextEditorCodeExecutionCreateResult = {
  isFileUpdate: boolean;
  type: "text_editor_code_execution_create_result";
};

/** @internal */
export const AnthropicTextEditorCodeExecutionCreateResult$inboundSchema:
  z.ZodType<AnthropicTextEditorCodeExecutionCreateResult, unknown> = z.object({
    is_file_update: z.boolean(),
    type: z.literal("text_editor_code_execution_create_result"),
  }).transform((v) => {
    return remap$(v, {
      "is_file_update": "isFileUpdate",
    });
  });

export function anthropicTextEditorCodeExecutionCreateResultFromJSON(
  jsonString: string,
): SafeParseResult<
  AnthropicTextEditorCodeExecutionCreateResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AnthropicTextEditorCodeExecutionCreateResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AnthropicTextEditorCodeExecutionCreateResult' from JSON`,
  );
}
