/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6772980a7ab5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AnthropicCacheCreation = {
  ephemeral1hInputTokens: number;
  ephemeral5mInputTokens: number;
};

/** @internal */
export const AnthropicCacheCreation$inboundSchema: z.ZodType<
  AnthropicCacheCreation,
  unknown
> = z.object({
  ephemeral_1h_input_tokens: z.int(),
  ephemeral_5m_input_tokens: z.int(),
}).transform((v) => {
  return remap$(v, {
    "ephemeral_1h_input_tokens": "ephemeral1hInputTokens",
    "ephemeral_5m_input_tokens": "ephemeral5mInputTokens",
  });
});

export function anthropicCacheCreationFromJSON(
  jsonString: string,
): SafeParseResult<AnthropicCacheCreation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnthropicCacheCreation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnthropicCacheCreation' from JSON`,
  );
}
