/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 484246536971
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  AnthropicAllowedCallers20260318,
  AnthropicAllowedCallers20260318$outboundSchema,
} from "./anthropicallowedcallers20260318.js";
import {
  AnthropicCacheControlTtl,
  AnthropicCacheControlTtl$outboundSchema,
} from "./anthropiccachecontrolttl.js";
import {
  AnthropicResponseInclusion,
  AnthropicResponseInclusion$outboundSchema,
} from "./anthropicresponseinclusion.js";
import {
  AnthropicWebSearchToolUserLocation,
  AnthropicWebSearchToolUserLocation$Outbound,
  AnthropicWebSearchToolUserLocation$outboundSchema,
} from "./anthropicwebsearchtooluserlocation.js";

export const AnthropicWebSearchTool20260318TypeEphemeral = {
  Ephemeral: "ephemeral",
} as const;
export type AnthropicWebSearchTool20260318TypeEphemeral = ClosedEnum<
  typeof AnthropicWebSearchTool20260318TypeEphemeral
>;

/**
 * Enable automatic prompt caching. When set at the top level, the system automatically applies cache breakpoints to the last cacheable block in the request. When set on an individual content block, it marks an explicit cache breakpoint; block-level markers also work on OpenAI models that support explicit prompt caching — OpenRouter converts them to the provider's native format.
 */
export type AnthropicWebSearchTool20260318CacheControl = {
  ttl?: AnthropicCacheControlTtl | undefined;
  type: AnthropicWebSearchTool20260318TypeEphemeral;
};

export const AnthropicWebSearchTool20260318Name = {
  WebSearch: "web_search",
} as const;
export type AnthropicWebSearchTool20260318Name = ClosedEnum<
  typeof AnthropicWebSearchTool20260318Name
>;

export const TypeWebSearch20260318 = {
  WebSearch20260318: "web_search_20260318",
} as const;
export type TypeWebSearch20260318 = ClosedEnum<typeof TypeWebSearch20260318>;

export type AnthropicWebSearchTool20260318 = {
  allowedCallers?: Array<AnthropicAllowedCallers20260318> | undefined;
  allowedDomains?: Array<string> | null | undefined;
  blockedDomains?: Array<string> | null | undefined;
  cacheControl?: AnthropicWebSearchTool20260318CacheControl | null | undefined;
  deferLoading?: boolean | undefined;
  maxUses?: number | null | undefined;
  name: AnthropicWebSearchTool20260318Name;
  responseInclusion?: AnthropicResponseInclusion | undefined;
  strict?: boolean | undefined;
  type: TypeWebSearch20260318;
  userLocation?: AnthropicWebSearchToolUserLocation | null | undefined;
};

/** @internal */
export const AnthropicWebSearchTool20260318TypeEphemeral$outboundSchema:
  z.ZodEnum<typeof AnthropicWebSearchTool20260318TypeEphemeral> = z.enum(
    AnthropicWebSearchTool20260318TypeEphemeral,
  );

/** @internal */
export type AnthropicWebSearchTool20260318CacheControl$Outbound = {
  ttl?: string | undefined;
  type: string;
};

/** @internal */
export const AnthropicWebSearchTool20260318CacheControl$outboundSchema:
  z.ZodType<
    AnthropicWebSearchTool20260318CacheControl$Outbound,
    AnthropicWebSearchTool20260318CacheControl
  > = z.object({
    ttl: AnthropicCacheControlTtl$outboundSchema.optional(),
    type: AnthropicWebSearchTool20260318TypeEphemeral$outboundSchema,
  });

export function anthropicWebSearchTool20260318CacheControlToJSON(
  anthropicWebSearchTool20260318CacheControl:
    AnthropicWebSearchTool20260318CacheControl,
): string {
  return JSON.stringify(
    AnthropicWebSearchTool20260318CacheControl$outboundSchema.parse(
      anthropicWebSearchTool20260318CacheControl,
    ),
  );
}

/** @internal */
export const AnthropicWebSearchTool20260318Name$outboundSchema: z.ZodEnum<
  typeof AnthropicWebSearchTool20260318Name
> = z.enum(AnthropicWebSearchTool20260318Name);

/** @internal */
export const TypeWebSearch20260318$outboundSchema: z.ZodEnum<
  typeof TypeWebSearch20260318
> = z.enum(TypeWebSearch20260318);

/** @internal */
export type AnthropicWebSearchTool20260318$Outbound = {
  allowed_callers?: Array<string> | undefined;
  allowed_domains?: Array<string> | null | undefined;
  blocked_domains?: Array<string> | null | undefined;
  cache_control?:
    | AnthropicWebSearchTool20260318CacheControl$Outbound
    | null
    | undefined;
  defer_loading?: boolean | undefined;
  max_uses?: number | null | undefined;
  name: string;
  response_inclusion?: string | undefined;
  strict?: boolean | undefined;
  type: string;
  user_location?:
    | AnthropicWebSearchToolUserLocation$Outbound
    | null
    | undefined;
};

/** @internal */
export const AnthropicWebSearchTool20260318$outboundSchema: z.ZodType<
  AnthropicWebSearchTool20260318$Outbound,
  AnthropicWebSearchTool20260318
> = z.object({
  allowedCallers: z.array(AnthropicAllowedCallers20260318$outboundSchema)
    .optional(),
  allowedDomains: z.nullable(z.array(z.string())).optional(),
  blockedDomains: z.nullable(z.array(z.string())).optional(),
  cacheControl: z.nullable(
    z.lazy(() => AnthropicWebSearchTool20260318CacheControl$outboundSchema),
  ).optional(),
  deferLoading: z.boolean().optional(),
  maxUses: z.nullable(z.int()).optional(),
  name: AnthropicWebSearchTool20260318Name$outboundSchema,
  responseInclusion: AnthropicResponseInclusion$outboundSchema.optional(),
  strict: z.boolean().optional(),
  type: TypeWebSearch20260318$outboundSchema,
  userLocation: z.nullable(AnthropicWebSearchToolUserLocation$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    allowedCallers: "allowed_callers",
    allowedDomains: "allowed_domains",
    blockedDomains: "blocked_domains",
    cacheControl: "cache_control",
    deferLoading: "defer_loading",
    maxUses: "max_uses",
    responseInclusion: "response_inclusion",
    userLocation: "user_location",
  });
});

export function anthropicWebSearchTool20260318ToJSON(
  anthropicWebSearchTool20260318: AnthropicWebSearchTool20260318,
): string {
  return JSON.stringify(
    AnthropicWebSearchTool20260318$outboundSchema.parse(
      anthropicWebSearchTool20260318,
    ),
  );
}
