/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8c545705b9ae
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const AnthropicSpeed = {
  Fast: "fast",
  Standard: "standard",
} as const;
export type AnthropicSpeed = OpenEnum<typeof AnthropicSpeed>;

/** @internal */
export const AnthropicSpeed$inboundSchema: z.ZodType<AnthropicSpeed, unknown> =
  openEnums.inboundSchema(AnthropicSpeed);
