/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dc2d569c8386
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

export type BulkAddWorkspaceMembersRequest = {
  /**
   * List of user IDs to add to the workspace. Members are assigned the same role they hold in the organization.
   */
  memberUserIds: Array<string>;
};

/** @internal */
export type BulkAddWorkspaceMembersRequest$Outbound = {
  member_user_ids: Array<string>;
};

/** @internal */
export const BulkAddWorkspaceMembersRequest$outboundSchema: z.ZodType<
  BulkAddWorkspaceMembersRequest$Outbound,
  BulkAddWorkspaceMembersRequest
> = z.object({
  memberUserIds: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    memberUserIds: "member_user_ids",
  });
});

export function bulkAddWorkspaceMembersRequestToJSON(
  bulkAddWorkspaceMembersRequest: BulkAddWorkspaceMembersRequest,
): string {
  return JSON.stringify(
    BulkAddWorkspaceMembersRequest$outboundSchema.parse(
      bulkAddWorkspaceMembersRequest,
    ),
  );
}
