/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ChatContentCacheControlType = {
  Ephemeral: "ephemeral",
} as const;
export type ChatContentCacheControlType = ClosedEnum<
  typeof ChatContentCacheControlType
>;

export const ChatContentCacheControlTtl = {
  Fivem: "5m",
  Oneh: "1h",
} as const;
export type ChatContentCacheControlTtl = OpenEnum<
  typeof ChatContentCacheControlTtl
>;

/**
 * Cache control for the content part
 */
export type ChatContentCacheControl = {
  type: ChatContentCacheControlType;
  ttl?: ChatContentCacheControlTtl | undefined;
};

/** @internal */
export const ChatContentCacheControlType$inboundSchema: z.ZodEnum<
  typeof ChatContentCacheControlType
> = z.enum(ChatContentCacheControlType);
/** @internal */
export const ChatContentCacheControlType$outboundSchema: z.ZodEnum<
  typeof ChatContentCacheControlType
> = ChatContentCacheControlType$inboundSchema;

/** @internal */
export const ChatContentCacheControlTtl$inboundSchema: z.ZodType<
  ChatContentCacheControlTtl,
  unknown
> = openEnums.inboundSchema(ChatContentCacheControlTtl);
/** @internal */
export const ChatContentCacheControlTtl$outboundSchema: z.ZodType<
  string,
  ChatContentCacheControlTtl
> = openEnums.outboundSchema(ChatContentCacheControlTtl);

/** @internal */
export const ChatContentCacheControl$inboundSchema: z.ZodType<
  ChatContentCacheControl,
  unknown
> = z.object({
  type: ChatContentCacheControlType$inboundSchema,
  ttl: ChatContentCacheControlTtl$inboundSchema.optional(),
});
/** @internal */
export type ChatContentCacheControl$Outbound = {
  type: string;
  ttl?: string | undefined;
};

/** @internal */
export const ChatContentCacheControl$outboundSchema: z.ZodType<
  ChatContentCacheControl$Outbound,
  ChatContentCacheControl
> = z.object({
  type: ChatContentCacheControlType$outboundSchema,
  ttl: ChatContentCacheControlTtl$outboundSchema.optional(),
});

export function chatContentCacheControlToJSON(
  chatContentCacheControl: ChatContentCacheControl,
): string {
  return JSON.stringify(
    ChatContentCacheControl$outboundSchema.parse(chatContentCacheControl),
  );
}
export function chatContentCacheControlFromJSON(
  jsonString: string,
): SafeParseResult<ChatContentCacheControl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatContentCacheControl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatContentCacheControl' from JSON`,
  );
}
