/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 125d1fe30400
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Audio output data or reference
 */
export type ChatCompletionAudioOutput = {
  /**
   * Audio output identifier
   */
  id?: string | undefined;
  /**
   * Audio expiration timestamp
   */
  expiresAt?: number | undefined;
  /**
   * Base64 encoded audio data
   */
  data?: string | undefined;
  /**
   * Audio transcript
   */
  transcript?: string | undefined;
};

/** @internal */
export const ChatCompletionAudioOutput$inboundSchema: z.ZodType<
  ChatCompletionAudioOutput,
  unknown
> = z.object({
  id: z.string().optional(),
  expires_at: z.number().optional(),
  data: z.string().optional(),
  transcript: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "expires_at": "expiresAt",
  });
});
/** @internal */
export type ChatCompletionAudioOutput$Outbound = {
  id?: string | undefined;
  expires_at?: number | undefined;
  data?: string | undefined;
  transcript?: string | undefined;
};

/** @internal */
export const ChatCompletionAudioOutput$outboundSchema: z.ZodType<
  ChatCompletionAudioOutput$Outbound,
  ChatCompletionAudioOutput
> = z.object({
  id: z.string().optional(),
  expiresAt: z.number().optional(),
  data: z.string().optional(),
  transcript: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    expiresAt: "expires_at",
  });
});

export function chatCompletionAudioOutputToJSON(
  chatCompletionAudioOutput: ChatCompletionAudioOutput,
): string {
  return JSON.stringify(
    ChatCompletionAudioOutput$outboundSchema.parse(chatCompletionAudioOutput),
  );
}
export function chatCompletionAudioOutputFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionAudioOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionAudioOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionAudioOutput' from JSON`,
  );
}
