/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6c32bdd2ee5d
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Debug options for inspecting request transformations (streaming only)
 */
export type ChatDebugOptions = {
  /**
   * If true, includes the transformed upstream request body in a debug chunk at the start of the stream. Only works with streaming mode.
   */
  echoUpstreamBody?: boolean | undefined;
};

/** @internal */
export type ChatDebugOptions$Outbound = {
  echo_upstream_body?: boolean | undefined;
};

/** @internal */
export const ChatDebugOptions$outboundSchema: z.ZodType<
  ChatDebugOptions$Outbound,
  ChatDebugOptions
> = z.object({
  echoUpstreamBody: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    echoUpstreamBody: "echo_upstream_body",
  });
});

export function chatDebugOptionsToJSON(
  chatDebugOptions: ChatDebugOptions,
): string {
  return JSON.stringify(
    ChatDebugOptions$outboundSchema.parse(chatDebugOptions),
  );
}
