/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b294b44052da
 */

import type { Result as SafeParseResult } from '../types/fp.js';
import type { SDKValidationError } from './errors/sdkvalidationerror.js';

import * as z from 'zod/v4';
import { safeParse } from '../lib/schemas.js';

export type ChatMessageToolCallFunction = {
  name: string;
  arguments: string;
};

export type ChatMessageToolCall = {
  id: string;
  type: 'function';
  function: ChatMessageToolCallFunction;
};

/** @internal */
export const ChatMessageToolCallFunction$inboundSchema: z.ZodType<
  ChatMessageToolCallFunction,
  unknown
> = z.object({
  name: z.string(),
  arguments: z.string(),
});
/** @internal */
export type ChatMessageToolCallFunction$Outbound = {
  name: string;
  arguments: string;
};

/** @internal */
export const ChatMessageToolCallFunction$outboundSchema: z.ZodType<
  ChatMessageToolCallFunction$Outbound,
  ChatMessageToolCallFunction
> = z.object({
  name: z.string(),
  arguments: z.string(),
});

export function chatMessageToolCallFunctionToJSON(
  chatMessageToolCallFunction: ChatMessageToolCallFunction,
): string {
  return JSON.stringify(
    ChatMessageToolCallFunction$outboundSchema.parse(chatMessageToolCallFunction),
  );
}
export function chatMessageToolCallFunctionFromJSON(
  jsonString: string,
): SafeParseResult<ChatMessageToolCallFunction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatMessageToolCallFunction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatMessageToolCallFunction' from JSON`,
  );
}

/** @internal */
export const ChatMessageToolCall$inboundSchema: z.ZodType<ChatMessageToolCall, unknown> = z.object({
  id: z.string(),
  type: z.literal('function'),
  function: z.lazy(() => ChatMessageToolCallFunction$inboundSchema),
});
/** @internal */
export type ChatMessageToolCall$Outbound = {
  id: string;
  type: 'function';
  function: ChatMessageToolCallFunction$Outbound;
};

/** @internal */
export const ChatMessageToolCall$outboundSchema: z.ZodType<
  ChatMessageToolCall$Outbound,
  ChatMessageToolCall
> = z.object({
  id: z.string(),
  type: z.literal('function'),
  function: z.lazy(() => ChatMessageToolCallFunction$outboundSchema),
});

export function chatMessageToolCallToJSON(chatMessageToolCall: ChatMessageToolCall): string {
  return JSON.stringify(ChatMessageToolCall$outboundSchema.parse(chatMessageToolCall));
}
export function chatMessageToolCallFromJSON(
  jsonString: string,
): SafeParseResult<ChatMessageToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatMessageToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatMessageToolCall' from JSON`,
  );
}
