/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 507759b9db28
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const CompletionStatus = {
  Completed: "completed",
  InProgress: "in_progress",
  Incomplete: "incomplete",
} as const;
export type CompletionStatus = OpenEnum<typeof CompletionStatus>;

/** @internal */
export const CompletionStatus$inboundSchema: z.ZodType<
  CompletionStatus,
  unknown
> = openEnums.inboundSchema(CompletionStatus);
/** @internal */
export const CompletionStatus$outboundSchema: z.ZodType<
  string,
  CompletionStatus
> = openEnums.outboundSchema(CompletionStatus);
