/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4c9b1effbc1
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ContentFilterBuiltinAction,
  ContentFilterBuiltinAction$inboundSchema,
} from "./contentfilterbuiltinaction.js";
import {
  ContentFilterBuiltinSlug,
  ContentFilterBuiltinSlug$inboundSchema,
} from "./contentfilterbuiltinslug.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PromptInjectionScanScope,
  PromptInjectionScanScope$inboundSchema,
} from "./promptinjectionscanscope.js";

/**
 * A builtin content filter entry. Builtin filters include PII detectors and the regex-based prompt injection detector.
 */
export type ContentFilterBuiltinEntry = {
  /**
   * Action taken when the builtin filter triggers
   */
  action: ContentFilterBuiltinAction;
  /**
   * Read-only, system-assigned redaction placeholder derived from the slug (e.g. "[EMAIL]", "[PHONE]"). Not settable by the caller.
   */
  label?: string | undefined;
  /**
   * Which message roles to scan for prompt injection. Only applies to the regex-prompt-injection builtin. Defaults to all_messages.
   */
  scanScope?: PromptInjectionScanScope | undefined;
  /**
   * The builtin filter identifier
   */
  slug: ContentFilterBuiltinSlug;
};

/** @internal */
export const ContentFilterBuiltinEntry$inboundSchema: z.ZodType<
  ContentFilterBuiltinEntry,
  unknown
> = z.object({
  action: ContentFilterBuiltinAction$inboundSchema,
  label: z.string().optional(),
  scan_scope: PromptInjectionScanScope$inboundSchema.optional(),
  slug: ContentFilterBuiltinSlug$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "scan_scope": "scanScope",
  });
});

export function contentFilterBuiltinEntryFromJSON(
  jsonString: string,
): SafeParseResult<ContentFilterBuiltinEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContentFilterBuiltinEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContentFilterBuiltinEntry' from JSON`,
  );
}
