/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4d8b08fcbb5
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";
import {
  DatetimeServerToolConfig,
  DatetimeServerToolConfig$Outbound,
  DatetimeServerToolConfig$outboundSchema,
} from "./datetimeservertoolconfig.js";

export const DatetimeServerToolType = {
  OpenrouterDatetime: "openrouter:datetime",
} as const;
export type DatetimeServerToolType = ClosedEnum<typeof DatetimeServerToolType>;

/**
 * OpenRouter built-in server tool: returns the current date and time
 */
export type DatetimeServerTool = {
  /**
   * Configuration for the openrouter:datetime server tool
   */
  parameters?: DatetimeServerToolConfig | undefined;
  type: DatetimeServerToolType;
};

/** @internal */
export const DatetimeServerToolType$outboundSchema: z.ZodEnum<
  typeof DatetimeServerToolType
> = z.enum(DatetimeServerToolType);

/** @internal */
export type DatetimeServerTool$Outbound = {
  parameters?: DatetimeServerToolConfig$Outbound | undefined;
  type: string;
};

/** @internal */
export const DatetimeServerTool$outboundSchema: z.ZodType<
  DatetimeServerTool$Outbound,
  DatetimeServerTool
> = z.object({
  parameters: DatetimeServerToolConfig$outboundSchema.optional(),
  type: DatetimeServerToolType$outboundSchema,
});

export function datetimeServerToolToJSON(
  datetimeServerTool: DatetimeServerTool,
): string {
  return JSON.stringify(
    DatetimeServerTool$outboundSchema.parse(datetimeServerTool),
  );
}
