/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Default parameters for this model
 */
export type DefaultParameters = {
  temperature?: number | null | undefined;
  topP?: number | null | undefined;
  topK?: number | null | undefined;
  frequencyPenalty?: number | null | undefined;
  presencePenalty?: number | null | undefined;
  repetitionPenalty?: number | null | undefined;
};

/** @internal */
export const DefaultParameters$inboundSchema: z.ZodType<
  DefaultParameters,
  unknown
> = z.object({
  temperature: z.nullable(z.number()).optional(),
  top_p: z.nullable(z.number()).optional(),
  top_k: z.nullable(z.int()).optional(),
  frequency_penalty: z.nullable(z.number()).optional(),
  presence_penalty: z.nullable(z.number()).optional(),
  repetition_penalty: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    "top_p": "topP",
    "top_k": "topK",
    "frequency_penalty": "frequencyPenalty",
    "presence_penalty": "presencePenalty",
    "repetition_penalty": "repetitionPenalty",
  });
});

export function defaultParametersFromJSON(
  jsonString: string,
): SafeParseResult<DefaultParameters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DefaultParameters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DefaultParameters' from JSON`,
  );
}
