/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 83efda25dcf0
 */

import type * as z from 'zod/v4';
import type { OpenEnum } from '../types/enums.js';

import * as openEnums from '../types/enums.js';

export const EndpointStatus = {
  Zero: 0,
  Minus1: -1,
  Minus2: -2,
  Minus3: -3,
  Minus5: -5,
  Minus10: -10,
} as const;
export type EndpointStatus = OpenEnum<typeof EndpointStatus>;

/** @internal */
export const EndpointStatus$inboundSchema: z.ZodType<EndpointStatus, unknown> =
  openEnums.inboundSchemaInt(EndpointStatus);
