/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const EndpointStatus = {
  Zero: 0,
  Minus1: -1,
  Minus2: -2,
  Minus3: -3,
  Minus5: -5,
  Minus10: -10,
} as const;
export type EndpointStatus = OpenEnum<typeof EndpointStatus>;

/** @internal */
export const EndpointStatus$inboundSchema: z.ZodType<EndpointStatus, unknown> =
  openEnums.inboundSchemaInt(EndpointStatus);
