/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5ad7989f6f99
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A parameter that accepts one of a discrete set of string values.
 */
export type EnumCapability = {
  type: "enum";
  values: Array<string>;
};

/** @internal */
export const EnumCapability$inboundSchema: z.ZodType<EnumCapability, unknown> =
  z.object({
    type: z.literal("enum"),
    values: z.array(z.string()),
  });

export function enumCapabilityFromJSON(
  jsonString: string,
): SafeParseResult<EnumCapability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnumCapability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnumCapability' from JSON`,
  );
}
