/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4978ed568c7
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnthropicFileList,
  AnthropicFileList$inboundSchema,
} from "./anthropicfilelist.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OpenAIFileList,
  OpenAIFileList$inboundSchema,
} from "./openaifilelist.js";
import {
  OpenRouterFileList,
  OpenRouterFileList$inboundSchema,
} from "./openrouterfilelist.js";

/**
 * A page of files, in the negotiated shape.
 */
export type FileListResponse =
  | AnthropicFileList
  | OpenAIFileList
  | OpenRouterFileList
  | discriminatedUnionTypes.Unknown<"shape">;

/** @internal */
export const FileListResponse$inboundSchema: z.ZodType<
  FileListResponse,
  unknown
> = discriminatedUnion("_shape", {
  anthropic: AnthropicFileList$inboundSchema,
  openai: OpenAIFileList$inboundSchema,
  openrouter: OpenRouterFileList$inboundSchema,
}, { outputPropertyName: "shape" });

export function fileListResponseFromJSON(
  jsonString: string,
): SafeParseResult<FileListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileListResponse' from JSON`,
  );
}
