/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 500c34bd192b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Configuration for the openrouter:fusion server tool.
 */
export type FusionServerToolConfig = {
  /**
   * Slugs of models to run in parallel as the analysis panel. Each model receives the user prompt with openrouter:web_search and openrouter:web_fetch enabled, then a judge model summarizes the collective output into structured analysis JSON. Capped at 8 models to bound cost amplification. Defaults to the Quality preset from /labs/fusion.
   */
  analysisModels?: Array<string> | undefined;
  /**
   * Maximum number of tool-calling steps each panelist (analysis model) and the judge model may take during their agentic web-research loop. Models with web_search/web_fetch enabled iterate until they produce a text response or hit this ceiling. Defaults to 8. Capped at 16.
   */
  maxToolCalls?: number | undefined;
  /**
   * Slug of the judge model that produces the structured analysis JSON. Defaults to the model used in the outer API request.
   */
  model?: string | undefined;
};

/** @internal */
export type FusionServerToolConfig$Outbound = {
  analysis_models?: Array<string> | undefined;
  max_tool_calls?: number | undefined;
  model?: string | undefined;
};

/** @internal */
export const FusionServerToolConfig$outboundSchema: z.ZodType<
  FusionServerToolConfig$Outbound,
  FusionServerToolConfig
> = z.object({
  analysisModels: z.array(z.string()).optional(),
  maxToolCalls: z.int().optional(),
  model: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    analysisModels: "analysis_models",
    maxToolCalls: "max_tool_calls",
  });
});

export function fusionServerToolConfigToJSON(
  fusionServerToolConfig: FusionServerToolConfig,
): string {
  return JSON.stringify(
    FusionServerToolConfig$outboundSchema.parse(fusionServerToolConfig),
  );
}
