/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f55aeaffdbd5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Input2 = {
  messages: Array<any>;
};

export type Input1 = {
  prompt: string;
};

/**
 * The input to the generation — either a prompt string or an array of messages
 */
export type InputUnion = Input1 | Input2;

export type GenerationContentDataFunction = {
  arguments: string;
  name: string;
};

export const ToolKind = {
  Function: "function",
  Custom: "custom",
} as const;
export type ToolKind = OpenEnum<typeof ToolKind>;

export const GenerationContentDataType = {
  Function: "function",
} as const;
export type GenerationContentDataType = ClosedEnum<
  typeof GenerationContentDataType
>;

export type ToolCall = {
  function: GenerationContentDataFunction;
  id: string;
  namespace?: string | undefined;
  toolKind?: ToolKind | undefined;
  type: GenerationContentDataType;
};

/**
 * The output from the generation
 */
export type GenerationContentDataOutput = {
  /**
   * The completion output
   */
  completion: string | null;
  /**
   * Reasoning/thinking output, if any
   */
  reasoning: string | null;
  /**
   * Structured tool calls emitted by the model, if any
   */
  toolCalls: Array<ToolCall> | null;
};

/**
 * Stored prompt and completion content
 */
export type GenerationContentData = {
  /**
   * The input to the generation — either a prompt string or an array of messages
   */
  input: Input1 | Input2;
  /**
   * The output from the generation
   */
  output: GenerationContentDataOutput;
};

/** @internal */
export const Input2$inboundSchema: z.ZodType<Input2, unknown> = z.object({
  messages: z.array(z.any()),
});

export function input2FromJSON(
  jsonString: string,
): SafeParseResult<Input2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Input2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Input2' from JSON`,
  );
}

/** @internal */
export const Input1$inboundSchema: z.ZodType<Input1, unknown> = z.object({
  prompt: z.string(),
});

export function input1FromJSON(
  jsonString: string,
): SafeParseResult<Input1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Input1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Input1' from JSON`,
  );
}

/** @internal */
export const InputUnion$inboundSchema: z.ZodType<InputUnion, unknown> = z.union(
  [z.lazy(() => Input1$inboundSchema), z.lazy(() => Input2$inboundSchema)],
);

export function inputUnionFromJSON(
  jsonString: string,
): SafeParseResult<InputUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputUnion' from JSON`,
  );
}

/** @internal */
export const GenerationContentDataFunction$inboundSchema: z.ZodType<
  GenerationContentDataFunction,
  unknown
> = z.object({
  arguments: z.string(),
  name: z.string(),
});

export function generationContentDataFunctionFromJSON(
  jsonString: string,
): SafeParseResult<GenerationContentDataFunction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerationContentDataFunction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerationContentDataFunction' from JSON`,
  );
}

/** @internal */
export const ToolKind$inboundSchema: z.ZodType<ToolKind, unknown> = openEnums
  .inboundSchema(ToolKind);

/** @internal */
export const GenerationContentDataType$inboundSchema: z.ZodEnum<
  typeof GenerationContentDataType
> = z.enum(GenerationContentDataType);

/** @internal */
export const ToolCall$inboundSchema: z.ZodType<ToolCall, unknown> = z.object({
  function: z.lazy(() => GenerationContentDataFunction$inboundSchema),
  id: z.string(),
  namespace: z.string().optional(),
  tool_kind: ToolKind$inboundSchema.optional(),
  type: GenerationContentDataType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "tool_kind": "toolKind",
  });
});

export function toolCallFromJSON(
  jsonString: string,
): SafeParseResult<ToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolCall' from JSON`,
  );
}

/** @internal */
export const GenerationContentDataOutput$inboundSchema: z.ZodType<
  GenerationContentDataOutput,
  unknown
> = z.object({
  completion: z.nullable(z.string()),
  reasoning: z.nullable(z.string()),
  tool_calls: z.nullable(z.array(z.lazy(() => ToolCall$inboundSchema))),
}).transform((v) => {
  return remap$(v, {
    "tool_calls": "toolCalls",
  });
});

export function generationContentDataOutputFromJSON(
  jsonString: string,
): SafeParseResult<GenerationContentDataOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerationContentDataOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerationContentDataOutput' from JSON`,
  );
}

/** @internal */
export const GenerationContentData$inboundSchema: z.ZodType<
  GenerationContentData,
  unknown
> = z.object({
  input: z.union([
    z.lazy(() => Input1$inboundSchema),
    z.lazy(() => Input2$inboundSchema),
  ]),
  output: z.lazy(() => GenerationContentDataOutput$inboundSchema),
});

export function generationContentDataFromJSON(
  jsonString: string,
): SafeParseResult<GenerationContentData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerationContentData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerationContentData' from JSON`,
  );
}
