/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 55445c92cf9f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { ProviderName, ProviderName$outboundSchema } from "./providername.js";
import { ProviderSort, ProviderSort$outboundSchema } from "./providersort.js";
import {
  ProviderSortConfig,
  ProviderSortConfig$Outbound,
  ProviderSortConfig$outboundSchema,
} from "./providersortconfig.js";

export type ImageGenerationProviderPreferencesIgnore = ProviderName | string;

export type ImageGenerationProviderPreferencesOnly = ProviderName | string;

/**
 * Provider-specific options keyed by provider slug. Only options for the matched provider are forwarded; the rest are ignored. Unrecognized keys are silently dropped.
 */
export type ImageGenerationProviderPreferencesOptions = {
  oneai?: { [k: string]: any | null } | undefined;
  ai21?: { [k: string]: any | null } | undefined;
  aionLabs?: { [k: string]: any | null } | undefined;
  akashml?: { [k: string]: any | null } | undefined;
  alibaba?: { [k: string]: any | null } | undefined;
  amazonBedrock?: { [k: string]: any | null } | undefined;
  amazonNova?: { [k: string]: any | null } | undefined;
  ambient?: { [k: string]: any | null } | undefined;
  anthropic?: { [k: string]: any | null } | undefined;
  anyscale?: { [k: string]: any | null } | undefined;
  arceeAi?: { [k: string]: any | null } | undefined;
  atlasCloud?: { [k: string]: any | null } | undefined;
  atoma?: { [k: string]: any | null } | undefined;
  avian?: { [k: string]: any | null } | undefined;
  azure?: { [k: string]: any | null } | undefined;
  baidu?: { [k: string]: any | null } | undefined;
  baseten?: { [k: string]: any | null } | undefined;
  blackForestLabs?: { [k: string]: any | null } | undefined;
  byteplus?: { [k: string]: any | null } | undefined;
  centml?: { [k: string]: any | null } | undefined;
  cerebras?: { [k: string]: any | null } | undefined;
  chutes?: { [k: string]: any | null } | undefined;
  cirrascale?: { [k: string]: any | null } | undefined;
  clarifai?: { [k: string]: any | null } | undefined;
  cloudflare?: { [k: string]: any | null } | undefined;
  cohere?: { [k: string]: any | null } | undefined;
  crofai?: { [k: string]: any | null } | undefined;
  crucible?: { [k: string]: any | null } | undefined;
  crusoe?: { [k: string]: any | null } | undefined;
  darkbloom?: { [k: string]: any | null } | undefined;
  decart?: { [k: string]: any | null } | undefined;
  deepgram?: { [k: string]: any | null } | undefined;
  deepinfra?: { [k: string]: any | null } | undefined;
  deepseek?: { [k: string]: any | null } | undefined;
  dekallm?: { [k: string]: any | null } | undefined;
  digitalocean?: { [k: string]: any | null } | undefined;
  enfer?: { [k: string]: any | null } | undefined;
  fakeProvider?: { [k: string]: any | null } | undefined;
  featherless?: { [k: string]: any | null } | undefined;
  fireworks?: { [k: string]: any | null } | undefined;
  friendli?: { [k: string]: any | null } | undefined;
  gmicloud?: { [k: string]: any | null } | undefined;
  googleAiStudio?: { [k: string]: any | null } | undefined;
  googleVertex?: { [k: string]: any | null } | undefined;
  gopomelo?: { [k: string]: any | null } | undefined;
  groq?: { [k: string]: any | null } | undefined;
  heygen?: { [k: string]: any | null } | undefined;
  huggingface?: { [k: string]: any | null } | undefined;
  hyperbolic?: { [k: string]: any | null } | undefined;
  hyperbolicQuantized?: { [k: string]: any | null } | undefined;
  inception?: { [k: string]: any | null } | undefined;
  inceptron?: { [k: string]: any | null } | undefined;
  inferactVllm?: { [k: string]: any | null } | undefined;
  inferenceNet?: { [k: string]: any | null } | undefined;
  infermatic?: { [k: string]: any | null } | undefined;
  inflection?: { [k: string]: any | null } | undefined;
  inocloud?: { [k: string]: any | null } | undefined;
  ioNet?: { [k: string]: any | null } | undefined;
  ionstream?: { [k: string]: any | null } | undefined;
  klusterai?: { [k: string]: any | null } | undefined;
  lambda?: { [k: string]: any | null } | undefined;
  lepton?: { [k: string]: any | null } | undefined;
  liquid?: { [k: string]: any | null } | undefined;
  lynn?: { [k: string]: any | null } | undefined;
  lynnPrivate?: { [k: string]: any | null } | undefined;
  mancer?: { [k: string]: any | null } | undefined;
  mancerOld?: { [k: string]: any | null } | undefined;
  mara?: { [k: string]: any | null } | undefined;
  meta?: { [k: string]: any | null } | undefined;
  minimax?: { [k: string]: any | null } | undefined;
  mistral?: { [k: string]: any | null } | undefined;
  modal?: { [k: string]: any | null } | undefined;
  modelrun?: { [k: string]: any | null } | undefined;
  modular?: { [k: string]: any | null } | undefined;
  moonshotai?: { [k: string]: any | null } | undefined;
  morph?: { [k: string]: any | null } | undefined;
  ncompass?: { [k: string]: any | null } | undefined;
  nebius?: { [k: string]: any | null } | undefined;
  nexAgi?: { [k: string]: any | null } | undefined;
  nextbit?: { [k: string]: any | null } | undefined;
  nineteen?: { [k: string]: any | null } | undefined;
  novita?: { [k: string]: any | null } | undefined;
  nvidia?: { [k: string]: any | null } | undefined;
  octoai?: { [k: string]: any | null } | undefined;
  openInference?: { [k: string]: any | null } | undefined;
  openai?: { [k: string]: any | null } | undefined;
  parasail?: { [k: string]: any | null } | undefined;
  perceptron?: { [k: string]: any | null } | undefined;
  perplexity?: { [k: string]: any | null } | undefined;
  phala?: { [k: string]: any | null } | undefined;
  poolside?: { [k: string]: any | null } | undefined;
  quiver?: { [k: string]: any | null } | undefined;
  recraft?: { [k: string]: any | null } | undefined;
  recursal?: { [k: string]: any | null } | undefined;
  reflection?: { [k: string]: any | null } | undefined;
  reka?: { [k: string]: any | null } | undefined;
  relace?: { [k: string]: any | null } | undefined;
  replicate?: { [k: string]: any | null } | undefined;
  sakana?: { [k: string]: any | null } | undefined;
  sambanova?: { [k: string]: any | null } | undefined;
  sambanovaCloaked?: { [k: string]: any | null } | undefined;
  seed?: { [k: string]: any | null } | undefined;
  sfCompute?: { [k: string]: any | null } | undefined;
  siliconflow?: { [k: string]: any | null } | undefined;
  sourceful?: { [k: string]: any | null } | undefined;
  stealth?: { [k: string]: any | null } | undefined;
  stepfun?: { [k: string]: any | null } | undefined;
  streamlake?: { [k: string]: any | null } | undefined;
  switchpoint?: { [k: string]: any | null } | undefined;
  targon?: { [k: string]: any | null } | undefined;
  tenstorrent?: { [k: string]: any | null } | undefined;
  together?: { [k: string]: any | null } | undefined;
  togetherLite?: { [k: string]: any | null } | undefined;
  ubicloud?: { [k: string]: any | null } | undefined;
  upstage?: { [k: string]: any | null } | undefined;
  venice?: { [k: string]: any | null } | undefined;
  wafer?: { [k: string]: any | null } | undefined;
  wandb?: { [k: string]: any | null } | undefined;
  xai?: { [k: string]: any | null } | undefined;
  xiaomi?: { [k: string]: any | null } | undefined;
  zAi?: { [k: string]: any | null } | undefined;
};

export type ImageGenerationProviderPreferencesOrder = ProviderName | string;

/**
 * The sorting strategy to use for this request, if "order" is not specified. When set, no load balancing is performed.
 */
export type ImageGenerationProviderPreferencesSort =
  | ProviderSort
  | ProviderSortConfig
  | any;

/**
 * Provider routing preferences and provider-specific passthrough configuration.
 */
export type ImageGenerationProviderPreferences = {
  /**
   * Whether to allow backup providers to serve requests
   *
   * @remarks
   * - true: (default) when the primary provider (or your custom providers in "order") is unavailable, use the next best provider.
   * - false: use only the primary/custom provider, and return the upstream error if it's unavailable.
   */
  allowFallbacks?: boolean | null | undefined;
  /**
   * List of provider slugs to ignore. If provided, this list is merged with your account-wide ignored provider settings for this request.
   */
  ignore?: Array<ProviderName | string> | null | undefined;
  /**
   * List of provider slugs to allow. If provided, this list is merged with your account-wide allowed provider settings for this request.
   */
  only?: Array<ProviderName | string> | null | undefined;
  options?: ImageGenerationProviderPreferencesOptions | undefined;
  /**
   * An ordered list of provider slugs. The router will attempt to use the first provider in the subset of this list that supports your requested model, and fall back to the next if it is unavailable. If no providers are available, the request will fail with an error message.
   */
  order?: Array<ProviderName | string> | null | undefined;
  /**
   * The sorting strategy to use for this request, if "order" is not specified. When set, no load balancing is performed.
   */
  sort?: ProviderSort | ProviderSortConfig | any | null | undefined;
};

/** @internal */
export type ImageGenerationProviderPreferencesIgnore$Outbound = string | string;

/** @internal */
export const ImageGenerationProviderPreferencesIgnore$outboundSchema: z.ZodType<
  ImageGenerationProviderPreferencesIgnore$Outbound,
  ImageGenerationProviderPreferencesIgnore
> = z.union([ProviderName$outboundSchema, z.string()]);

export function imageGenerationProviderPreferencesIgnoreToJSON(
  imageGenerationProviderPreferencesIgnore:
    ImageGenerationProviderPreferencesIgnore,
): string {
  return JSON.stringify(
    ImageGenerationProviderPreferencesIgnore$outboundSchema.parse(
      imageGenerationProviderPreferencesIgnore,
    ),
  );
}

/** @internal */
export type ImageGenerationProviderPreferencesOnly$Outbound = string | string;

/** @internal */
export const ImageGenerationProviderPreferencesOnly$outboundSchema: z.ZodType<
  ImageGenerationProviderPreferencesOnly$Outbound,
  ImageGenerationProviderPreferencesOnly
> = z.union([ProviderName$outboundSchema, z.string()]);

export function imageGenerationProviderPreferencesOnlyToJSON(
  imageGenerationProviderPreferencesOnly:
    ImageGenerationProviderPreferencesOnly,
): string {
  return JSON.stringify(
    ImageGenerationProviderPreferencesOnly$outboundSchema.parse(
      imageGenerationProviderPreferencesOnly,
    ),
  );
}

/** @internal */
export type ImageGenerationProviderPreferencesOptions$Outbound = {
  "01ai"?: { [k: string]: any | null } | undefined;
  ai21?: { [k: string]: any | null } | undefined;
  "aion-labs"?: { [k: string]: any | null } | undefined;
  akashml?: { [k: string]: any | null } | undefined;
  alibaba?: { [k: string]: any | null } | undefined;
  "amazon-bedrock"?: { [k: string]: any | null } | undefined;
  "amazon-nova"?: { [k: string]: any | null } | undefined;
  ambient?: { [k: string]: any | null } | undefined;
  anthropic?: { [k: string]: any | null } | undefined;
  anyscale?: { [k: string]: any | null } | undefined;
  "arcee-ai"?: { [k: string]: any | null } | undefined;
  "atlas-cloud"?: { [k: string]: any | null } | undefined;
  atoma?: { [k: string]: any | null } | undefined;
  avian?: { [k: string]: any | null } | undefined;
  azure?: { [k: string]: any | null } | undefined;
  baidu?: { [k: string]: any | null } | undefined;
  baseten?: { [k: string]: any | null } | undefined;
  "black-forest-labs"?: { [k: string]: any | null } | undefined;
  byteplus?: { [k: string]: any | null } | undefined;
  centml?: { [k: string]: any | null } | undefined;
  cerebras?: { [k: string]: any | null } | undefined;
  chutes?: { [k: string]: any | null } | undefined;
  cirrascale?: { [k: string]: any | null } | undefined;
  clarifai?: { [k: string]: any | null } | undefined;
  cloudflare?: { [k: string]: any | null } | undefined;
  cohere?: { [k: string]: any | null } | undefined;
  crofai?: { [k: string]: any | null } | undefined;
  crucible?: { [k: string]: any | null } | undefined;
  crusoe?: { [k: string]: any | null } | undefined;
  darkbloom?: { [k: string]: any | null } | undefined;
  decart?: { [k: string]: any | null } | undefined;
  deepgram?: { [k: string]: any | null } | undefined;
  deepinfra?: { [k: string]: any | null } | undefined;
  deepseek?: { [k: string]: any | null } | undefined;
  dekallm?: { [k: string]: any | null } | undefined;
  digitalocean?: { [k: string]: any | null } | undefined;
  enfer?: { [k: string]: any | null } | undefined;
  "fake-provider"?: { [k: string]: any | null } | undefined;
  featherless?: { [k: string]: any | null } | undefined;
  fireworks?: { [k: string]: any | null } | undefined;
  friendli?: { [k: string]: any | null } | undefined;
  gmicloud?: { [k: string]: any | null } | undefined;
  "google-ai-studio"?: { [k: string]: any | null } | undefined;
  "google-vertex"?: { [k: string]: any | null } | undefined;
  gopomelo?: { [k: string]: any | null } | undefined;
  groq?: { [k: string]: any | null } | undefined;
  heygen?: { [k: string]: any | null } | undefined;
  huggingface?: { [k: string]: any | null } | undefined;
  hyperbolic?: { [k: string]: any | null } | undefined;
  "hyperbolic-quantized"?: { [k: string]: any | null } | undefined;
  inception?: { [k: string]: any | null } | undefined;
  inceptron?: { [k: string]: any | null } | undefined;
  "inferact-vllm"?: { [k: string]: any | null } | undefined;
  "inference-net"?: { [k: string]: any | null } | undefined;
  infermatic?: { [k: string]: any | null } | undefined;
  inflection?: { [k: string]: any | null } | undefined;
  inocloud?: { [k: string]: any | null } | undefined;
  "io-net"?: { [k: string]: any | null } | undefined;
  ionstream?: { [k: string]: any | null } | undefined;
  klusterai?: { [k: string]: any | null } | undefined;
  lambda?: { [k: string]: any | null } | undefined;
  lepton?: { [k: string]: any | null } | undefined;
  liquid?: { [k: string]: any | null } | undefined;
  lynn?: { [k: string]: any | null } | undefined;
  "lynn-private"?: { [k: string]: any | null } | undefined;
  mancer?: { [k: string]: any | null } | undefined;
  "mancer-old"?: { [k: string]: any | null } | undefined;
  mara?: { [k: string]: any | null } | undefined;
  meta?: { [k: string]: any | null } | undefined;
  minimax?: { [k: string]: any | null } | undefined;
  mistral?: { [k: string]: any | null } | undefined;
  modal?: { [k: string]: any | null } | undefined;
  modelrun?: { [k: string]: any | null } | undefined;
  modular?: { [k: string]: any | null } | undefined;
  moonshotai?: { [k: string]: any | null } | undefined;
  morph?: { [k: string]: any | null } | undefined;
  ncompass?: { [k: string]: any | null } | undefined;
  nebius?: { [k: string]: any | null } | undefined;
  "nex-agi"?: { [k: string]: any | null } | undefined;
  nextbit?: { [k: string]: any | null } | undefined;
  nineteen?: { [k: string]: any | null } | undefined;
  novita?: { [k: string]: any | null } | undefined;
  nvidia?: { [k: string]: any | null } | undefined;
  octoai?: { [k: string]: any | null } | undefined;
  "open-inference"?: { [k: string]: any | null } | undefined;
  openai?: { [k: string]: any | null } | undefined;
  parasail?: { [k: string]: any | null } | undefined;
  perceptron?: { [k: string]: any | null } | undefined;
  perplexity?: { [k: string]: any | null } | undefined;
  phala?: { [k: string]: any | null } | undefined;
  poolside?: { [k: string]: any | null } | undefined;
  quiver?: { [k: string]: any | null } | undefined;
  recraft?: { [k: string]: any | null } | undefined;
  recursal?: { [k: string]: any | null } | undefined;
  reflection?: { [k: string]: any | null } | undefined;
  reka?: { [k: string]: any | null } | undefined;
  relace?: { [k: string]: any | null } | undefined;
  replicate?: { [k: string]: any | null } | undefined;
  sakana?: { [k: string]: any | null } | undefined;
  sambanova?: { [k: string]: any | null } | undefined;
  "sambanova-cloaked"?: { [k: string]: any | null } | undefined;
  seed?: { [k: string]: any | null } | undefined;
  "sf-compute"?: { [k: string]: any | null } | undefined;
  siliconflow?: { [k: string]: any | null } | undefined;
  sourceful?: { [k: string]: any | null } | undefined;
  stealth?: { [k: string]: any | null } | undefined;
  stepfun?: { [k: string]: any | null } | undefined;
  streamlake?: { [k: string]: any | null } | undefined;
  switchpoint?: { [k: string]: any | null } | undefined;
  targon?: { [k: string]: any | null } | undefined;
  tenstorrent?: { [k: string]: any | null } | undefined;
  together?: { [k: string]: any | null } | undefined;
  "together-lite"?: { [k: string]: any | null } | undefined;
  ubicloud?: { [k: string]: any | null } | undefined;
  upstage?: { [k: string]: any | null } | undefined;
  venice?: { [k: string]: any | null } | undefined;
  wafer?: { [k: string]: any | null } | undefined;
  wandb?: { [k: string]: any | null } | undefined;
  xai?: { [k: string]: any | null } | undefined;
  xiaomi?: { [k: string]: any | null } | undefined;
  "z-ai"?: { [k: string]: any | null } | undefined;
};

/** @internal */
export const ImageGenerationProviderPreferencesOptions$outboundSchema:
  z.ZodType<
    ImageGenerationProviderPreferencesOptions$Outbound,
    ImageGenerationProviderPreferencesOptions
  > = z.object({
    oneai: z.record(z.string(), z.nullable(z.any())).optional(),
    ai21: z.record(z.string(), z.nullable(z.any())).optional(),
    aionLabs: z.record(z.string(), z.nullable(z.any())).optional(),
    akashml: z.record(z.string(), z.nullable(z.any())).optional(),
    alibaba: z.record(z.string(), z.nullable(z.any())).optional(),
    amazonBedrock: z.record(z.string(), z.nullable(z.any())).optional(),
    amazonNova: z.record(z.string(), z.nullable(z.any())).optional(),
    ambient: z.record(z.string(), z.nullable(z.any())).optional(),
    anthropic: z.record(z.string(), z.nullable(z.any())).optional(),
    anyscale: z.record(z.string(), z.nullable(z.any())).optional(),
    arceeAi: z.record(z.string(), z.nullable(z.any())).optional(),
    atlasCloud: z.record(z.string(), z.nullable(z.any())).optional(),
    atoma: z.record(z.string(), z.nullable(z.any())).optional(),
    avian: z.record(z.string(), z.nullable(z.any())).optional(),
    azure: z.record(z.string(), z.nullable(z.any())).optional(),
    baidu: z.record(z.string(), z.nullable(z.any())).optional(),
    baseten: z.record(z.string(), z.nullable(z.any())).optional(),
    blackForestLabs: z.record(z.string(), z.nullable(z.any())).optional(),
    byteplus: z.record(z.string(), z.nullable(z.any())).optional(),
    centml: z.record(z.string(), z.nullable(z.any())).optional(),
    cerebras: z.record(z.string(), z.nullable(z.any())).optional(),
    chutes: z.record(z.string(), z.nullable(z.any())).optional(),
    cirrascale: z.record(z.string(), z.nullable(z.any())).optional(),
    clarifai: z.record(z.string(), z.nullable(z.any())).optional(),
    cloudflare: z.record(z.string(), z.nullable(z.any())).optional(),
    cohere: z.record(z.string(), z.nullable(z.any())).optional(),
    crofai: z.record(z.string(), z.nullable(z.any())).optional(),
    crucible: z.record(z.string(), z.nullable(z.any())).optional(),
    crusoe: z.record(z.string(), z.nullable(z.any())).optional(),
    darkbloom: z.record(z.string(), z.nullable(z.any())).optional(),
    decart: z.record(z.string(), z.nullable(z.any())).optional(),
    deepgram: z.record(z.string(), z.nullable(z.any())).optional(),
    deepinfra: z.record(z.string(), z.nullable(z.any())).optional(),
    deepseek: z.record(z.string(), z.nullable(z.any())).optional(),
    dekallm: z.record(z.string(), z.nullable(z.any())).optional(),
    digitalocean: z.record(z.string(), z.nullable(z.any())).optional(),
    enfer: z.record(z.string(), z.nullable(z.any())).optional(),
    fakeProvider: z.record(z.string(), z.nullable(z.any())).optional(),
    featherless: z.record(z.string(), z.nullable(z.any())).optional(),
    fireworks: z.record(z.string(), z.nullable(z.any())).optional(),
    friendli: z.record(z.string(), z.nullable(z.any())).optional(),
    gmicloud: z.record(z.string(), z.nullable(z.any())).optional(),
    googleAiStudio: z.record(z.string(), z.nullable(z.any())).optional(),
    googleVertex: z.record(z.string(), z.nullable(z.any())).optional(),
    gopomelo: z.record(z.string(), z.nullable(z.any())).optional(),
    groq: z.record(z.string(), z.nullable(z.any())).optional(),
    heygen: z.record(z.string(), z.nullable(z.any())).optional(),
    huggingface: z.record(z.string(), z.nullable(z.any())).optional(),
    hyperbolic: z.record(z.string(), z.nullable(z.any())).optional(),
    hyperbolicQuantized: z.record(z.string(), z.nullable(z.any())).optional(),
    inception: z.record(z.string(), z.nullable(z.any())).optional(),
    inceptron: z.record(z.string(), z.nullable(z.any())).optional(),
    inferactVllm: z.record(z.string(), z.nullable(z.any())).optional(),
    inferenceNet: z.record(z.string(), z.nullable(z.any())).optional(),
    infermatic: z.record(z.string(), z.nullable(z.any())).optional(),
    inflection: z.record(z.string(), z.nullable(z.any())).optional(),
    inocloud: z.record(z.string(), z.nullable(z.any())).optional(),
    ioNet: z.record(z.string(), z.nullable(z.any())).optional(),
    ionstream: z.record(z.string(), z.nullable(z.any())).optional(),
    klusterai: z.record(z.string(), z.nullable(z.any())).optional(),
    lambda: z.record(z.string(), z.nullable(z.any())).optional(),
    lepton: z.record(z.string(), z.nullable(z.any())).optional(),
    liquid: z.record(z.string(), z.nullable(z.any())).optional(),
    lynn: z.record(z.string(), z.nullable(z.any())).optional(),
    lynnPrivate: z.record(z.string(), z.nullable(z.any())).optional(),
    mancer: z.record(z.string(), z.nullable(z.any())).optional(),
    mancerOld: z.record(z.string(), z.nullable(z.any())).optional(),
    mara: z.record(z.string(), z.nullable(z.any())).optional(),
    meta: z.record(z.string(), z.nullable(z.any())).optional(),
    minimax: z.record(z.string(), z.nullable(z.any())).optional(),
    mistral: z.record(z.string(), z.nullable(z.any())).optional(),
    modal: z.record(z.string(), z.nullable(z.any())).optional(),
    modelrun: z.record(z.string(), z.nullable(z.any())).optional(),
    modular: z.record(z.string(), z.nullable(z.any())).optional(),
    moonshotai: z.record(z.string(), z.nullable(z.any())).optional(),
    morph: z.record(z.string(), z.nullable(z.any())).optional(),
    ncompass: z.record(z.string(), z.nullable(z.any())).optional(),
    nebius: z.record(z.string(), z.nullable(z.any())).optional(),
    nexAgi: z.record(z.string(), z.nullable(z.any())).optional(),
    nextbit: z.record(z.string(), z.nullable(z.any())).optional(),
    nineteen: z.record(z.string(), z.nullable(z.any())).optional(),
    novita: z.record(z.string(), z.nullable(z.any())).optional(),
    nvidia: z.record(z.string(), z.nullable(z.any())).optional(),
    octoai: z.record(z.string(), z.nullable(z.any())).optional(),
    openInference: z.record(z.string(), z.nullable(z.any())).optional(),
    openai: z.record(z.string(), z.nullable(z.any())).optional(),
    parasail: z.record(z.string(), z.nullable(z.any())).optional(),
    perceptron: z.record(z.string(), z.nullable(z.any())).optional(),
    perplexity: z.record(z.string(), z.nullable(z.any())).optional(),
    phala: z.record(z.string(), z.nullable(z.any())).optional(),
    poolside: z.record(z.string(), z.nullable(z.any())).optional(),
    quiver: z.record(z.string(), z.nullable(z.any())).optional(),
    recraft: z.record(z.string(), z.nullable(z.any())).optional(),
    recursal: z.record(z.string(), z.nullable(z.any())).optional(),
    reflection: z.record(z.string(), z.nullable(z.any())).optional(),
    reka: z.record(z.string(), z.nullable(z.any())).optional(),
    relace: z.record(z.string(), z.nullable(z.any())).optional(),
    replicate: z.record(z.string(), z.nullable(z.any())).optional(),
    sakana: z.record(z.string(), z.nullable(z.any())).optional(),
    sambanova: z.record(z.string(), z.nullable(z.any())).optional(),
    sambanovaCloaked: z.record(z.string(), z.nullable(z.any())).optional(),
    seed: z.record(z.string(), z.nullable(z.any())).optional(),
    sfCompute: z.record(z.string(), z.nullable(z.any())).optional(),
    siliconflow: z.record(z.string(), z.nullable(z.any())).optional(),
    sourceful: z.record(z.string(), z.nullable(z.any())).optional(),
    stealth: z.record(z.string(), z.nullable(z.any())).optional(),
    stepfun: z.record(z.string(), z.nullable(z.any())).optional(),
    streamlake: z.record(z.string(), z.nullable(z.any())).optional(),
    switchpoint: z.record(z.string(), z.nullable(z.any())).optional(),
    targon: z.record(z.string(), z.nullable(z.any())).optional(),
    tenstorrent: z.record(z.string(), z.nullable(z.any())).optional(),
    together: z.record(z.string(), z.nullable(z.any())).optional(),
    togetherLite: z.record(z.string(), z.nullable(z.any())).optional(),
    ubicloud: z.record(z.string(), z.nullable(z.any())).optional(),
    upstage: z.record(z.string(), z.nullable(z.any())).optional(),
    venice: z.record(z.string(), z.nullable(z.any())).optional(),
    wafer: z.record(z.string(), z.nullable(z.any())).optional(),
    wandb: z.record(z.string(), z.nullable(z.any())).optional(),
    xai: z.record(z.string(), z.nullable(z.any())).optional(),
    xiaomi: z.record(z.string(), z.nullable(z.any())).optional(),
    zAi: z.record(z.string(), z.nullable(z.any())).optional(),
  }).transform((v) => {
    return remap$(v, {
      oneai: "01ai",
      aionLabs: "aion-labs",
      amazonBedrock: "amazon-bedrock",
      amazonNova: "amazon-nova",
      arceeAi: "arcee-ai",
      atlasCloud: "atlas-cloud",
      blackForestLabs: "black-forest-labs",
      fakeProvider: "fake-provider",
      googleAiStudio: "google-ai-studio",
      googleVertex: "google-vertex",
      hyperbolicQuantized: "hyperbolic-quantized",
      inferactVllm: "inferact-vllm",
      inferenceNet: "inference-net",
      ioNet: "io-net",
      lynnPrivate: "lynn-private",
      mancerOld: "mancer-old",
      nexAgi: "nex-agi",
      openInference: "open-inference",
      sambanovaCloaked: "sambanova-cloaked",
      sfCompute: "sf-compute",
      togetherLite: "together-lite",
      zAi: "z-ai",
    });
  });

export function imageGenerationProviderPreferencesOptionsToJSON(
  imageGenerationProviderPreferencesOptions:
    ImageGenerationProviderPreferencesOptions,
): string {
  return JSON.stringify(
    ImageGenerationProviderPreferencesOptions$outboundSchema.parse(
      imageGenerationProviderPreferencesOptions,
    ),
  );
}

/** @internal */
export type ImageGenerationProviderPreferencesOrder$Outbound = string | string;

/** @internal */
export const ImageGenerationProviderPreferencesOrder$outboundSchema: z.ZodType<
  ImageGenerationProviderPreferencesOrder$Outbound,
  ImageGenerationProviderPreferencesOrder
> = z.union([ProviderName$outboundSchema, z.string()]);

export function imageGenerationProviderPreferencesOrderToJSON(
  imageGenerationProviderPreferencesOrder:
    ImageGenerationProviderPreferencesOrder,
): string {
  return JSON.stringify(
    ImageGenerationProviderPreferencesOrder$outboundSchema.parse(
      imageGenerationProviderPreferencesOrder,
    ),
  );
}

/** @internal */
export type ImageGenerationProviderPreferencesSort$Outbound =
  | string
  | ProviderSortConfig$Outbound
  | any;

/** @internal */
export const ImageGenerationProviderPreferencesSort$outboundSchema: z.ZodType<
  ImageGenerationProviderPreferencesSort$Outbound,
  ImageGenerationProviderPreferencesSort
> = z.union([
  ProviderSort$outboundSchema,
  ProviderSortConfig$outboundSchema,
  z.any(),
]);

export function imageGenerationProviderPreferencesSortToJSON(
  imageGenerationProviderPreferencesSort:
    ImageGenerationProviderPreferencesSort,
): string {
  return JSON.stringify(
    ImageGenerationProviderPreferencesSort$outboundSchema.parse(
      imageGenerationProviderPreferencesSort,
    ),
  );
}

/** @internal */
export type ImageGenerationProviderPreferences$Outbound = {
  allow_fallbacks?: boolean | null | undefined;
  ignore?: Array<string | string> | null | undefined;
  only?: Array<string | string> | null | undefined;
  options?: ImageGenerationProviderPreferencesOptions$Outbound | undefined;
  order?: Array<string | string> | null | undefined;
  sort?: string | ProviderSortConfig$Outbound | any | null | undefined;
};

/** @internal */
export const ImageGenerationProviderPreferences$outboundSchema: z.ZodType<
  ImageGenerationProviderPreferences$Outbound,
  ImageGenerationProviderPreferences
> = z.object({
  allowFallbacks: z.nullable(z.boolean()).optional(),
  ignore: z.nullable(
    z.array(z.union([ProviderName$outboundSchema, z.string()])),
  ).optional(),
  only: z.nullable(z.array(z.union([ProviderName$outboundSchema, z.string()])))
    .optional(),
  options: z.lazy(() =>
    ImageGenerationProviderPreferencesOptions$outboundSchema
  ).optional(),
  order: z.nullable(z.array(z.union([ProviderName$outboundSchema, z.string()])))
    .optional(),
  sort: z.nullable(
    z.union([
      ProviderSort$outboundSchema,
      ProviderSortConfig$outboundSchema,
      z.any(),
    ]),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    allowFallbacks: "allow_fallbacks",
  });
});

export function imageGenerationProviderPreferencesToJSON(
  imageGenerationProviderPreferences: ImageGenerationProviderPreferences,
): string {
  return JSON.stringify(
    ImageGenerationProviderPreferences$outboundSchema.parse(
      imageGenerationProviderPreferences,
    ),
  );
}
