/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ea1ffc0d2470
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import {
  ContentPartImage,
  ContentPartImage$Outbound,
  ContentPartImage$outboundSchema,
} from "./contentpartimage.js";

/**
 * Normalized aspect ratio of the generated image. Providers clamp to their supported subset.
 */
export const ImageGenerationRequestAspectRatio = {
  Eleven: "1:1",
  Twelve: "1:2",
  Fourteen: "1:4",
  Eighteen: "1:8",
  TwentyOne: "2:1",
  TwentyThree: "2:3",
  ThirtyTwo: "3:2",
  ThirtyFour: "3:4",
  FortyOne: "4:1",
  FortyThree: "4:3",
  FortyFive: "4:5",
  FiftyFour: "5:4",
  EightyOne: "8:1",
  NineHundredAndSixteen: "9:16",
  OneHundredAndSixtyNine: "16:9",
  NineHundredAndNineteenDot5: "9:19.5",
  NineteenDot59: "19.5:9",
  NineHundredAndTwenty: "9:20",
  TwoHundredAndNine: "20:9",
  NineHundredAndTwentyOne: "9:21",
  TwoHundredAndNineteen: "21:9",
  Auto: "auto",
} as const;
/**
 * Normalized aspect ratio of the generated image. Providers clamp to their supported subset.
 */
export type ImageGenerationRequestAspectRatio = OpenEnum<
  typeof ImageGenerationRequestAspectRatio
>;

/**
 * Background treatment. `transparent` requires an output_format that supports alpha (png or webp).
 */
export const ImageGenerationRequestBackground = {
  Auto: "auto",
  Transparent: "transparent",
  Opaque: "opaque",
} as const;
/**
 * Background treatment. `transparent` requires an output_format that supports alpha (png or webp).
 */
export type ImageGenerationRequestBackground = OpenEnum<
  typeof ImageGenerationRequestBackground
>;

/**
 * Encoding of the returned image bytes.
 */
export const ImageGenerationRequestOutputFormat = {
  Png: "png",
  Jpeg: "jpeg",
  Webp: "webp",
} as const;
/**
 * Encoding of the returned image bytes.
 */
export type ImageGenerationRequestOutputFormat = OpenEnum<
  typeof ImageGenerationRequestOutputFormat
>;

/**
 * Provider-specific options keyed by provider slug. Only options for the matched provider are forwarded; the rest are ignored. Unrecognized keys are silently dropped.
 */
export type ImageGenerationRequestOptions = {
  oneai?: { [k: string]: any | null } | undefined;
  ai21?: { [k: string]: any | null } | undefined;
  aionLabs?: { [k: string]: any | null } | undefined;
  akashml?: { [k: string]: any | null } | undefined;
  alibaba?: { [k: string]: any | null } | undefined;
  amazonBedrock?: { [k: string]: any | null } | undefined;
  amazonNova?: { [k: string]: any | null } | undefined;
  ambient?: { [k: string]: any | null } | undefined;
  anthropic?: { [k: string]: any | null } | undefined;
  anyscale?: { [k: string]: any | null } | undefined;
  arceeAi?: { [k: string]: any | null } | undefined;
  atlasCloud?: { [k: string]: any | null } | undefined;
  atoma?: { [k: string]: any | null } | undefined;
  avian?: { [k: string]: any | null } | undefined;
  azure?: { [k: string]: any | null } | undefined;
  baidu?: { [k: string]: any | null } | undefined;
  baseten?: { [k: string]: any | null } | undefined;
  blackForestLabs?: { [k: string]: any | null } | undefined;
  byteplus?: { [k: string]: any | null } | undefined;
  centml?: { [k: string]: any | null } | undefined;
  cerebras?: { [k: string]: any | null } | undefined;
  chutes?: { [k: string]: any | null } | undefined;
  cirrascale?: { [k: string]: any | null } | undefined;
  clarifai?: { [k: string]: any | null } | undefined;
  cloudflare?: { [k: string]: any | null } | undefined;
  cohere?: { [k: string]: any | null } | undefined;
  crofai?: { [k: string]: any | null } | undefined;
  crucible?: { [k: string]: any | null } | undefined;
  crusoe?: { [k: string]: any | null } | undefined;
  darkbloom?: { [k: string]: any | null } | undefined;
  decart?: { [k: string]: any | null } | undefined;
  deepgram?: { [k: string]: any | null } | undefined;
  deepinfra?: { [k: string]: any | null } | undefined;
  deepseek?: { [k: string]: any | null } | undefined;
  dekallm?: { [k: string]: any | null } | undefined;
  digitalocean?: { [k: string]: any | null } | undefined;
  enfer?: { [k: string]: any | null } | undefined;
  fakeProvider?: { [k: string]: any | null } | undefined;
  featherless?: { [k: string]: any | null } | undefined;
  fireworks?: { [k: string]: any | null } | undefined;
  friendli?: { [k: string]: any | null } | undefined;
  gmicloud?: { [k: string]: any | null } | undefined;
  googleAiStudio?: { [k: string]: any | null } | undefined;
  googleVertex?: { [k: string]: any | null } | undefined;
  gopomelo?: { [k: string]: any | null } | undefined;
  groq?: { [k: string]: any | null } | undefined;
  heygen?: { [k: string]: any | null } | undefined;
  huggingface?: { [k: string]: any | null } | undefined;
  hyperbolic?: { [k: string]: any | null } | undefined;
  hyperbolicQuantized?: { [k: string]: any | null } | undefined;
  inception?: { [k: string]: any | null } | undefined;
  inceptron?: { [k: string]: any | null } | undefined;
  inferactVllm?: { [k: string]: any | null } | undefined;
  inferenceNet?: { [k: string]: any | null } | undefined;
  infermatic?: { [k: string]: any | null } | undefined;
  inflection?: { [k: string]: any | null } | undefined;
  inocloud?: { [k: string]: any | null } | undefined;
  ioNet?: { [k: string]: any | null } | undefined;
  ionstream?: { [k: string]: any | null } | undefined;
  klusterai?: { [k: string]: any | null } | undefined;
  lambda?: { [k: string]: any | null } | undefined;
  lepton?: { [k: string]: any | null } | undefined;
  liquid?: { [k: string]: any | null } | undefined;
  lynn?: { [k: string]: any | null } | undefined;
  lynnPrivate?: { [k: string]: any | null } | undefined;
  mancer?: { [k: string]: any | null } | undefined;
  mancerOld?: { [k: string]: any | null } | undefined;
  mara?: { [k: string]: any | null } | undefined;
  meta?: { [k: string]: any | null } | undefined;
  minimax?: { [k: string]: any | null } | undefined;
  mistral?: { [k: string]: any | null } | undefined;
  modal?: { [k: string]: any | null } | undefined;
  modelrun?: { [k: string]: any | null } | undefined;
  modular?: { [k: string]: any | null } | undefined;
  moonshotai?: { [k: string]: any | null } | undefined;
  morph?: { [k: string]: any | null } | undefined;
  ncompass?: { [k: string]: any | null } | undefined;
  nebius?: { [k: string]: any | null } | undefined;
  nexAgi?: { [k: string]: any | null } | undefined;
  nextbit?: { [k: string]: any | null } | undefined;
  nineteen?: { [k: string]: any | null } | undefined;
  novita?: { [k: string]: any | null } | undefined;
  nvidia?: { [k: string]: any | null } | undefined;
  octoai?: { [k: string]: any | null } | undefined;
  openInference?: { [k: string]: any | null } | undefined;
  openai?: { [k: string]: any | null } | undefined;
  parasail?: { [k: string]: any | null } | undefined;
  perceptron?: { [k: string]: any | null } | undefined;
  perplexity?: { [k: string]: any | null } | undefined;
  phala?: { [k: string]: any | null } | undefined;
  poolside?: { [k: string]: any | null } | undefined;
  recraft?: { [k: string]: any | null } | undefined;
  recursal?: { [k: string]: any | null } | undefined;
  reflection?: { [k: string]: any | null } | undefined;
  reka?: { [k: string]: any | null } | undefined;
  relace?: { [k: string]: any | null } | undefined;
  replicate?: { [k: string]: any | null } | undefined;
  sakanaAi?: { [k: string]: any | null } | undefined;
  sambanova?: { [k: string]: any | null } | undefined;
  sambanovaCloaked?: { [k: string]: any | null } | undefined;
  seed?: { [k: string]: any | null } | undefined;
  sfCompute?: { [k: string]: any | null } | undefined;
  siliconflow?: { [k: string]: any | null } | undefined;
  sourceful?: { [k: string]: any | null } | undefined;
  stealth?: { [k: string]: any | null } | undefined;
  stepfun?: { [k: string]: any | null } | undefined;
  streamlake?: { [k: string]: any | null } | undefined;
  switchpoint?: { [k: string]: any | null } | undefined;
  targon?: { [k: string]: any | null } | undefined;
  tenstorrent?: { [k: string]: any | null } | undefined;
  together?: { [k: string]: any | null } | undefined;
  togetherLite?: { [k: string]: any | null } | undefined;
  ubicloud?: { [k: string]: any | null } | undefined;
  upstage?: { [k: string]: any | null } | undefined;
  venice?: { [k: string]: any | null } | undefined;
  wafer?: { [k: string]: any | null } | undefined;
  wandb?: { [k: string]: any | null } | undefined;
  xai?: { [k: string]: any | null } | undefined;
  xiaomi?: { [k: string]: any | null } | undefined;
  zAi?: { [k: string]: any | null } | undefined;
};

/**
 * Provider-specific passthrough configuration
 */
export type ImageGenerationRequestProvider = {
  options?: ImageGenerationRequestOptions | undefined;
};

/**
 * Rendering quality. Providers without a quality knob ignore this.
 */
export const ImageGenerationRequestQuality = {
  Auto: "auto",
  Low: "low",
  Medium: "medium",
  High: "high",
} as const;
/**
 * Rendering quality. Providers without a quality knob ignore this.
 */
export type ImageGenerationRequestQuality = OpenEnum<
  typeof ImageGenerationRequestQuality
>;

/**
 * Normalized resolution tier of the generated image. Concrete pixel dimensions are derived per-provider.
 */
export const ImageGenerationRequestResolution = {
  FiveHundredAndTwelve: "512",
  OneK: "1K",
  TwoK: "2K",
  FourK: "4K",
} as const;
/**
 * Normalized resolution tier of the generated image. Concrete pixel dimensions are derived per-provider.
 */
export type ImageGenerationRequestResolution = OpenEnum<
  typeof ImageGenerationRequestResolution
>;

/**
 * Image generation request input
 */
export type ImageGenerationRequest = {
  /**
   * Normalized aspect ratio of the generated image. Providers clamp to their supported subset.
   */
  aspectRatio?: ImageGenerationRequestAspectRatio | undefined;
  /**
   * Background treatment. `transparent` requires an output_format that supports alpha (png or webp).
   */
  background?: ImageGenerationRequestBackground | undefined;
  /**
   * Reference images to guide image-to-image generation, as base64 data URLs or HTTP(S) URLs.
   */
  inputReferences?: Array<ContentPartImage> | undefined;
  /**
   * The image generation model to use
   */
  model: string;
  /**
   * Number of images to generate (1-10). Providers that only support single-image generation reject n > 1.
   */
  n?: number | undefined;
  /**
   * Compression level (0-100) for webp/jpeg output. Ignored for png and by providers without a compression knob.
   */
  outputCompression?: number | undefined;
  /**
   * Encoding of the returned image bytes.
   */
  outputFormat?: ImageGenerationRequestOutputFormat | undefined;
  /**
   * Text description of the desired image
   */
  prompt: string;
  /**
   * Provider-specific passthrough configuration
   */
  provider?: ImageGenerationRequestProvider | undefined;
  /**
   * Rendering quality. Providers without a quality knob ignore this.
   */
  quality?: ImageGenerationRequestQuality | undefined;
  /**
   * Normalized resolution tier of the generated image. Concrete pixel dimensions are derived per-provider.
   */
  resolution?: ImageGenerationRequestResolution | undefined;
  /**
   * If specified, the generation will sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed for all providers.
   */
  seed?: number | undefined;
  /**
   * Optional. A convenience shorthand for output dimensions — pass a tier ("2K", "4K") or explicit pixels ("2048x2048") and we normalize it to the right dimensions for the chosen provider. Interchangeable with resolution + aspect_ratio; use those directly for enumerated, per-model discoverable values. Conflicting size + resolution/aspect_ratio is rejected.
   */
  size?: string | undefined;
  /**
   * If true, partial images are streamed as SSE events as they become available. Only supported by providers with native streaming (currently OpenAI). Non-streaming providers ignore this flag and return a buffered response.
   */
  stream?: boolean | undefined;
};

/** @internal */
export const ImageGenerationRequestAspectRatio$outboundSchema: z.ZodType<
  string,
  ImageGenerationRequestAspectRatio
> = openEnums.outboundSchema(ImageGenerationRequestAspectRatio);

/** @internal */
export const ImageGenerationRequestBackground$outboundSchema: z.ZodType<
  string,
  ImageGenerationRequestBackground
> = openEnums.outboundSchema(ImageGenerationRequestBackground);

/** @internal */
export const ImageGenerationRequestOutputFormat$outboundSchema: z.ZodType<
  string,
  ImageGenerationRequestOutputFormat
> = openEnums.outboundSchema(ImageGenerationRequestOutputFormat);

/** @internal */
export type ImageGenerationRequestOptions$Outbound = {
  "01ai"?: { [k: string]: any | null } | undefined;
  ai21?: { [k: string]: any | null } | undefined;
  "aion-labs"?: { [k: string]: any | null } | undefined;
  akashml?: { [k: string]: any | null } | undefined;
  alibaba?: { [k: string]: any | null } | undefined;
  "amazon-bedrock"?: { [k: string]: any | null } | undefined;
  "amazon-nova"?: { [k: string]: any | null } | undefined;
  ambient?: { [k: string]: any | null } | undefined;
  anthropic?: { [k: string]: any | null } | undefined;
  anyscale?: { [k: string]: any | null } | undefined;
  "arcee-ai"?: { [k: string]: any | null } | undefined;
  "atlas-cloud"?: { [k: string]: any | null } | undefined;
  atoma?: { [k: string]: any | null } | undefined;
  avian?: { [k: string]: any | null } | undefined;
  azure?: { [k: string]: any | null } | undefined;
  baidu?: { [k: string]: any | null } | undefined;
  baseten?: { [k: string]: any | null } | undefined;
  "black-forest-labs"?: { [k: string]: any | null } | undefined;
  byteplus?: { [k: string]: any | null } | undefined;
  centml?: { [k: string]: any | null } | undefined;
  cerebras?: { [k: string]: any | null } | undefined;
  chutes?: { [k: string]: any | null } | undefined;
  cirrascale?: { [k: string]: any | null } | undefined;
  clarifai?: { [k: string]: any | null } | undefined;
  cloudflare?: { [k: string]: any | null } | undefined;
  cohere?: { [k: string]: any | null } | undefined;
  crofai?: { [k: string]: any | null } | undefined;
  crucible?: { [k: string]: any | null } | undefined;
  crusoe?: { [k: string]: any | null } | undefined;
  darkbloom?: { [k: string]: any | null } | undefined;
  decart?: { [k: string]: any | null } | undefined;
  deepgram?: { [k: string]: any | null } | undefined;
  deepinfra?: { [k: string]: any | null } | undefined;
  deepseek?: { [k: string]: any | null } | undefined;
  dekallm?: { [k: string]: any | null } | undefined;
  digitalocean?: { [k: string]: any | null } | undefined;
  enfer?: { [k: string]: any | null } | undefined;
  "fake-provider"?: { [k: string]: any | null } | undefined;
  featherless?: { [k: string]: any | null } | undefined;
  fireworks?: { [k: string]: any | null } | undefined;
  friendli?: { [k: string]: any | null } | undefined;
  gmicloud?: { [k: string]: any | null } | undefined;
  "google-ai-studio"?: { [k: string]: any | null } | undefined;
  "google-vertex"?: { [k: string]: any | null } | undefined;
  gopomelo?: { [k: string]: any | null } | undefined;
  groq?: { [k: string]: any | null } | undefined;
  heygen?: { [k: string]: any | null } | undefined;
  huggingface?: { [k: string]: any | null } | undefined;
  hyperbolic?: { [k: string]: any | null } | undefined;
  "hyperbolic-quantized"?: { [k: string]: any | null } | undefined;
  inception?: { [k: string]: any | null } | undefined;
  inceptron?: { [k: string]: any | null } | undefined;
  "inferact-vllm"?: { [k: string]: any | null } | undefined;
  "inference-net"?: { [k: string]: any | null } | undefined;
  infermatic?: { [k: string]: any | null } | undefined;
  inflection?: { [k: string]: any | null } | undefined;
  inocloud?: { [k: string]: any | null } | undefined;
  "io-net"?: { [k: string]: any | null } | undefined;
  ionstream?: { [k: string]: any | null } | undefined;
  klusterai?: { [k: string]: any | null } | undefined;
  lambda?: { [k: string]: any | null } | undefined;
  lepton?: { [k: string]: any | null } | undefined;
  liquid?: { [k: string]: any | null } | undefined;
  lynn?: { [k: string]: any | null } | undefined;
  "lynn-private"?: { [k: string]: any | null } | undefined;
  mancer?: { [k: string]: any | null } | undefined;
  "mancer-old"?: { [k: string]: any | null } | undefined;
  mara?: { [k: string]: any | null } | undefined;
  meta?: { [k: string]: any | null } | undefined;
  minimax?: { [k: string]: any | null } | undefined;
  mistral?: { [k: string]: any | null } | undefined;
  modal?: { [k: string]: any | null } | undefined;
  modelrun?: { [k: string]: any | null } | undefined;
  modular?: { [k: string]: any | null } | undefined;
  moonshotai?: { [k: string]: any | null } | undefined;
  morph?: { [k: string]: any | null } | undefined;
  ncompass?: { [k: string]: any | null } | undefined;
  nebius?: { [k: string]: any | null } | undefined;
  "nex-agi"?: { [k: string]: any | null } | undefined;
  nextbit?: { [k: string]: any | null } | undefined;
  nineteen?: { [k: string]: any | null } | undefined;
  novita?: { [k: string]: any | null } | undefined;
  nvidia?: { [k: string]: any | null } | undefined;
  octoai?: { [k: string]: any | null } | undefined;
  "open-inference"?: { [k: string]: any | null } | undefined;
  openai?: { [k: string]: any | null } | undefined;
  parasail?: { [k: string]: any | null } | undefined;
  perceptron?: { [k: string]: any | null } | undefined;
  perplexity?: { [k: string]: any | null } | undefined;
  phala?: { [k: string]: any | null } | undefined;
  poolside?: { [k: string]: any | null } | undefined;
  recraft?: { [k: string]: any | null } | undefined;
  recursal?: { [k: string]: any | null } | undefined;
  reflection?: { [k: string]: any | null } | undefined;
  reka?: { [k: string]: any | null } | undefined;
  relace?: { [k: string]: any | null } | undefined;
  replicate?: { [k: string]: any | null } | undefined;
  "sakana-ai"?: { [k: string]: any | null } | undefined;
  sambanova?: { [k: string]: any | null } | undefined;
  "sambanova-cloaked"?: { [k: string]: any | null } | undefined;
  seed?: { [k: string]: any | null } | undefined;
  "sf-compute"?: { [k: string]: any | null } | undefined;
  siliconflow?: { [k: string]: any | null } | undefined;
  sourceful?: { [k: string]: any | null } | undefined;
  stealth?: { [k: string]: any | null } | undefined;
  stepfun?: { [k: string]: any | null } | undefined;
  streamlake?: { [k: string]: any | null } | undefined;
  switchpoint?: { [k: string]: any | null } | undefined;
  targon?: { [k: string]: any | null } | undefined;
  tenstorrent?: { [k: string]: any | null } | undefined;
  together?: { [k: string]: any | null } | undefined;
  "together-lite"?: { [k: string]: any | null } | undefined;
  ubicloud?: { [k: string]: any | null } | undefined;
  upstage?: { [k: string]: any | null } | undefined;
  venice?: { [k: string]: any | null } | undefined;
  wafer?: { [k: string]: any | null } | undefined;
  wandb?: { [k: string]: any | null } | undefined;
  xai?: { [k: string]: any | null } | undefined;
  xiaomi?: { [k: string]: any | null } | undefined;
  "z-ai"?: { [k: string]: any | null } | undefined;
};

/** @internal */
export const ImageGenerationRequestOptions$outboundSchema: z.ZodType<
  ImageGenerationRequestOptions$Outbound,
  ImageGenerationRequestOptions
> = z.object({
  oneai: z.record(z.string(), z.nullable(z.any())).optional(),
  ai21: z.record(z.string(), z.nullable(z.any())).optional(),
  aionLabs: z.record(z.string(), z.nullable(z.any())).optional(),
  akashml: z.record(z.string(), z.nullable(z.any())).optional(),
  alibaba: z.record(z.string(), z.nullable(z.any())).optional(),
  amazonBedrock: z.record(z.string(), z.nullable(z.any())).optional(),
  amazonNova: z.record(z.string(), z.nullable(z.any())).optional(),
  ambient: z.record(z.string(), z.nullable(z.any())).optional(),
  anthropic: z.record(z.string(), z.nullable(z.any())).optional(),
  anyscale: z.record(z.string(), z.nullable(z.any())).optional(),
  arceeAi: z.record(z.string(), z.nullable(z.any())).optional(),
  atlasCloud: z.record(z.string(), z.nullable(z.any())).optional(),
  atoma: z.record(z.string(), z.nullable(z.any())).optional(),
  avian: z.record(z.string(), z.nullable(z.any())).optional(),
  azure: z.record(z.string(), z.nullable(z.any())).optional(),
  baidu: z.record(z.string(), z.nullable(z.any())).optional(),
  baseten: z.record(z.string(), z.nullable(z.any())).optional(),
  blackForestLabs: z.record(z.string(), z.nullable(z.any())).optional(),
  byteplus: z.record(z.string(), z.nullable(z.any())).optional(),
  centml: z.record(z.string(), z.nullable(z.any())).optional(),
  cerebras: z.record(z.string(), z.nullable(z.any())).optional(),
  chutes: z.record(z.string(), z.nullable(z.any())).optional(),
  cirrascale: z.record(z.string(), z.nullable(z.any())).optional(),
  clarifai: z.record(z.string(), z.nullable(z.any())).optional(),
  cloudflare: z.record(z.string(), z.nullable(z.any())).optional(),
  cohere: z.record(z.string(), z.nullable(z.any())).optional(),
  crofai: z.record(z.string(), z.nullable(z.any())).optional(),
  crucible: z.record(z.string(), z.nullable(z.any())).optional(),
  crusoe: z.record(z.string(), z.nullable(z.any())).optional(),
  darkbloom: z.record(z.string(), z.nullable(z.any())).optional(),
  decart: z.record(z.string(), z.nullable(z.any())).optional(),
  deepgram: z.record(z.string(), z.nullable(z.any())).optional(),
  deepinfra: z.record(z.string(), z.nullable(z.any())).optional(),
  deepseek: z.record(z.string(), z.nullable(z.any())).optional(),
  dekallm: z.record(z.string(), z.nullable(z.any())).optional(),
  digitalocean: z.record(z.string(), z.nullable(z.any())).optional(),
  enfer: z.record(z.string(), z.nullable(z.any())).optional(),
  fakeProvider: z.record(z.string(), z.nullable(z.any())).optional(),
  featherless: z.record(z.string(), z.nullable(z.any())).optional(),
  fireworks: z.record(z.string(), z.nullable(z.any())).optional(),
  friendli: z.record(z.string(), z.nullable(z.any())).optional(),
  gmicloud: z.record(z.string(), z.nullable(z.any())).optional(),
  googleAiStudio: z.record(z.string(), z.nullable(z.any())).optional(),
  googleVertex: z.record(z.string(), z.nullable(z.any())).optional(),
  gopomelo: z.record(z.string(), z.nullable(z.any())).optional(),
  groq: z.record(z.string(), z.nullable(z.any())).optional(),
  heygen: z.record(z.string(), z.nullable(z.any())).optional(),
  huggingface: z.record(z.string(), z.nullable(z.any())).optional(),
  hyperbolic: z.record(z.string(), z.nullable(z.any())).optional(),
  hyperbolicQuantized: z.record(z.string(), z.nullable(z.any())).optional(),
  inception: z.record(z.string(), z.nullable(z.any())).optional(),
  inceptron: z.record(z.string(), z.nullable(z.any())).optional(),
  inferactVllm: z.record(z.string(), z.nullable(z.any())).optional(),
  inferenceNet: z.record(z.string(), z.nullable(z.any())).optional(),
  infermatic: z.record(z.string(), z.nullable(z.any())).optional(),
  inflection: z.record(z.string(), z.nullable(z.any())).optional(),
  inocloud: z.record(z.string(), z.nullable(z.any())).optional(),
  ioNet: z.record(z.string(), z.nullable(z.any())).optional(),
  ionstream: z.record(z.string(), z.nullable(z.any())).optional(),
  klusterai: z.record(z.string(), z.nullable(z.any())).optional(),
  lambda: z.record(z.string(), z.nullable(z.any())).optional(),
  lepton: z.record(z.string(), z.nullable(z.any())).optional(),
  liquid: z.record(z.string(), z.nullable(z.any())).optional(),
  lynn: z.record(z.string(), z.nullable(z.any())).optional(),
  lynnPrivate: z.record(z.string(), z.nullable(z.any())).optional(),
  mancer: z.record(z.string(), z.nullable(z.any())).optional(),
  mancerOld: z.record(z.string(), z.nullable(z.any())).optional(),
  mara: z.record(z.string(), z.nullable(z.any())).optional(),
  meta: z.record(z.string(), z.nullable(z.any())).optional(),
  minimax: z.record(z.string(), z.nullable(z.any())).optional(),
  mistral: z.record(z.string(), z.nullable(z.any())).optional(),
  modal: z.record(z.string(), z.nullable(z.any())).optional(),
  modelrun: z.record(z.string(), z.nullable(z.any())).optional(),
  modular: z.record(z.string(), z.nullable(z.any())).optional(),
  moonshotai: z.record(z.string(), z.nullable(z.any())).optional(),
  morph: z.record(z.string(), z.nullable(z.any())).optional(),
  ncompass: z.record(z.string(), z.nullable(z.any())).optional(),
  nebius: z.record(z.string(), z.nullable(z.any())).optional(),
  nexAgi: z.record(z.string(), z.nullable(z.any())).optional(),
  nextbit: z.record(z.string(), z.nullable(z.any())).optional(),
  nineteen: z.record(z.string(), z.nullable(z.any())).optional(),
  novita: z.record(z.string(), z.nullable(z.any())).optional(),
  nvidia: z.record(z.string(), z.nullable(z.any())).optional(),
  octoai: z.record(z.string(), z.nullable(z.any())).optional(),
  openInference: z.record(z.string(), z.nullable(z.any())).optional(),
  openai: z.record(z.string(), z.nullable(z.any())).optional(),
  parasail: z.record(z.string(), z.nullable(z.any())).optional(),
  perceptron: z.record(z.string(), z.nullable(z.any())).optional(),
  perplexity: z.record(z.string(), z.nullable(z.any())).optional(),
  phala: z.record(z.string(), z.nullable(z.any())).optional(),
  poolside: z.record(z.string(), z.nullable(z.any())).optional(),
  recraft: z.record(z.string(), z.nullable(z.any())).optional(),
  recursal: z.record(z.string(), z.nullable(z.any())).optional(),
  reflection: z.record(z.string(), z.nullable(z.any())).optional(),
  reka: z.record(z.string(), z.nullable(z.any())).optional(),
  relace: z.record(z.string(), z.nullable(z.any())).optional(),
  replicate: z.record(z.string(), z.nullable(z.any())).optional(),
  sakanaAi: z.record(z.string(), z.nullable(z.any())).optional(),
  sambanova: z.record(z.string(), z.nullable(z.any())).optional(),
  sambanovaCloaked: z.record(z.string(), z.nullable(z.any())).optional(),
  seed: z.record(z.string(), z.nullable(z.any())).optional(),
  sfCompute: z.record(z.string(), z.nullable(z.any())).optional(),
  siliconflow: z.record(z.string(), z.nullable(z.any())).optional(),
  sourceful: z.record(z.string(), z.nullable(z.any())).optional(),
  stealth: z.record(z.string(), z.nullable(z.any())).optional(),
  stepfun: z.record(z.string(), z.nullable(z.any())).optional(),
  streamlake: z.record(z.string(), z.nullable(z.any())).optional(),
  switchpoint: z.record(z.string(), z.nullable(z.any())).optional(),
  targon: z.record(z.string(), z.nullable(z.any())).optional(),
  tenstorrent: z.record(z.string(), z.nullable(z.any())).optional(),
  together: z.record(z.string(), z.nullable(z.any())).optional(),
  togetherLite: z.record(z.string(), z.nullable(z.any())).optional(),
  ubicloud: z.record(z.string(), z.nullable(z.any())).optional(),
  upstage: z.record(z.string(), z.nullable(z.any())).optional(),
  venice: z.record(z.string(), z.nullable(z.any())).optional(),
  wafer: z.record(z.string(), z.nullable(z.any())).optional(),
  wandb: z.record(z.string(), z.nullable(z.any())).optional(),
  xai: z.record(z.string(), z.nullable(z.any())).optional(),
  xiaomi: z.record(z.string(), z.nullable(z.any())).optional(),
  zAi: z.record(z.string(), z.nullable(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    oneai: "01ai",
    aionLabs: "aion-labs",
    amazonBedrock: "amazon-bedrock",
    amazonNova: "amazon-nova",
    arceeAi: "arcee-ai",
    atlasCloud: "atlas-cloud",
    blackForestLabs: "black-forest-labs",
    fakeProvider: "fake-provider",
    googleAiStudio: "google-ai-studio",
    googleVertex: "google-vertex",
    hyperbolicQuantized: "hyperbolic-quantized",
    inferactVllm: "inferact-vllm",
    inferenceNet: "inference-net",
    ioNet: "io-net",
    lynnPrivate: "lynn-private",
    mancerOld: "mancer-old",
    nexAgi: "nex-agi",
    openInference: "open-inference",
    sakanaAi: "sakana-ai",
    sambanovaCloaked: "sambanova-cloaked",
    sfCompute: "sf-compute",
    togetherLite: "together-lite",
    zAi: "z-ai",
  });
});

export function imageGenerationRequestOptionsToJSON(
  imageGenerationRequestOptions: ImageGenerationRequestOptions,
): string {
  return JSON.stringify(
    ImageGenerationRequestOptions$outboundSchema.parse(
      imageGenerationRequestOptions,
    ),
  );
}

/** @internal */
export type ImageGenerationRequestProvider$Outbound = {
  options?: ImageGenerationRequestOptions$Outbound | undefined;
};

/** @internal */
export const ImageGenerationRequestProvider$outboundSchema: z.ZodType<
  ImageGenerationRequestProvider$Outbound,
  ImageGenerationRequestProvider
> = z.object({
  options: z.lazy(() => ImageGenerationRequestOptions$outboundSchema)
    .optional(),
});

export function imageGenerationRequestProviderToJSON(
  imageGenerationRequestProvider: ImageGenerationRequestProvider,
): string {
  return JSON.stringify(
    ImageGenerationRequestProvider$outboundSchema.parse(
      imageGenerationRequestProvider,
    ),
  );
}

/** @internal */
export const ImageGenerationRequestQuality$outboundSchema: z.ZodType<
  string,
  ImageGenerationRequestQuality
> = openEnums.outboundSchema(ImageGenerationRequestQuality);

/** @internal */
export const ImageGenerationRequestResolution$outboundSchema: z.ZodType<
  string,
  ImageGenerationRequestResolution
> = openEnums.outboundSchema(ImageGenerationRequestResolution);

/** @internal */
export type ImageGenerationRequest$Outbound = {
  aspect_ratio?: string | undefined;
  background?: string | undefined;
  input_references?: Array<ContentPartImage$Outbound> | undefined;
  model: string;
  n?: number | undefined;
  output_compression?: number | undefined;
  output_format?: string | undefined;
  prompt: string;
  provider?: ImageGenerationRequestProvider$Outbound | undefined;
  quality?: string | undefined;
  resolution?: string | undefined;
  seed?: number | undefined;
  size?: string | undefined;
  stream?: boolean | undefined;
};

/** @internal */
export const ImageGenerationRequest$outboundSchema: z.ZodType<
  ImageGenerationRequest$Outbound,
  ImageGenerationRequest
> = z.object({
  aspectRatio: ImageGenerationRequestAspectRatio$outboundSchema.optional(),
  background: ImageGenerationRequestBackground$outboundSchema.optional(),
  inputReferences: z.array(ContentPartImage$outboundSchema).optional(),
  model: z.string(),
  n: z.int().optional(),
  outputCompression: z.int().optional(),
  outputFormat: ImageGenerationRequestOutputFormat$outboundSchema.optional(),
  prompt: z.string(),
  provider: z.lazy(() => ImageGenerationRequestProvider$outboundSchema)
    .optional(),
  quality: ImageGenerationRequestQuality$outboundSchema.optional(),
  resolution: ImageGenerationRequestResolution$outboundSchema.optional(),
  seed: z.int().optional(),
  size: z.string().optional(),
  stream: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    aspectRatio: "aspect_ratio",
    inputReferences: "input_references",
    outputCompression: "output_compression",
    outputFormat: "output_format",
  });
});

export function imageGenerationRequestToJSON(
  imageGenerationRequest: ImageGenerationRequest,
): string {
  return JSON.stringify(
    ImageGenerationRequest$outboundSchema.parse(imageGenerationRequest),
  );
}
