/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1efbad50f534
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ImageGenerationServerToolBackground = {
  Transparent: "transparent",
  Opaque: "opaque",
  Auto: "auto",
} as const;
export type ImageGenerationServerToolBackground = OpenEnum<
  typeof ImageGenerationServerToolBackground
>;

export const InputFidelity = {
  High: "high",
  Low: "low",
} as const;
export type InputFidelity = OpenEnum<typeof InputFidelity>;

export type InputImageMask = {
  fileId?: string | undefined;
  imageUrl?: string | undefined;
};

export const ModelEnum = {
  GptImage1: "gpt-image-1",
  GptImage1Mini: "gpt-image-1-mini",
} as const;
export type ModelEnum = OpenEnum<typeof ModelEnum>;

export const ImageGenerationServerToolModeration = {
  Auto: "auto",
  Low: "low",
} as const;
export type ImageGenerationServerToolModeration = OpenEnum<
  typeof ImageGenerationServerToolModeration
>;

export const ImageGenerationServerToolOutputFormat = {
  Png: "png",
  Webp: "webp",
  Jpeg: "jpeg",
} as const;
export type ImageGenerationServerToolOutputFormat = OpenEnum<
  typeof ImageGenerationServerToolOutputFormat
>;

export const ImageGenerationServerToolQuality = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Auto: "auto",
} as const;
export type ImageGenerationServerToolQuality = OpenEnum<
  typeof ImageGenerationServerToolQuality
>;

export const ImageGenerationServerToolSize = {
  OneThousandAndTwentyFourx1024: "1024x1024",
  OneThousandAndTwentyFourx1536: "1024x1536",
  OneThousandFiveHundredAndThirtySixx1024: "1536x1024",
  Auto: "auto",
} as const;
export type ImageGenerationServerToolSize = OpenEnum<
  typeof ImageGenerationServerToolSize
>;

/**
 * Image generation tool configuration
 */
export type ImageGenerationServerTool = {
  background?: ImageGenerationServerToolBackground | undefined;
  inputFidelity?: InputFidelity | null | undefined;
  inputImageMask?: InputImageMask | undefined;
  model?: ModelEnum | undefined;
  moderation?: ImageGenerationServerToolModeration | undefined;
  outputCompression?: number | undefined;
  outputFormat?: ImageGenerationServerToolOutputFormat | undefined;
  partialImages?: number | undefined;
  quality?: ImageGenerationServerToolQuality | undefined;
  size?: ImageGenerationServerToolSize | undefined;
  type: "image_generation";
};

/** @internal */
export const ImageGenerationServerToolBackground$inboundSchema: z.ZodType<
  ImageGenerationServerToolBackground,
  unknown
> = openEnums.inboundSchema(ImageGenerationServerToolBackground);
/** @internal */
export const ImageGenerationServerToolBackground$outboundSchema: z.ZodType<
  string,
  ImageGenerationServerToolBackground
> = openEnums.outboundSchema(ImageGenerationServerToolBackground);

/** @internal */
export const InputFidelity$inboundSchema: z.ZodType<InputFidelity, unknown> =
  openEnums.inboundSchema(InputFidelity);
/** @internal */
export const InputFidelity$outboundSchema: z.ZodType<string, InputFidelity> =
  openEnums.outboundSchema(InputFidelity);

/** @internal */
export const InputImageMask$inboundSchema: z.ZodType<InputImageMask, unknown> =
  z.object({
    file_id: z.string().optional(),
    image_url: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "file_id": "fileId",
      "image_url": "imageUrl",
    });
  });
/** @internal */
export type InputImageMask$Outbound = {
  file_id?: string | undefined;
  image_url?: string | undefined;
};

/** @internal */
export const InputImageMask$outboundSchema: z.ZodType<
  InputImageMask$Outbound,
  InputImageMask
> = z.object({
  fileId: z.string().optional(),
  imageUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
    imageUrl: "image_url",
  });
});

export function inputImageMaskToJSON(inputImageMask: InputImageMask): string {
  return JSON.stringify(InputImageMask$outboundSchema.parse(inputImageMask));
}
export function inputImageMaskFromJSON(
  jsonString: string,
): SafeParseResult<InputImageMask, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputImageMask$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputImageMask' from JSON`,
  );
}

/** @internal */
export const ModelEnum$inboundSchema: z.ZodType<ModelEnum, unknown> = openEnums
  .inboundSchema(ModelEnum);
/** @internal */
export const ModelEnum$outboundSchema: z.ZodType<string, ModelEnum> = openEnums
  .outboundSchema(ModelEnum);

/** @internal */
export const ImageGenerationServerToolModeration$inboundSchema: z.ZodType<
  ImageGenerationServerToolModeration,
  unknown
> = openEnums.inboundSchema(ImageGenerationServerToolModeration);
/** @internal */
export const ImageGenerationServerToolModeration$outboundSchema: z.ZodType<
  string,
  ImageGenerationServerToolModeration
> = openEnums.outboundSchema(ImageGenerationServerToolModeration);

/** @internal */
export const ImageGenerationServerToolOutputFormat$inboundSchema: z.ZodType<
  ImageGenerationServerToolOutputFormat,
  unknown
> = openEnums.inboundSchema(ImageGenerationServerToolOutputFormat);
/** @internal */
export const ImageGenerationServerToolOutputFormat$outboundSchema: z.ZodType<
  string,
  ImageGenerationServerToolOutputFormat
> = openEnums.outboundSchema(ImageGenerationServerToolOutputFormat);

/** @internal */
export const ImageGenerationServerToolQuality$inboundSchema: z.ZodType<
  ImageGenerationServerToolQuality,
  unknown
> = openEnums.inboundSchema(ImageGenerationServerToolQuality);
/** @internal */
export const ImageGenerationServerToolQuality$outboundSchema: z.ZodType<
  string,
  ImageGenerationServerToolQuality
> = openEnums.outboundSchema(ImageGenerationServerToolQuality);

/** @internal */
export const ImageGenerationServerToolSize$inboundSchema: z.ZodType<
  ImageGenerationServerToolSize,
  unknown
> = openEnums.inboundSchema(ImageGenerationServerToolSize);
/** @internal */
export const ImageGenerationServerToolSize$outboundSchema: z.ZodType<
  string,
  ImageGenerationServerToolSize
> = openEnums.outboundSchema(ImageGenerationServerToolSize);

/** @internal */
export const ImageGenerationServerTool$inboundSchema: z.ZodType<
  ImageGenerationServerTool,
  unknown
> = z.object({
  background: ImageGenerationServerToolBackground$inboundSchema.optional(),
  input_fidelity: z.nullable(InputFidelity$inboundSchema).optional(),
  input_image_mask: z.lazy(() => InputImageMask$inboundSchema).optional(),
  model: ModelEnum$inboundSchema.optional(),
  moderation: ImageGenerationServerToolModeration$inboundSchema.optional(),
  output_compression: z.int().optional(),
  output_format: ImageGenerationServerToolOutputFormat$inboundSchema.optional(),
  partial_images: z.int().optional(),
  quality: ImageGenerationServerToolQuality$inboundSchema.optional(),
  size: ImageGenerationServerToolSize$inboundSchema.optional(),
  type: z.literal("image_generation"),
}).transform((v) => {
  return remap$(v, {
    "input_fidelity": "inputFidelity",
    "input_image_mask": "inputImageMask",
    "output_compression": "outputCompression",
    "output_format": "outputFormat",
    "partial_images": "partialImages",
  });
});
/** @internal */
export type ImageGenerationServerTool$Outbound = {
  background?: string | undefined;
  input_fidelity?: string | null | undefined;
  input_image_mask?: InputImageMask$Outbound | undefined;
  model?: string | undefined;
  moderation?: string | undefined;
  output_compression?: number | undefined;
  output_format?: string | undefined;
  partial_images?: number | undefined;
  quality?: string | undefined;
  size?: string | undefined;
  type: "image_generation";
};

/** @internal */
export const ImageGenerationServerTool$outboundSchema: z.ZodType<
  ImageGenerationServerTool$Outbound,
  ImageGenerationServerTool
> = z.object({
  background: ImageGenerationServerToolBackground$outboundSchema.optional(),
  inputFidelity: z.nullable(InputFidelity$outboundSchema).optional(),
  inputImageMask: z.lazy(() => InputImageMask$outboundSchema).optional(),
  model: ModelEnum$outboundSchema.optional(),
  moderation: ImageGenerationServerToolModeration$outboundSchema.optional(),
  outputCompression: z.int().optional(),
  outputFormat: ImageGenerationServerToolOutputFormat$outboundSchema.optional(),
  partialImages: z.int().optional(),
  quality: ImageGenerationServerToolQuality$outboundSchema.optional(),
  size: ImageGenerationServerToolSize$outboundSchema.optional(),
  type: z.literal("image_generation"),
}).transform((v) => {
  return remap$(v, {
    inputFidelity: "input_fidelity",
    inputImageMask: "input_image_mask",
    outputCompression: "output_compression",
    outputFormat: "output_format",
    partialImages: "partial_images",
  });
});

export function imageGenerationServerToolToJSON(
  imageGenerationServerTool: ImageGenerationServerTool,
): string {
  return JSON.stringify(
    ImageGenerationServerTool$outboundSchema.parse(imageGenerationServerTool),
  );
}
export function imageGenerationServerToolFromJSON(
  jsonString: string,
): SafeParseResult<ImageGenerationServerTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageGenerationServerTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageGenerationServerTool' from JSON`,
  );
}
