/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c2dc1f33e1df
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  InternChatToolCall,
  InternChatToolCall$inboundSchema,
} from "./internchattoolcall.js";

export const InternChatDeltaRole = {
  Assistant: "assistant",
} as const;
export type InternChatDeltaRole = ClosedEnum<typeof InternChatDeltaRole>;

/**
 * The incremental content of one chunk. The first chunk carries `role`, text chunks carry `content`, reasoning chunks carry `reasoning`, and an interaction chunk carries one complete `tool_calls` entry.
 */
export type InternChatDelta = {
  content?: string | undefined;
  reasoning?: string | undefined;
  role?: InternChatDeltaRole | undefined;
  toolCalls?: Array<InternChatToolCall> | undefined;
};

/** @internal */
export const InternChatDeltaRole$inboundSchema: z.ZodEnum<
  typeof InternChatDeltaRole
> = z.enum(InternChatDeltaRole);

/** @internal */
export const InternChatDelta$inboundSchema: z.ZodType<
  InternChatDelta,
  unknown
> = z.object({
  content: z.string().optional(),
  reasoning: z.string().optional(),
  role: InternChatDeltaRole$inboundSchema.optional(),
  tool_calls: z.array(InternChatToolCall$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_calls": "toolCalls",
  });
});

export function internChatDeltaFromJSON(
  jsonString: string,
): SafeParseResult<InternChatDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InternChatDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternChatDelta' from JSON`,
  );
}
