/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1a9c64204177
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  SearchContextSizeEnum,
  SearchContextSizeEnum$inboundSchema,
  SearchContextSizeEnum$outboundSchema,
} from "./searchcontextsizeenum.js";
import {
  WebSearchDomainFilter,
  WebSearchDomainFilter$inboundSchema,
  WebSearchDomainFilter$Outbound,
  WebSearchDomainFilter$outboundSchema,
} from "./websearchdomainfilter.js";
import {
  WebSearchEngineEnum,
  WebSearchEngineEnum$inboundSchema,
  WebSearchEngineEnum$outboundSchema,
} from "./websearchengineenum.js";

export const LegacyWebSearchServerToolTypeApproximate = {
  Approximate: "approximate",
} as const;
export type LegacyWebSearchServerToolTypeApproximate = ClosedEnum<
  typeof LegacyWebSearchServerToolTypeApproximate
>;

/**
 * User location information for web search
 */
export type LegacyWebSearchServerToolUserLocation = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  region?: string | null | undefined;
  timezone?: string | null | undefined;
  type: LegacyWebSearchServerToolTypeApproximate;
};

/**
 * Web search tool configuration
 */
export type LegacyWebSearchServerTool = {
  /**
   * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API.
   */
  engine?: WebSearchEngineEnum | undefined;
  filters?: WebSearchDomainFilter | null | undefined;
  /**
   * Maximum number of search results to return per search call. Defaults to 5. Applies to Exa, Firecrawl, and Parallel engines; ignored with native provider search.
   */
  maxResults?: number | undefined;
  /**
   * Size of the search context for web search tools
   */
  searchContextSize?: SearchContextSizeEnum | undefined;
  type: "web_search";
  userLocation?: LegacyWebSearchServerToolUserLocation | null | undefined;
};

/** @internal */
export const LegacyWebSearchServerToolTypeApproximate$inboundSchema: z.ZodEnum<
  typeof LegacyWebSearchServerToolTypeApproximate
> = z.enum(LegacyWebSearchServerToolTypeApproximate);
/** @internal */
export const LegacyWebSearchServerToolTypeApproximate$outboundSchema: z.ZodEnum<
  typeof LegacyWebSearchServerToolTypeApproximate
> = LegacyWebSearchServerToolTypeApproximate$inboundSchema;

/** @internal */
export const LegacyWebSearchServerToolUserLocation$inboundSchema: z.ZodType<
  LegacyWebSearchServerToolUserLocation,
  unknown
> = z.object({
  city: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  timezone: z.nullable(z.string()).optional(),
  type: LegacyWebSearchServerToolTypeApproximate$inboundSchema,
});
/** @internal */
export type LegacyWebSearchServerToolUserLocation$Outbound = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  region?: string | null | undefined;
  timezone?: string | null | undefined;
  type: string;
};

/** @internal */
export const LegacyWebSearchServerToolUserLocation$outboundSchema: z.ZodType<
  LegacyWebSearchServerToolUserLocation$Outbound,
  LegacyWebSearchServerToolUserLocation
> = z.object({
  city: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  timezone: z.nullable(z.string()).optional(),
  type: LegacyWebSearchServerToolTypeApproximate$outboundSchema,
});

export function legacyWebSearchServerToolUserLocationToJSON(
  legacyWebSearchServerToolUserLocation: LegacyWebSearchServerToolUserLocation,
): string {
  return JSON.stringify(
    LegacyWebSearchServerToolUserLocation$outboundSchema.parse(
      legacyWebSearchServerToolUserLocation,
    ),
  );
}
export function legacyWebSearchServerToolUserLocationFromJSON(
  jsonString: string,
): SafeParseResult<LegacyWebSearchServerToolUserLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LegacyWebSearchServerToolUserLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LegacyWebSearchServerToolUserLocation' from JSON`,
  );
}

/** @internal */
export const LegacyWebSearchServerTool$inboundSchema: z.ZodType<
  LegacyWebSearchServerTool,
  unknown
> = z.object({
  engine: WebSearchEngineEnum$inboundSchema.optional(),
  filters: z.nullable(WebSearchDomainFilter$inboundSchema).optional(),
  max_results: z.int().optional(),
  search_context_size: SearchContextSizeEnum$inboundSchema.optional(),
  type: z.literal("web_search"),
  user_location: z.nullable(
    z.lazy(() => LegacyWebSearchServerToolUserLocation$inboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "max_results": "maxResults",
    "search_context_size": "searchContextSize",
    "user_location": "userLocation",
  });
});
/** @internal */
export type LegacyWebSearchServerTool$Outbound = {
  engine?: string | undefined;
  filters?: WebSearchDomainFilter$Outbound | null | undefined;
  max_results?: number | undefined;
  search_context_size?: string | undefined;
  type: "web_search";
  user_location?:
    | LegacyWebSearchServerToolUserLocation$Outbound
    | null
    | undefined;
};

/** @internal */
export const LegacyWebSearchServerTool$outboundSchema: z.ZodType<
  LegacyWebSearchServerTool$Outbound,
  LegacyWebSearchServerTool
> = z.object({
  engine: WebSearchEngineEnum$outboundSchema.optional(),
  filters: z.nullable(WebSearchDomainFilter$outboundSchema).optional(),
  maxResults: z.int().optional(),
  searchContextSize: SearchContextSizeEnum$outboundSchema.optional(),
  type: z.literal("web_search"),
  userLocation: z.nullable(
    z.lazy(() => LegacyWebSearchServerToolUserLocation$outboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    maxResults: "max_results",
    searchContextSize: "search_context_size",
    userLocation: "user_location",
  });
});

export function legacyWebSearchServerToolToJSON(
  legacyWebSearchServerTool: LegacyWebSearchServerTool,
): string {
  return JSON.stringify(
    LegacyWebSearchServerTool$outboundSchema.parse(legacyWebSearchServerTool),
  );
}
export function legacyWebSearchServerToolFromJSON(
  jsonString: string,
): SafeParseResult<LegacyWebSearchServerTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LegacyWebSearchServerTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LegacyWebSearchServerTool' from JSON`,
  );
}
