/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 33f95516f59f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Output of an `openrouter:shell` call from a prior assistant turn. Accepted on replay and dropped before the provider request — Anthropic has no equivalent block.
 */
export type MessagesShellToolResultBlock = {
  content: { [k: string]: any };
  toolUseId: string;
  type: "openrouter_shell_tool_result";
};

/** @internal */
export type MessagesShellToolResultBlock$Outbound = {
  content: { [k: string]: any };
  tool_use_id: string;
  type: "openrouter_shell_tool_result";
};

/** @internal */
export const MessagesShellToolResultBlock$outboundSchema: z.ZodType<
  MessagesShellToolResultBlock$Outbound,
  MessagesShellToolResultBlock
> = z.object({
  content: z.record(z.string(), z.any()),
  toolUseId: z.string(),
  type: z.literal("openrouter_shell_tool_result"),
}).transform((v) => {
  return remap$(v, {
    toolUseId: "tool_use_id",
  });
});

export function messagesShellToolResultBlockToJSON(
  messagesShellToolResultBlock: MessagesShellToolResultBlock,
): string {
  return JSON.stringify(
    MessagesShellToolResultBlock$outboundSchema.parse(
      messagesShellToolResultBlock,
    ),
  );
}
