/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c7312e55417d
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReasoningEffort,
  ReasoningEffort$inboundSchema,
} from "./reasoningeffort.js";

/**
 * Default reasoning effort when the client enables reasoning without specifying effort. Maps to `reasoning.effort` in chat requests. When `"none"`, prefer omitting effort unless the user explicitly disables reasoning.
 */
export const DefaultEffort = {
  Xhigh: "xhigh",
  High: "high",
  Medium: "medium",
  Low: "low",
  Minimal: "minimal",
  None: "none",
} as const;
/**
 * Default reasoning effort when the client enables reasoning without specifying effort. Maps to `reasoning.effort` in chat requests. When `"none"`, prefer omitting effort unless the user explicitly disables reasoning.
 */
export type DefaultEffort = OpenEnum<typeof DefaultEffort>;

/**
 * Reasoning effort configuration. Omitted for non-reasoning models and dynamic router models.
 */
export type ModelReasoning = {
  defaultEffort?: DefaultEffort | null | undefined;
  /**
   * Default reasoning enabled state when the client does not set `reasoning.enabled`.
   */
  defaultEnabled?: boolean | undefined;
  /**
   * When true, reasoning cannot be disabled and effort "none" is rejected.
   */
  mandatory: boolean;
  /**
   * Allowed reasoning effort values for this model, in descending effort order (highest first). Null means no allowlist — all gateway effort values are accepted.
   */
  supportedEfforts?: Array<ReasoningEffort | null> | null | undefined;
  /**
   * Present and `true` when the model accepts `reasoning.max_tokens` in requests (Anthropic-style) instead of or in addition to `reasoning.effort`. Omitted otherwise.
   */
  supportsMaxTokens?: boolean | undefined;
};

/** @internal */
export const DefaultEffort$inboundSchema: z.ZodType<DefaultEffort, unknown> =
  openEnums.inboundSchema(DefaultEffort);

/** @internal */
export const ModelReasoning$inboundSchema: z.ZodType<ModelReasoning, unknown> =
  z.object({
    default_effort: z.nullable(DefaultEffort$inboundSchema).optional(),
    default_enabled: z.boolean().optional(),
    mandatory: z.boolean(),
    supported_efforts: z.nullable(
      z.array(z.nullable(ReasoningEffort$inboundSchema)),
    ).optional(),
    supports_max_tokens: z.boolean().optional(),
  }).transform((v) => {
    return remap$(v, {
      "default_effort": "defaultEffort",
      "default_enabled": "defaultEnabled",
      "supported_efforts": "supportedEfforts",
      "supports_max_tokens": "supportsMaxTokens",
    });
  });

export function modelReasoningFromJSON(
  jsonString: string,
): SafeParseResult<ModelReasoning, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelReasoning$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelReasoning' from JSON`,
  );
}
