/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Error data for NotFoundResponse
 */
export type NotFoundResponseErrorData = {
  code: number;
  message: string;
  metadata?: { [k: string]: any | null } | null | undefined;
};

/** @internal */
export const NotFoundResponseErrorData$inboundSchema: z.ZodType<
  NotFoundResponseErrorData,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  metadata: z.nullable(z.record(z.string(), z.nullable(z.any()))).optional(),
});

/** @internal */
export type NotFoundResponseErrorData$Outbound = {
  code: number;
  message: string;
  metadata?: { [k: string]: any | null } | null | undefined;
};

/** @internal */
export const NotFoundResponseErrorData$outboundSchema: z.ZodType<
  NotFoundResponseErrorData$Outbound,
  NotFoundResponseErrorData
> = z.object({
  code: z.number().int(),
  message: z.string(),
  metadata: z.nullable(z.record(z.string(), z.nullable(z.any()))).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotFoundResponseErrorData$ {
  /** @deprecated use `NotFoundResponseErrorData$inboundSchema` instead. */
  export const inboundSchema = NotFoundResponseErrorData$inboundSchema;
  /** @deprecated use `NotFoundResponseErrorData$outboundSchema` instead. */
  export const outboundSchema = NotFoundResponseErrorData$outboundSchema;
  /** @deprecated use `NotFoundResponseErrorData$Outbound` instead. */
  export type Outbound = NotFoundResponseErrorData$Outbound;
}

export function notFoundResponseErrorDataToJSON(
  notFoundResponseErrorData: NotFoundResponseErrorData,
): string {
  return JSON.stringify(
    NotFoundResponseErrorData$outboundSchema.parse(notFoundResponseErrorData),
  );
}

export function notFoundResponseErrorDataFromJSON(
  jsonString: string,
): SafeParseResult<NotFoundResponseErrorData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotFoundResponseErrorData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotFoundResponseErrorData' from JSON`,
  );
}
