/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 628ce2e2989d
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ObservabilityFilterRulesConfig,
  ObservabilityFilterRulesConfig$inboundSchema,
} from "./observabilityfilterrulesconfig.js";

export type ObservabilityClickhouseDestinationConfig = {
  database: string;
  /**
   * Custom HTTP headers to include in requests to this destination.
   */
  headers?: { [k: string]: string } | undefined;
  host: string;
  password: string;
  table: string;
  /**
   * If you have not set a specific username in ClickHouse, simply type in 'default' below.
   */
  username: string;
};

export type ObservabilityClickhouseDestination = {
  /**
   * Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) whose traffic is forwarded to this destination. `null` means all keys.
   */
  apiKeyHashes: Array<string> | null;
  config: ObservabilityClickhouseDestinationConfig;
  /**
   * ISO timestamp of when the destination was created.
   */
  createdAt: string;
  /**
   * Whether this destination is currently enabled.
   */
  enabled: boolean;
  /**
   * Optional structured filter rules controlling which events are forwarded.
   */
  filterRules: ObservabilityFilterRulesConfig | null;
  /**
   * Stable public identifier for this destination.
   */
  id: string;
  /**
   * Human-readable name for the destination.
   */
  name: string | null;
  /**
   * When true, request/response bodies are not forwarded to this destination — only metadata.
   */
  privacyMode: boolean;
  /**
   * Sampling rate for events sent to this destination, between 0 and 1 (1 = 100%).
   */
  samplingRate: number;
  type: "clickhouse";
  /**
   * ISO timestamp of when the destination was last updated.
   */
  updatedAt: string;
  /**
   * ID of the workspace this destination belongs to.
   */
  workspaceId: string;
};

/** @internal */
export const ObservabilityClickhouseDestinationConfig$inboundSchema: z.ZodType<
  ObservabilityClickhouseDestinationConfig,
  unknown
> = z.object({
  database: z.string(),
  headers: z.record(z.string(), z.string()).optional(),
  host: z.string(),
  password: z.string(),
  table: z.string().default("OPENROUTER_TRACES"),
  username: z.string(),
});

export function observabilityClickhouseDestinationConfigFromJSON(
  jsonString: string,
): SafeParseResult<
  ObservabilityClickhouseDestinationConfig,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ObservabilityClickhouseDestinationConfig$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ObservabilityClickhouseDestinationConfig' from JSON`,
  );
}

/** @internal */
export const ObservabilityClickhouseDestination$inboundSchema: z.ZodType<
  ObservabilityClickhouseDestination,
  unknown
> = z.object({
  api_key_hashes: z.nullable(z.array(z.string())),
  config: z.lazy(() => ObservabilityClickhouseDestinationConfig$inboundSchema),
  created_at: z.string(),
  enabled: z.boolean(),
  filter_rules: z.nullable(ObservabilityFilterRulesConfig$inboundSchema),
  id: z.string(),
  name: z.nullable(z.string()),
  privacy_mode: z.boolean(),
  sampling_rate: z.number(),
  type: z.literal("clickhouse"),
  updated_at: z.string(),
  workspace_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "api_key_hashes": "apiKeyHashes",
    "created_at": "createdAt",
    "filter_rules": "filterRules",
    "privacy_mode": "privacyMode",
    "sampling_rate": "samplingRate",
    "updated_at": "updatedAt",
    "workspace_id": "workspaceId",
  });
});

export function observabilityClickhouseDestinationFromJSON(
  jsonString: string,
): SafeParseResult<ObservabilityClickhouseDestination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ObservabilityClickhouseDestination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ObservabilityClickhouseDestination' from JSON`,
  );
}
