/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const OpenResponsesImageGenCallPartialImageType = {
  ResponseImageGenerationCallPartialImage:
    "response.image_generation_call.partial_image",
} as const;
export type OpenResponsesImageGenCallPartialImageType = ClosedEnum<
  typeof OpenResponsesImageGenCallPartialImageType
>;

/**
 * Image generation call with partial image
 */
export type OpenResponsesImageGenCallPartialImage = {
  type: OpenResponsesImageGenCallPartialImageType;
  itemId: string;
  outputIndex: number;
  sequenceNumber: number;
  partialImageB64: string;
  partialImageIndex: number;
};

/** @internal */
export const OpenResponsesImageGenCallPartialImageType$inboundSchema:
  z.ZodNativeEnum<typeof OpenResponsesImageGenCallPartialImageType> = z
    .nativeEnum(OpenResponsesImageGenCallPartialImageType);

/** @internal */
export const OpenResponsesImageGenCallPartialImageType$outboundSchema:
  z.ZodNativeEnum<typeof OpenResponsesImageGenCallPartialImageType> =
    OpenResponsesImageGenCallPartialImageType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OpenResponsesImageGenCallPartialImageType$ {
  /** @deprecated use `OpenResponsesImageGenCallPartialImageType$inboundSchema` instead. */
  export const inboundSchema =
    OpenResponsesImageGenCallPartialImageType$inboundSchema;
  /** @deprecated use `OpenResponsesImageGenCallPartialImageType$outboundSchema` instead. */
  export const outboundSchema =
    OpenResponsesImageGenCallPartialImageType$outboundSchema;
}

/** @internal */
export const OpenResponsesImageGenCallPartialImage$inboundSchema: z.ZodType<
  OpenResponsesImageGenCallPartialImage,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: OpenResponsesImageGenCallPartialImageType$inboundSchema,
  item_id: z.string(),
  output_index: z.number(),
  sequence_number: z.number(),
  partial_image_b64: z.string(),
  partial_image_index: z.number(),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
    "partial_image_b64": "partialImageB64",
    "partial_image_index": "partialImageIndex",
  });
});

/** @internal */
export type OpenResponsesImageGenCallPartialImage$Outbound = {
  type: string;
  item_id: string;
  output_index: number;
  sequence_number: number;
  partial_image_b64: string;
  partial_image_index: number;
};

/** @internal */
export const OpenResponsesImageGenCallPartialImage$outboundSchema: z.ZodType<
  OpenResponsesImageGenCallPartialImage$Outbound,
  z.ZodTypeDef,
  OpenResponsesImageGenCallPartialImage
> = z.object({
  type: OpenResponsesImageGenCallPartialImageType$outboundSchema,
  itemId: z.string(),
  outputIndex: z.number(),
  sequenceNumber: z.number(),
  partialImageB64: z.string(),
  partialImageIndex: z.number(),
}).transform((v) => {
  return remap$(v, {
    itemId: "item_id",
    outputIndex: "output_index",
    sequenceNumber: "sequence_number",
    partialImageB64: "partial_image_b64",
    partialImageIndex: "partial_image_index",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OpenResponsesImageGenCallPartialImage$ {
  /** @deprecated use `OpenResponsesImageGenCallPartialImage$inboundSchema` instead. */
  export const inboundSchema =
    OpenResponsesImageGenCallPartialImage$inboundSchema;
  /** @deprecated use `OpenResponsesImageGenCallPartialImage$outboundSchema` instead. */
  export const outboundSchema =
    OpenResponsesImageGenCallPartialImage$outboundSchema;
  /** @deprecated use `OpenResponsesImageGenCallPartialImage$Outbound` instead. */
  export type Outbound = OpenResponsesImageGenCallPartialImage$Outbound;
}

export function openResponsesImageGenCallPartialImageToJSON(
  openResponsesImageGenCallPartialImage: OpenResponsesImageGenCallPartialImage,
): string {
  return JSON.stringify(
    OpenResponsesImageGenCallPartialImage$outboundSchema.parse(
      openResponsesImageGenCallPartialImage,
    ),
  );
}

export function openResponsesImageGenCallPartialImageFromJSON(
  jsonString: string,
): SafeParseResult<OpenResponsesImageGenCallPartialImage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      OpenResponsesImageGenCallPartialImage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenResponsesImageGenCallPartialImage' from JSON`,
  );
}
