/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 510ab58460c2
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ResponsesSearchContextSize,
  ResponsesSearchContextSize$inboundSchema,
  ResponsesSearchContextSize$outboundSchema,
} from "./responsessearchcontextsize.js";
import {
  ResponsesWebSearchUserLocation,
  ResponsesWebSearchUserLocation$inboundSchema,
  ResponsesWebSearchUserLocation$Outbound,
  ResponsesWebSearchUserLocation$outboundSchema,
} from "./responseswebsearchuserlocation.js";

export type OpenResponsesWebSearchToolFilters = {
  allowedDomains?: Array<string> | null | undefined;
  excludedDomains?: Array<string> | null | undefined;
};

/**
 * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API.
 */
export const OpenResponsesWebSearchToolEngine = {
  Auto: "auto",
  Native: "native",
  Exa: "exa",
} as const;
/**
 * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API.
 */
export type OpenResponsesWebSearchToolEngine = OpenEnum<
  typeof OpenResponsesWebSearchToolEngine
>;

/**
 * Web search tool configuration
 */
export type OpenResponsesWebSearchTool = {
  type: "web_search";
  filters?: OpenResponsesWebSearchToolFilters | null | undefined;
  /**
   * Size of the search context for web search tools
   */
  searchContextSize?: ResponsesSearchContextSize | undefined;
  /**
   * User location information for web search
   */
  userLocation?: ResponsesWebSearchUserLocation | null | undefined;
  /**
   * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API.
   */
  engine?: OpenResponsesWebSearchToolEngine | undefined;
  /**
   * Maximum number of search results to return per search call. Defaults to 5.
   */
  maxResults?: number | undefined;
};

/** @internal */
export const OpenResponsesWebSearchToolFilters$inboundSchema: z.ZodType<
  OpenResponsesWebSearchToolFilters,
  unknown
> = z.object({
  allowed_domains: z.nullable(z.array(z.string())).optional(),
  excluded_domains: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "allowed_domains": "allowedDomains",
    "excluded_domains": "excludedDomains",
  });
});
/** @internal */
export type OpenResponsesWebSearchToolFilters$Outbound = {
  allowed_domains?: Array<string> | null | undefined;
  excluded_domains?: Array<string> | null | undefined;
};

/** @internal */
export const OpenResponsesWebSearchToolFilters$outboundSchema: z.ZodType<
  OpenResponsesWebSearchToolFilters$Outbound,
  OpenResponsesWebSearchToolFilters
> = z.object({
  allowedDomains: z.nullable(z.array(z.string())).optional(),
  excludedDomains: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    allowedDomains: "allowed_domains",
    excludedDomains: "excluded_domains",
  });
});

export function openResponsesWebSearchToolFiltersToJSON(
  openResponsesWebSearchToolFilters: OpenResponsesWebSearchToolFilters,
): string {
  return JSON.stringify(
    OpenResponsesWebSearchToolFilters$outboundSchema.parse(
      openResponsesWebSearchToolFilters,
    ),
  );
}
export function openResponsesWebSearchToolFiltersFromJSON(
  jsonString: string,
): SafeParseResult<OpenResponsesWebSearchToolFilters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenResponsesWebSearchToolFilters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenResponsesWebSearchToolFilters' from JSON`,
  );
}

/** @internal */
export const OpenResponsesWebSearchToolEngine$inboundSchema: z.ZodType<
  OpenResponsesWebSearchToolEngine,
  unknown
> = openEnums.inboundSchema(OpenResponsesWebSearchToolEngine);
/** @internal */
export const OpenResponsesWebSearchToolEngine$outboundSchema: z.ZodType<
  string,
  OpenResponsesWebSearchToolEngine
> = openEnums.outboundSchema(OpenResponsesWebSearchToolEngine);

/** @internal */
export const OpenResponsesWebSearchTool$inboundSchema: z.ZodType<
  OpenResponsesWebSearchTool,
  unknown
> = z.object({
  type: z.literal("web_search"),
  filters: z.nullable(
    z.lazy(() => OpenResponsesWebSearchToolFilters$inboundSchema),
  ).optional(),
  search_context_size: ResponsesSearchContextSize$inboundSchema.optional(),
  user_location: z.nullable(ResponsesWebSearchUserLocation$inboundSchema)
    .optional(),
  engine: OpenResponsesWebSearchToolEngine$inboundSchema.optional(),
  max_results: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "search_context_size": "searchContextSize",
    "user_location": "userLocation",
    "max_results": "maxResults",
  });
});
/** @internal */
export type OpenResponsesWebSearchTool$Outbound = {
  type: "web_search";
  filters?: OpenResponsesWebSearchToolFilters$Outbound | null | undefined;
  search_context_size?: string | undefined;
  user_location?: ResponsesWebSearchUserLocation$Outbound | null | undefined;
  engine?: string | undefined;
  max_results?: number | undefined;
};

/** @internal */
export const OpenResponsesWebSearchTool$outboundSchema: z.ZodType<
  OpenResponsesWebSearchTool$Outbound,
  OpenResponsesWebSearchTool
> = z.object({
  type: z.literal("web_search"),
  filters: z.nullable(
    z.lazy(() => OpenResponsesWebSearchToolFilters$outboundSchema),
  ).optional(),
  searchContextSize: ResponsesSearchContextSize$outboundSchema.optional(),
  userLocation: z.nullable(ResponsesWebSearchUserLocation$outboundSchema)
    .optional(),
  engine: OpenResponsesWebSearchToolEngine$outboundSchema.optional(),
  maxResults: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    searchContextSize: "search_context_size",
    userLocation: "user_location",
    maxResults: "max_results",
  });
});

export function openResponsesWebSearchToolToJSON(
  openResponsesWebSearchTool: OpenResponsesWebSearchTool,
): string {
  return JSON.stringify(
    OpenResponsesWebSearchTool$outboundSchema.parse(openResponsesWebSearchTool),
  );
}
export function openResponsesWebSearchToolFromJSON(
  jsonString: string,
): SafeParseResult<OpenResponsesWebSearchTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenResponsesWebSearchTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenResponsesWebSearchTool' from JSON`,
  );
}
