/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c583d897e9d2
 */

import type { Result as SafeParseResult } from '../types/fp.js';
import type { SDKValidationError } from './errors/sdkvalidationerror.js';
import type { ResponseInputFile, ResponseInputFile$Outbound } from './responseinputfile.js';
import type { ResponseInputImage, ResponseInputImage$Outbound } from './responseinputimage.js';
import type { ResponseInputText, ResponseInputText$Outbound } from './responseinputtext.js';

import * as z from 'zod/v4';
import { safeParse } from '../lib/schemas.js';
import {
  ResponseInputFile$inboundSchema,
  ResponseInputFile$outboundSchema,
} from './responseinputfile.js';
import {
  ResponseInputImage$inboundSchema,
  ResponseInputImage$outboundSchema,
} from './responseinputimage.js';
import {
  ResponseInputText$inboundSchema,
  ResponseInputText$outboundSchema,
} from './responseinputtext.js';

export type Variables = ResponseInputText | ResponseInputImage | ResponseInputFile | string;

export type OpenAIResponsesPrompt = {
  id: string;
  variables?:
    | {
        [k: string]: ResponseInputText | ResponseInputImage | ResponseInputFile | string;
      }
    | null
    | undefined;
};

/** @internal */
export const Variables$inboundSchema: z.ZodType<Variables, unknown> = z.union([
  ResponseInputText$inboundSchema,
  ResponseInputImage$inboundSchema,
  ResponseInputFile$inboundSchema,
  z.string(),
]);
/** @internal */
export type Variables$Outbound =
  | ResponseInputText$Outbound
  | ResponseInputImage$Outbound
  | ResponseInputFile$Outbound
  | string;

/** @internal */
export const Variables$outboundSchema: z.ZodType<Variables$Outbound, Variables> = z.union([
  ResponseInputText$outboundSchema,
  ResponseInputImage$outboundSchema,
  ResponseInputFile$outboundSchema,
  z.string(),
]);

export function variablesToJSON(variables: Variables): string {
  return JSON.stringify(Variables$outboundSchema.parse(variables));
}
export function variablesFromJSON(
  jsonString: string,
): SafeParseResult<Variables, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Variables$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Variables' from JSON`,
  );
}

/** @internal */
export const OpenAIResponsesPrompt$inboundSchema: z.ZodType<OpenAIResponsesPrompt, unknown> =
  z.object({
    id: z.string(),
    variables: z
      .nullable(
        z.record(
          z.string(),
          z.union([
            ResponseInputText$inboundSchema,
            ResponseInputImage$inboundSchema,
            ResponseInputFile$inboundSchema,
            z.string(),
          ]),
        ),
      )
      .optional(),
  });
/** @internal */
export type OpenAIResponsesPrompt$Outbound = {
  id: string;
  variables?:
    | {
        [k: string]:
          | ResponseInputText$Outbound
          | ResponseInputImage$Outbound
          | ResponseInputFile$Outbound
          | string;
      }
    | null
    | undefined;
};

/** @internal */
export const OpenAIResponsesPrompt$outboundSchema: z.ZodType<
  OpenAIResponsesPrompt$Outbound,
  OpenAIResponsesPrompt
> = z.object({
  id: z.string(),
  variables: z
    .nullable(
      z.record(
        z.string(),
        z.union([
          ResponseInputText$outboundSchema,
          ResponseInputImage$outboundSchema,
          ResponseInputFile$outboundSchema,
          z.string(),
        ]),
      ),
    )
    .optional(),
});

export function openAIResponsesPromptToJSON(openAIResponsesPrompt: OpenAIResponsesPrompt): string {
  return JSON.stringify(OpenAIResponsesPrompt$outboundSchema.parse(openAIResponsesPrompt));
}
export function openAIResponsesPromptFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponsesPrompt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenAIResponsesPrompt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponsesPrompt' from JSON`,
  );
}
