/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const OpenResponsesReasoningDeltaEventType = {
  ResponseReasoningTextDelta: "response.reasoning_text.delta",
} as const;
export type OpenResponsesReasoningDeltaEventType = ClosedEnum<
  typeof OpenResponsesReasoningDeltaEventType
>;

/**
 * Event emitted when reasoning text delta is streamed
 */
export type OpenResponsesReasoningDeltaEvent = {
  type: OpenResponsesReasoningDeltaEventType;
  outputIndex: number;
  itemId: string;
  contentIndex: number;
  delta: string;
  sequenceNumber: number;
};

/** @internal */
export const OpenResponsesReasoningDeltaEventType$inboundSchema: z.ZodEnum<
  typeof OpenResponsesReasoningDeltaEventType
> = z.enum(OpenResponsesReasoningDeltaEventType);

/** @internal */
export const OpenResponsesReasoningDeltaEvent$inboundSchema: z.ZodType<
  OpenResponsesReasoningDeltaEvent,
  unknown
> = z.object({
  type: OpenResponsesReasoningDeltaEventType$inboundSchema,
  output_index: z.number(),
  item_id: z.string(),
  content_index: z.number(),
  delta: z.string(),
  sequence_number: z.number(),
}).transform((v) => {
  return remap$(v, {
    "output_index": "outputIndex",
    "item_id": "itemId",
    "content_index": "contentIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function openResponsesReasoningDeltaEventFromJSON(
  jsonString: string,
): SafeParseResult<OpenResponsesReasoningDeltaEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenResponsesReasoningDeltaEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenResponsesReasoningDeltaEvent' from JSON`,
  );
}
