/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 66f4fffdcaca
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ToolCallStatus,
  ToolCallStatus$inboundSchema,
  ToolCallStatus$outboundSchema,
} from "./toolcallstatus.js";

export const OutputFilesServerToolItemType = {
  OpenrouterFiles: "openrouter:files",
} as const;
export type OutputFilesServerToolItemType = ClosedEnum<
  typeof OutputFilesServerToolItemType
>;

/**
 * An openrouter:files server tool output item
 */
export type OutputFilesServerToolItem = {
  /**
   * Error message when the file operation failed.
   */
  error?: string | undefined;
  /**
   * The target file id supplied in the tool-call arguments.
   */
  fileId?: string | undefined;
  /**
   * The target filename supplied in the tool-call arguments.
   */
  filename?: string | undefined;
  id?: string | undefined;
  /**
   * The file operation performed (list, read, write, or edit).
   */
  operation?: string | undefined;
  /**
   * JSON-serialized result of the file operation.
   */
  result?: string | undefined;
  status: ToolCallStatus;
  type: OutputFilesServerToolItemType;
};

/** @internal */
export const OutputFilesServerToolItemType$inboundSchema: z.ZodEnum<
  typeof OutputFilesServerToolItemType
> = z.enum(OutputFilesServerToolItemType);
/** @internal */
export const OutputFilesServerToolItemType$outboundSchema: z.ZodEnum<
  typeof OutputFilesServerToolItemType
> = OutputFilesServerToolItemType$inboundSchema;

/** @internal */
export const OutputFilesServerToolItem$inboundSchema: z.ZodType<
  OutputFilesServerToolItem,
  unknown
> = z.object({
  error: z.string().optional(),
  file_id: z.string().optional(),
  filename: z.string().optional(),
  id: z.string().optional(),
  operation: z.string().optional(),
  result: z.string().optional(),
  status: ToolCallStatus$inboundSchema,
  type: OutputFilesServerToolItemType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "file_id": "fileId",
  });
});
/** @internal */
export type OutputFilesServerToolItem$Outbound = {
  error?: string | undefined;
  file_id?: string | undefined;
  filename?: string | undefined;
  id?: string | undefined;
  operation?: string | undefined;
  result?: string | undefined;
  status: string;
  type: string;
};

/** @internal */
export const OutputFilesServerToolItem$outboundSchema: z.ZodType<
  OutputFilesServerToolItem$Outbound,
  OutputFilesServerToolItem
> = z.object({
  error: z.string().optional(),
  fileId: z.string().optional(),
  filename: z.string().optional(),
  id: z.string().optional(),
  operation: z.string().optional(),
  result: z.string().optional(),
  status: ToolCallStatus$outboundSchema,
  type: OutputFilesServerToolItemType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
  });
});

export function outputFilesServerToolItemToJSON(
  outputFilesServerToolItem: OutputFilesServerToolItem,
): string {
  return JSON.stringify(
    OutputFilesServerToolItem$outboundSchema.parse(outputFilesServerToolItem),
  );
}
export function outputFilesServerToolItemFromJSON(
  jsonString: string,
): SafeParseResult<OutputFilesServerToolItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputFilesServerToolItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputFilesServerToolItem' from JSON`,
  );
}
