/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9c3ac6a7a9ad
 */

import type { ClosedEnum } from '../types/enums.js';
import type { Result as SafeParseResult } from '../types/fp.js';
import type { SDKValidationError } from './errors/sdkvalidationerror.js';
import type { ImageGenerationStatus } from './imagegenerationstatus.js';

import * as z from 'zod/v4';
import { safeParse } from '../lib/schemas.js';
import { ImageGenerationStatus$inboundSchema } from './imagegenerationstatus.js';

export const OutputItemImageGenerationCallType = {
  ImageGenerationCall: 'image_generation_call',
} as const;
export type OutputItemImageGenerationCallType = ClosedEnum<
  typeof OutputItemImageGenerationCallType
>;

export type OutputItemImageGenerationCall = {
  type: OutputItemImageGenerationCallType;
  id: string;
  result: string | null;
  status: ImageGenerationStatus;
};

/** @internal */
export const OutputItemImageGenerationCallType$inboundSchema: z.ZodEnum<
  typeof OutputItemImageGenerationCallType
> = z.enum(OutputItemImageGenerationCallType);

/** @internal */
export const OutputItemImageGenerationCall$inboundSchema: z.ZodType<
  OutputItemImageGenerationCall,
  unknown
> = z.object({
  type: OutputItemImageGenerationCallType$inboundSchema,
  id: z.string(),
  result: z.nullable(z.string()).default(null),
  status: ImageGenerationStatus$inboundSchema,
});

export function outputItemImageGenerationCallFromJSON(
  jsonString: string,
): SafeParseResult<OutputItemImageGenerationCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputItemImageGenerationCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputItemImageGenerationCall' from JSON`,
  );
}
