/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dabc92a5609a
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Related API endpoints and resources for a private model.
 */
export type PrivateModelLinks = {
  /**
   * URL for the public model endpoints API. Null for private model responses until a private endpoints route exists.
   */
  details: string | null;
};

/** @internal */
export const PrivateModelLinks$inboundSchema: z.ZodType<
  PrivateModelLinks,
  unknown
> = z.object({
  details: z.nullable(z.string()),
});

export function privateModelLinksFromJSON(
  jsonString: string,
): SafeParseResult<PrivateModelLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrivateModelLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrivateModelLinks' from JSON`,
  );
}
