/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 379f1256314f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { ApiErrorType, ApiErrorType$inboundSchema } from "./apierrortype.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ProviderOverloadedResponseErrorDataMetadata = {
  /**
   * Canonical OpenRouter error type, stable across all API formats
   */
  errorType?: ApiErrorType | undefined;
  additionalProperties?: { [k: string]: any | null } | undefined;
};

/**
 * Error data for ProviderOverloadedResponse
 */
export type ProviderOverloadedResponseErrorData = {
  code: number;
  message: string;
  metadata?: ProviderOverloadedResponseErrorDataMetadata | null | undefined;
};

/** @internal */
export const ProviderOverloadedResponseErrorDataMetadata$inboundSchema:
  z.ZodType<ProviderOverloadedResponseErrorDataMetadata, unknown> =
    collectExtraKeys$(
      z.object({
        error_type: ApiErrorType$inboundSchema.optional(),
      }).catchall(z.any()),
      "additionalProperties",
      true,
    ).transform((v) => {
      return remap$(v, {
        "error_type": "errorType",
      });
    });

export function providerOverloadedResponseErrorDataMetadataFromJSON(
  jsonString: string,
): SafeParseResult<
  ProviderOverloadedResponseErrorDataMetadata,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ProviderOverloadedResponseErrorDataMetadata$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ProviderOverloadedResponseErrorDataMetadata' from JSON`,
  );
}

/** @internal */
export const ProviderOverloadedResponseErrorData$inboundSchema: z.ZodType<
  ProviderOverloadedResponseErrorData,
  unknown
> = z.object({
  code: z.int(),
  message: z.string(),
  metadata: z.nullable(
    z.lazy(() => ProviderOverloadedResponseErrorDataMetadata$inboundSchema),
  ).optional(),
});

export function providerOverloadedResponseErrorDataFromJSON(
  jsonString: string,
): SafeParseResult<ProviderOverloadedResponseErrorData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ProviderOverloadedResponseErrorData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProviderOverloadedResponseErrorData' from JSON`,
  );
}
