/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 396ce3186017
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  EndpointStatus,
  EndpointStatus$inboundSchema,
} from "./endpointstatus.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Parameter, Parameter$inboundSchema } from "./parameter.js";
import {
  PercentileStats,
  PercentileStats$inboundSchema,
} from "./percentilestats.js";
import {
  PricingOverride,
  PricingOverride$inboundSchema,
} from "./pricingoverride.js";
import { ProviderName, ProviderName$inboundSchema } from "./providername.js";
import { Quantization, Quantization$inboundSchema } from "./quantization.js";
import {
  ToolChoiceSupport,
  ToolChoiceSupport$inboundSchema,
} from "./toolchoicesupport.js";

export type Embeddings = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

export type ImageGeneration = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

export type Rerank = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

export type STT = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

export type TextGeneration = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

export type TTS = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

export type Unknown = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

export type VideoGeneration = {
  latency: PercentileStats | null;
  /**
   * Total requests admitted for this workload in the window.
   */
  requestCount: number | null;
  throughput: PercentileStats | null;
};

/**
 * Endpoint performance over the last 30 minutes, keyed by the kind of request served (e.g. `text_generation`, `image_generation`). Additive to the legacy singular latency and throughput fields; image and video generation report end-to-end latency. Only visible when authenticated with an API key or cookie.
 */
export type PerfLast30mByWorkload = {
  embeddings?: Embeddings | undefined;
  imageGeneration?: ImageGeneration | undefined;
  rerank?: Rerank | undefined;
  stt?: STT | undefined;
  textGeneration?: TextGeneration | undefined;
  tts?: TTS | undefined;
  unknown?: Unknown | undefined;
  videoGeneration?: VideoGeneration | undefined;
};

export type Pricing = {
  /**
   * Price in USD per audio input token
   */
  audio?: string | undefined;
  /**
   * Price in USD per audio output token
   */
  audioOutput?: string | undefined;
  /**
   * Price in USD per token for completion (output) generation
   */
  completion: string;
  /**
   * Fractional discount applied to this endpoint's pricing; the price is multiplied by (1 - discount) (0 = no discount, 1 = free)
   */
  discount?: number | undefined;
  /**
   * Price in USD per input image
   */
  image?: string | undefined;
  /**
   * Price in USD per output image
   */
  imageOutput?: string | undefined;
  /**
   * Price in USD per image token
   */
  imageToken?: string | undefined;
  /**
   * Price in USD per cached audio input token
   */
  inputAudioCache?: string | undefined;
  /**
   * Price in USD per cached input token (read)
   */
  inputCacheRead?: string | undefined;
  /**
   * Price per cache-write token, in USD per token. For providers with multiple cache TTLs (e.g. Anthropic), this is the default (5-minute) cache-write rate.
   */
  inputCacheWrite?: string | undefined;
  /**
   * Price per 1-hour cache-write token, in USD per token. Only present for providers that price an extended (1-hour) cache TTL separately, such as Anthropic.
   */
  inputCacheWrite1h?: string | undefined;
  /**
   * Price in USD per internal reasoning token
   */
  internalReasoning?: string | undefined;
  /**
   * Conditional overrides of the base pricing (e.g. long-context or time-based pricing). An entry applies when all of its condition fields (e.g. min_prompt_tokens, or the utc_start/utc_end time window) match the request; among applicable entries, later entries win per key; price keys absent from an entry inherit the base price. The top-level pricing keys always reflect the price that applies under default conditions.
   */
  overrides?: Array<PricingOverride> | undefined;
  /**
   * Price in USD per token for prompt (input) processing
   */
  prompt: string;
  /**
   * Price in USD per request
   */
  request?: string | undefined;
  /**
   * Price in USD per web search
   */
  webSearch?: string | undefined;
};

/**
 * Information about a specific model endpoint
 */
export type PublicEndpoint = {
  contextLength: number;
  /**
   * Latency percentiles in milliseconds over the last 30 minutes. Latency measures time to first token. Only visible when authenticated with an API key or cookie; returns null for unauthenticated requests.
   */
  latencyLast30m: PercentileStats | null;
  /**
   * Maximum completion tokens for this endpoint. Input and output tokens share the context window, so the effective maximum output for a request is further limited by the context remaining after input tokens.
   */
  maxCompletionTokens: number | null;
  maxPromptTokens: number | null;
  /**
   * The unique identifier for the model (permaslug)
   */
  modelId: string;
  modelName: string;
  name: string;
  /**
   * Endpoint performance over the last 30 minutes, keyed by the kind of request served (e.g. `text_generation`, `image_generation`). Additive to the legacy singular latency and throughput fields; image and video generation report end-to-end latency. Only visible when authenticated with an API key or cookie.
   */
  perfLast30mByWorkload?: PerfLast30mByWorkload | undefined;
  pricing: Pricing;
  providerName: ProviderName;
  quantization: Quantization | null;
  status?: EndpointStatus | undefined;
  supportedParameters: Array<Parameter>;
  supportsImplicitCaching: boolean;
  /**
   * Per-variant `tool_choice` support. `tool_choice` in `supported_parameters` only says the parameter is accepted; these flags say which of its values passed testing.
   */
  supportsToolChoice: ToolChoiceSupport;
  /**
   * Whether this TTS endpoint accepts inline reference audio (`input_references`) for stateless voice cloning. Requests carrying reference audio are only routed to endpoints where this is true.
   */
  supportsVoiceCloning: boolean;
  tag: string;
  throughputLast30m: PercentileStats | null;
  /**
   * Uptime percentage over the last 1 day, calculated as successful requests / (successful + error requests) * 100. Rate-limited requests are excluded. Returns null if insufficient data.
   */
  uptimeLast1d: number | null;
  uptimeLast30m: number | null;
  /**
   * Uptime percentage over the last 5 minutes, calculated as successful requests / (successful + error requests) * 100. Rate-limited requests are excluded. Returns null if insufficient data.
   */
  uptimeLast5m: number | null;
};

/** @internal */
export const Embeddings$inboundSchema: z.ZodType<Embeddings, unknown> = z
  .object({
    latency: z.nullable(PercentileStats$inboundSchema),
    request_count: z.nullable(z.int()),
    throughput: z.nullable(PercentileStats$inboundSchema),
  }).transform((v) => {
    return remap$(v, {
      "request_count": "requestCount",
    });
  });

export function embeddingsFromJSON(
  jsonString: string,
): SafeParseResult<Embeddings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Embeddings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Embeddings' from JSON`,
  );
}

/** @internal */
export const ImageGeneration$inboundSchema: z.ZodType<
  ImageGeneration,
  unknown
> = z.object({
  latency: z.nullable(PercentileStats$inboundSchema),
  request_count: z.nullable(z.int()),
  throughput: z.nullable(PercentileStats$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "request_count": "requestCount",
  });
});

export function imageGenerationFromJSON(
  jsonString: string,
): SafeParseResult<ImageGeneration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageGeneration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageGeneration' from JSON`,
  );
}

/** @internal */
export const Rerank$inboundSchema: z.ZodType<Rerank, unknown> = z.object({
  latency: z.nullable(PercentileStats$inboundSchema),
  request_count: z.nullable(z.int()),
  throughput: z.nullable(PercentileStats$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "request_count": "requestCount",
  });
});

export function rerankFromJSON(
  jsonString: string,
): SafeParseResult<Rerank, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Rerank$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Rerank' from JSON`,
  );
}

/** @internal */
export const STT$inboundSchema: z.ZodType<STT, unknown> = z.object({
  latency: z.nullable(PercentileStats$inboundSchema),
  request_count: z.nullable(z.int()),
  throughput: z.nullable(PercentileStats$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "request_count": "requestCount",
  });
});

export function sttFromJSON(
  jsonString: string,
): SafeParseResult<STT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => STT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'STT' from JSON`,
  );
}

/** @internal */
export const TextGeneration$inboundSchema: z.ZodType<TextGeneration, unknown> =
  z.object({
    latency: z.nullable(PercentileStats$inboundSchema),
    request_count: z.nullable(z.int()),
    throughput: z.nullable(PercentileStats$inboundSchema),
  }).transform((v) => {
    return remap$(v, {
      "request_count": "requestCount",
    });
  });

export function textGenerationFromJSON(
  jsonString: string,
): SafeParseResult<TextGeneration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextGeneration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextGeneration' from JSON`,
  );
}

/** @internal */
export const TTS$inboundSchema: z.ZodType<TTS, unknown> = z.object({
  latency: z.nullable(PercentileStats$inboundSchema),
  request_count: z.nullable(z.int()),
  throughput: z.nullable(PercentileStats$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "request_count": "requestCount",
  });
});

export function ttsFromJSON(
  jsonString: string,
): SafeParseResult<TTS, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TTS$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TTS' from JSON`,
  );
}

/** @internal */
export const Unknown$inboundSchema: z.ZodType<Unknown, unknown> = z.object({
  latency: z.nullable(PercentileStats$inboundSchema),
  request_count: z.nullable(z.int()),
  throughput: z.nullable(PercentileStats$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "request_count": "requestCount",
  });
});

export function unknownFromJSON(
  jsonString: string,
): SafeParseResult<Unknown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Unknown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Unknown' from JSON`,
  );
}

/** @internal */
export const VideoGeneration$inboundSchema: z.ZodType<
  VideoGeneration,
  unknown
> = z.object({
  latency: z.nullable(PercentileStats$inboundSchema),
  request_count: z.nullable(z.int()),
  throughput: z.nullable(PercentileStats$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "request_count": "requestCount",
  });
});

export function videoGenerationFromJSON(
  jsonString: string,
): SafeParseResult<VideoGeneration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VideoGeneration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VideoGeneration' from JSON`,
  );
}

/** @internal */
export const PerfLast30mByWorkload$inboundSchema: z.ZodType<
  PerfLast30mByWorkload,
  unknown
> = z.object({
  embeddings: z.lazy(() => Embeddings$inboundSchema).optional(),
  image_generation: z.lazy(() => ImageGeneration$inboundSchema).optional(),
  rerank: z.lazy(() => Rerank$inboundSchema).optional(),
  stt: z.lazy(() => STT$inboundSchema).optional(),
  text_generation: z.lazy(() => TextGeneration$inboundSchema).optional(),
  tts: z.lazy(() => TTS$inboundSchema).optional(),
  unknown: z.lazy(() => Unknown$inboundSchema).optional(),
  video_generation: z.lazy(() => VideoGeneration$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "image_generation": "imageGeneration",
    "text_generation": "textGeneration",
    "video_generation": "videoGeneration",
  });
});

export function perfLast30mByWorkloadFromJSON(
  jsonString: string,
): SafeParseResult<PerfLast30mByWorkload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PerfLast30mByWorkload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PerfLast30mByWorkload' from JSON`,
  );
}

/** @internal */
export const Pricing$inboundSchema: z.ZodType<Pricing, unknown> = z.object({
  audio: z.string().optional(),
  audio_output: z.string().optional(),
  completion: z.string(),
  discount: z.number().optional(),
  image: z.string().optional(),
  image_output: z.string().optional(),
  image_token: z.string().optional(),
  input_audio_cache: z.string().optional(),
  input_cache_read: z.string().optional(),
  input_cache_write: z.string().optional(),
  input_cache_write_1h: z.string().optional(),
  internal_reasoning: z.string().optional(),
  overrides: z.array(PricingOverride$inboundSchema).optional(),
  prompt: z.string(),
  request: z.string().optional(),
  web_search: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "audio_output": "audioOutput",
    "image_output": "imageOutput",
    "image_token": "imageToken",
    "input_audio_cache": "inputAudioCache",
    "input_cache_read": "inputCacheRead",
    "input_cache_write": "inputCacheWrite",
    "input_cache_write_1h": "inputCacheWrite1h",
    "internal_reasoning": "internalReasoning",
    "web_search": "webSearch",
  });
});

export function pricingFromJSON(
  jsonString: string,
): SafeParseResult<Pricing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pricing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pricing' from JSON`,
  );
}

/** @internal */
export const PublicEndpoint$inboundSchema: z.ZodType<PublicEndpoint, unknown> =
  z.object({
    context_length: z.int(),
    latency_last_30m: z.nullable(PercentileStats$inboundSchema),
    max_completion_tokens: z.nullable(z.int()),
    max_prompt_tokens: z.nullable(z.int()),
    model_id: z.string(),
    model_name: z.string(),
    name: z.string(),
    perf_last_30m_by_workload: z.lazy(() => PerfLast30mByWorkload$inboundSchema)
      .optional(),
    pricing: z.lazy(() => Pricing$inboundSchema),
    provider_name: ProviderName$inboundSchema,
    quantization: z.nullable(Quantization$inboundSchema),
    status: EndpointStatus$inboundSchema.optional(),
    supported_parameters: z.array(Parameter$inboundSchema),
    supports_implicit_caching: z.boolean(),
    supports_tool_choice: ToolChoiceSupport$inboundSchema,
    supports_voice_cloning: z.boolean().default(false),
    tag: z.string(),
    throughput_last_30m: z.nullable(PercentileStats$inboundSchema),
    uptime_last_1d: z.nullable(z.number()),
    uptime_last_30m: z.nullable(z.number()),
    uptime_last_5m: z.nullable(z.number()),
  }).transform((v) => {
    return remap$(v, {
      "context_length": "contextLength",
      "latency_last_30m": "latencyLast30m",
      "max_completion_tokens": "maxCompletionTokens",
      "max_prompt_tokens": "maxPromptTokens",
      "model_id": "modelId",
      "model_name": "modelName",
      "perf_last_30m_by_workload": "perfLast30mByWorkload",
      "provider_name": "providerName",
      "supported_parameters": "supportedParameters",
      "supports_implicit_caching": "supportsImplicitCaching",
      "supports_tool_choice": "supportsToolChoice",
      "supports_voice_cloning": "supportsVoiceCloning",
      "throughput_last_30m": "throughputLast30m",
      "uptime_last_1d": "uptimeLast1d",
      "uptime_last_30m": "uptimeLast30m",
      "uptime_last_5m": "uptimeLast5m",
    });
  });

export function publicEndpointFromJSON(
  jsonString: string,
): SafeParseResult<PublicEndpoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicEndpoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicEndpoint' from JSON`,
  );
}
