/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0e129c34b701
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Event emitted when reasoning text delta is streamed
 */
export type ReasoningDeltaEvent = {
  type: "response.reasoning_text.delta";
  outputIndex: number;
  itemId: string;
  contentIndex: number;
  delta: string;
  sequenceNumber: number;
};

/** @internal */
export const ReasoningDeltaEvent$inboundSchema: z.ZodType<
  ReasoningDeltaEvent,
  unknown
> = z.object({
  type: z.literal("response.reasoning_text.delta"),
  output_index: z.number(),
  item_id: z.string(),
  content_index: z.number(),
  delta: z.string(),
  sequence_number: z.number(),
}).transform((v) => {
  return remap$(v, {
    "output_index": "outputIndex",
    "item_id": "itemId",
    "content_index": "contentIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function reasoningDeltaEventFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningDeltaEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningDeltaEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningDeltaEvent' from JSON`,
  );
}
