/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Event emitted when refusal streaming is complete
 */
export type RefusalDoneEvent = {
  type: "response.refusal.done";
  outputIndex: number;
  itemId: string;
  contentIndex: number;
  refusal: string;
  sequenceNumber: number;
};

/** @internal */
export const RefusalDoneEvent$inboundSchema: z.ZodType<
  RefusalDoneEvent,
  unknown
> = z.object({
  type: z.literal("response.refusal.done"),
  output_index: z.number(),
  item_id: z.string(),
  content_index: z.number(),
  refusal: z.string(),
  sequence_number: z.number(),
}).transform((v) => {
  return remap$(v, {
    "output_index": "outputIndex",
    "item_id": "itemId",
    "content_index": "contentIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function refusalDoneEventFromJSON(
  jsonString: string,
): SafeParseResult<RefusalDoneEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefusalDoneEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefusalDoneEvent' from JSON`,
  );
}
