/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ResponseTextVerbosity = {
  High: "high",
  Low: "low",
  Medium: "medium",
} as const;
export type ResponseTextVerbosity = ClosedEnum<typeof ResponseTextVerbosity>;

/** @internal */
export const ResponseTextVerbosity$inboundSchema: z.ZodNativeEnum<
  typeof ResponseTextVerbosity
> = z.nativeEnum(ResponseTextVerbosity);

/** @internal */
export const ResponseTextVerbosity$outboundSchema: z.ZodNativeEnum<
  typeof ResponseTextVerbosity
> = ResponseTextVerbosity$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseTextVerbosity$ {
  /** @deprecated use `ResponseTextVerbosity$inboundSchema` instead. */
  export const inboundSchema = ResponseTextVerbosity$inboundSchema;
  /** @deprecated use `ResponseTextVerbosity$outboundSchema` instead. */
  export const outboundSchema = ResponseTextVerbosity$outboundSchema;
}
