/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ResponsesImageGenerationCall,
  ResponsesImageGenerationCall$inboundSchema,
  ResponsesImageGenerationCall$Outbound,
  ResponsesImageGenerationCall$outboundSchema,
} from "./responsesimagegenerationcall.js";
import {
  ResponsesOutputItemFileSearchCall,
  ResponsesOutputItemFileSearchCall$inboundSchema,
  ResponsesOutputItemFileSearchCall$Outbound,
  ResponsesOutputItemFileSearchCall$outboundSchema,
} from "./responsesoutputitemfilesearchcall.js";
import {
  ResponsesOutputItemFunctionCall,
  ResponsesOutputItemFunctionCall$inboundSchema,
  ResponsesOutputItemFunctionCall$Outbound,
  ResponsesOutputItemFunctionCall$outboundSchema,
} from "./responsesoutputitemfunctioncall.js";
import {
  ResponsesOutputItemReasoning,
  ResponsesOutputItemReasoning$inboundSchema,
  ResponsesOutputItemReasoning$Outbound,
  ResponsesOutputItemReasoning$outboundSchema,
} from "./responsesoutputitemreasoning.js";
import {
  ResponsesOutputMessage,
  ResponsesOutputMessage$inboundSchema,
  ResponsesOutputMessage$Outbound,
  ResponsesOutputMessage$outboundSchema,
} from "./responsesoutputmessage.js";
import {
  ResponsesWebSearchCallOutput,
  ResponsesWebSearchCallOutput$inboundSchema,
  ResponsesWebSearchCallOutput$Outbound,
  ResponsesWebSearchCallOutput$outboundSchema,
} from "./responseswebsearchcalloutput.js";

/**
 * An output item from the response
 */
export type ResponsesOutputItem =
  | ResponsesOutputMessage
  | ResponsesOutputItemFunctionCall
  | ResponsesOutputItemFileSearchCall
  | ResponsesImageGenerationCall
  | ResponsesWebSearchCallOutput
  | ResponsesOutputItemReasoning;

/** @internal */
export const ResponsesOutputItem$inboundSchema: z.ZodType<
  ResponsesOutputItem,
  unknown
> = z.union([
  ResponsesOutputMessage$inboundSchema,
  ResponsesOutputItemFunctionCall$inboundSchema,
  ResponsesOutputItemFileSearchCall$inboundSchema,
  ResponsesImageGenerationCall$inboundSchema,
  ResponsesWebSearchCallOutput$inboundSchema,
  ResponsesOutputItemReasoning$inboundSchema,
]);

/** @internal */
export type ResponsesOutputItem$Outbound =
  | ResponsesOutputMessage$Outbound
  | ResponsesOutputItemFunctionCall$Outbound
  | ResponsesOutputItemFileSearchCall$Outbound
  | ResponsesImageGenerationCall$Outbound
  | ResponsesWebSearchCallOutput$Outbound
  | ResponsesOutputItemReasoning$Outbound;

/** @internal */
export const ResponsesOutputItem$outboundSchema: z.ZodType<
  ResponsesOutputItem$Outbound,
  ResponsesOutputItem
> = z.union([
  ResponsesOutputMessage$outboundSchema,
  ResponsesOutputItemFunctionCall$outboundSchema,
  ResponsesOutputItemFileSearchCall$outboundSchema,
  ResponsesImageGenerationCall$outboundSchema,
  ResponsesWebSearchCallOutput$outboundSchema,
  ResponsesOutputItemReasoning$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponsesOutputItem$ {
  /** @deprecated use `ResponsesOutputItem$inboundSchema` instead. */
  export const inboundSchema = ResponsesOutputItem$inboundSchema;
  /** @deprecated use `ResponsesOutputItem$outboundSchema` instead. */
  export const outboundSchema = ResponsesOutputItem$outboundSchema;
  /** @deprecated use `ResponsesOutputItem$Outbound` instead. */
  export type Outbound = ResponsesOutputItem$Outbound;
}

export function responsesOutputItemToJSON(
  responsesOutputItem: ResponsesOutputItem,
): string {
  return JSON.stringify(
    ResponsesOutputItem$outboundSchema.parse(responsesOutputItem),
  );
}

export function responsesOutputItemFromJSON(
  jsonString: string,
): SafeParseResult<ResponsesOutputItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponsesOutputItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponsesOutputItem' from JSON`,
  );
}
