/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ResponseInputAudioFormat = {
  Mp3: "mp3",
  Wav: "wav",
} as const;
export type ResponseInputAudioFormat = OpenEnum<
  typeof ResponseInputAudioFormat
>;

export type ResponseInputAudioInputAudio = {
  data: string;
  format: ResponseInputAudioFormat;
};

/**
 * Audio input content item
 */
export type ResponseInputAudio = {
  type: "input_audio";
  inputAudio: ResponseInputAudioInputAudio;
};

/** @internal */
export const ResponseInputAudioFormat$inboundSchema: z.ZodType<
  ResponseInputAudioFormat,
  unknown
> = openEnums.inboundSchema(ResponseInputAudioFormat);
/** @internal */
export const ResponseInputAudioFormat$outboundSchema: z.ZodType<
  string,
  ResponseInputAudioFormat
> = openEnums.outboundSchema(ResponseInputAudioFormat);

/** @internal */
export const ResponseInputAudioInputAudio$inboundSchema: z.ZodType<
  ResponseInputAudioInputAudio,
  unknown
> = z.object({
  data: z.string(),
  format: ResponseInputAudioFormat$inboundSchema,
});
/** @internal */
export type ResponseInputAudioInputAudio$Outbound = {
  data: string;
  format: string;
};

/** @internal */
export const ResponseInputAudioInputAudio$outboundSchema: z.ZodType<
  ResponseInputAudioInputAudio$Outbound,
  ResponseInputAudioInputAudio
> = z.object({
  data: z.string(),
  format: ResponseInputAudioFormat$outboundSchema,
});

export function responseInputAudioInputAudioToJSON(
  responseInputAudioInputAudio: ResponseInputAudioInputAudio,
): string {
  return JSON.stringify(
    ResponseInputAudioInputAudio$outboundSchema.parse(
      responseInputAudioInputAudio,
    ),
  );
}
export function responseInputAudioInputAudioFromJSON(
  jsonString: string,
): SafeParseResult<ResponseInputAudioInputAudio, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseInputAudioInputAudio$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseInputAudioInputAudio' from JSON`,
  );
}

/** @internal */
export const ResponseInputAudio$inboundSchema: z.ZodType<
  ResponseInputAudio,
  unknown
> = z.object({
  type: z.literal("input_audio"),
  input_audio: z.lazy(() => ResponseInputAudioInputAudio$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "input_audio": "inputAudio",
  });
});
/** @internal */
export type ResponseInputAudio$Outbound = {
  type: "input_audio";
  input_audio: ResponseInputAudioInputAudio$Outbound;
};

/** @internal */
export const ResponseInputAudio$outboundSchema: z.ZodType<
  ResponseInputAudio$Outbound,
  ResponseInputAudio
> = z.object({
  type: z.literal("input_audio"),
  inputAudio: z.lazy(() => ResponseInputAudioInputAudio$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    inputAudio: "input_audio",
  });
});

export function responseInputAudioToJSON(
  responseInputAudio: ResponseInputAudio,
): string {
  return JSON.stringify(
    ResponseInputAudio$outboundSchema.parse(responseInputAudio),
  );
}
export function responseInputAudioFromJSON(
  jsonString: string,
): SafeParseResult<ResponseInputAudio, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseInputAudio$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseInputAudio' from JSON`,
  );
}
