/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../types/enums.js";

export const ResponseReasoningSummaryMode = {
  Auto: "auto",
  Concise: "concise",
  Detailed: "detailed",
} as const;
export type ResponseReasoningSummaryMode = OpenEnum<
  typeof ResponseReasoningSummaryMode
>;

/** @internal */
export const ResponseReasoningSummaryMode$inboundSchema: z.ZodType<
  ResponseReasoningSummaryMode,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(ResponseReasoningSummaryMode),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const ResponseReasoningSummaryMode$outboundSchema: z.ZodType<
  ResponseReasoningSummaryMode,
  z.ZodTypeDef,
  ResponseReasoningSummaryMode
> = z.union([
  z.nativeEnum(ResponseReasoningSummaryMode),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseReasoningSummaryMode$ {
  /** @deprecated use `ResponseReasoningSummaryMode$inboundSchema` instead. */
  export const inboundSchema = ResponseReasoningSummaryMode$inboundSchema;
  /** @deprecated use `ResponseReasoningSummaryMode$outboundSchema` instead. */
  export const outboundSchema = ResponseReasoningSummaryMode$outboundSchema;
}
