/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d90c6c784ca5
 */

import * as z from "zod/v4";

export type Security = {
  apiKey?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  apiKey?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<Security$Outbound, Security> = z
  .object({
    apiKey: z.string().optional(),
  });

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
