/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3a84d88babcc
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Endpoints whose provider runs this tool itself during inference. Zero for tools no provider runs natively.
 */
export type ServerToolNativeSupport = {
  endpointCount: number;
  modelCount: number;
};

/** @internal */
export const ServerToolNativeSupport$inboundSchema: z.ZodType<
  ServerToolNativeSupport,
  unknown
> = z.object({
  endpoint_count: z.int(),
  model_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "endpoint_count": "endpointCount",
    "model_count": "modelCount",
  });
});

export function serverToolNativeSupportFromJSON(
  jsonString: string,
): SafeParseResult<ServerToolNativeSupport, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerToolNativeSupport$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerToolNativeSupport' from JSON`,
  );
}
