/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7fbbfc5a6ebc
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ToolCallStatus,
  ToolCallStatus$inboundSchema,
  ToolCallStatus$outboundSchema,
} from "./toolcallstatus.js";

export type ShellCallOutputItemOutput = {
  content?: string | null | undefined;
  exitCode?: number | null | undefined;
  type: string;
  additionalProperties?: { [k: string]: any } | undefined;
};

export const ShellCallOutputItemType = {
  ShellCallOutput: "shell_call_output",
} as const;
export type ShellCallOutputItemType = ClosedEnum<
  typeof ShellCallOutputItemType
>;

/**
 * Output from a shell command execution (newer variant)
 */
export type ShellCallOutputItem = {
  callId: string;
  id?: string | null | undefined;
  maxOutputLength?: number | null | undefined;
  output: Array<ShellCallOutputItemOutput>;
  status?: ToolCallStatus | null | undefined;
  type: ShellCallOutputItemType;
};

/** @internal */
export const ShellCallOutputItemOutput$inboundSchema: z.ZodType<
  ShellCallOutputItemOutput,
  unknown
> = collectExtraKeys$(
  z.object({
    content: z.nullable(z.string()).optional(),
    exit_code: z.nullable(z.int()).optional(),
    type: z.string(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "exit_code": "exitCode",
  });
});
/** @internal */
export type ShellCallOutputItemOutput$Outbound = {
  content?: string | null | undefined;
  exit_code?: number | null | undefined;
  type: string;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ShellCallOutputItemOutput$outboundSchema: z.ZodType<
  ShellCallOutputItemOutput$Outbound,
  ShellCallOutputItemOutput
> = z.object({
  content: z.nullable(z.string()).optional(),
  exitCode: z.nullable(z.int()).optional(),
  type: z.string(),
  additionalProperties: z.record(z.string(), z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      exitCode: "exit_code",
      additionalProperties: null,
    }),
  };
});

export function shellCallOutputItemOutputToJSON(
  shellCallOutputItemOutput: ShellCallOutputItemOutput,
): string {
  return JSON.stringify(
    ShellCallOutputItemOutput$outboundSchema.parse(shellCallOutputItemOutput),
  );
}
export function shellCallOutputItemOutputFromJSON(
  jsonString: string,
): SafeParseResult<ShellCallOutputItemOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShellCallOutputItemOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShellCallOutputItemOutput' from JSON`,
  );
}

/** @internal */
export const ShellCallOutputItemType$inboundSchema: z.ZodEnum<
  typeof ShellCallOutputItemType
> = z.enum(ShellCallOutputItemType);
/** @internal */
export const ShellCallOutputItemType$outboundSchema: z.ZodEnum<
  typeof ShellCallOutputItemType
> = ShellCallOutputItemType$inboundSchema;

/** @internal */
export const ShellCallOutputItem$inboundSchema: z.ZodType<
  ShellCallOutputItem,
  unknown
> = z.object({
  call_id: z.string(),
  id: z.nullable(z.string()).optional(),
  max_output_length: z.nullable(z.int()).optional(),
  output: z.array(z.lazy(() => ShellCallOutputItemOutput$inboundSchema)),
  status: z.nullable(ToolCallStatus$inboundSchema).optional(),
  type: ShellCallOutputItemType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "call_id": "callId",
    "max_output_length": "maxOutputLength",
  });
});
/** @internal */
export type ShellCallOutputItem$Outbound = {
  call_id: string;
  id?: string | null | undefined;
  max_output_length?: number | null | undefined;
  output: Array<ShellCallOutputItemOutput$Outbound>;
  status?: string | null | undefined;
  type: string;
};

/** @internal */
export const ShellCallOutputItem$outboundSchema: z.ZodType<
  ShellCallOutputItem$Outbound,
  ShellCallOutputItem
> = z.object({
  callId: z.string(),
  id: z.nullable(z.string()).optional(),
  maxOutputLength: z.nullable(z.int()).optional(),
  output: z.array(z.lazy(() => ShellCallOutputItemOutput$outboundSchema)),
  status: z.nullable(ToolCallStatus$outboundSchema).optional(),
  type: ShellCallOutputItemType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    callId: "call_id",
    maxOutputLength: "max_output_length",
  });
});

export function shellCallOutputItemToJSON(
  shellCallOutputItem: ShellCallOutputItem,
): string {
  return JSON.stringify(
    ShellCallOutputItem$outboundSchema.parse(shellCallOutputItem),
  );
}
export function shellCallOutputItemFromJSON(
  jsonString: string,
): SafeParseResult<ShellCallOutputItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShellCallOutputItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShellCallOutputItem' from JSON`,
  );
}
