/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 16760a92290d
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SubmitGenerationFeedbackResponseData = {
  /**
   * Whether the feedback was recorded
   */
  success: true;
};

/**
 * Confirmation that the feedback was recorded
 */
export type SubmitGenerationFeedbackResponse = {
  data: SubmitGenerationFeedbackResponseData;
};

/** @internal */
export const SubmitGenerationFeedbackResponseData$inboundSchema: z.ZodType<
  SubmitGenerationFeedbackResponseData,
  unknown
> = z.object({
  success: z.literal(true),
});

export function submitGenerationFeedbackResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<SubmitGenerationFeedbackResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SubmitGenerationFeedbackResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubmitGenerationFeedbackResponseData' from JSON`,
  );
}

/** @internal */
export const SubmitGenerationFeedbackResponse$inboundSchema: z.ZodType<
  SubmitGenerationFeedbackResponse,
  unknown
> = z.object({
  data: z.lazy(() => SubmitGenerationFeedbackResponseData$inboundSchema),
});

export function submitGenerationFeedbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubmitGenerationFeedbackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubmitGenerationFeedbackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubmitGenerationFeedbackResponse' from JSON`,
  );
}
