/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4b11e81b145
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * How the engine treats unknown request fields. `strict` rejects them; `meta-only` allows opaque metadata only.
 */
export const ToolEngineExtensionPolicy = {
  Strict: "strict",
  MetaOnly: "meta-only",
} as const;
/**
 * How the engine treats unknown request fields. `strict` rejects them; `meta-only` allows opaque metadata only.
 */
export type ToolEngineExtensionPolicy = OpenEnum<
  typeof ToolEngineExtensionPolicy
>;

/** @internal */
export const ToolEngineExtensionPolicy$outboundSchema: z.ZodType<
  string,
  ToolEngineExtensionPolicy
> = openEnums.outboundSchema(ToolEngineExtensionPolicy);
