/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Error data for UnprocessableEntityResponse
 */
export type UnprocessableEntityResponseErrorData = {
  code: number;
  message: string;
  metadata?: { [k: string]: any | null } | null | undefined;
};

/** @internal */
export const UnprocessableEntityResponseErrorData$inboundSchema: z.ZodType<
  UnprocessableEntityResponseErrorData,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  metadata: z.nullable(z.record(z.string(), z.nullable(z.any()))).optional(),
});

/** @internal */
export type UnprocessableEntityResponseErrorData$Outbound = {
  code: number;
  message: string;
  metadata?: { [k: string]: any | null } | null | undefined;
};

/** @internal */
export const UnprocessableEntityResponseErrorData$outboundSchema: z.ZodType<
  UnprocessableEntityResponseErrorData$Outbound,
  UnprocessableEntityResponseErrorData
> = z.object({
  code: z.number().int(),
  message: z.string(),
  metadata: z.nullable(z.record(z.string(), z.nullable(z.any()))).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnprocessableEntityResponseErrorData$ {
  /** @deprecated use `UnprocessableEntityResponseErrorData$inboundSchema` instead. */
  export const inboundSchema =
    UnprocessableEntityResponseErrorData$inboundSchema;
  /** @deprecated use `UnprocessableEntityResponseErrorData$outboundSchema` instead. */
  export const outboundSchema =
    UnprocessableEntityResponseErrorData$outboundSchema;
  /** @deprecated use `UnprocessableEntityResponseErrorData$Outbound` instead. */
  export type Outbound = UnprocessableEntityResponseErrorData$Outbound;
}

export function unprocessableEntityResponseErrorDataToJSON(
  unprocessableEntityResponseErrorData: UnprocessableEntityResponseErrorData,
): string {
  return JSON.stringify(
    UnprocessableEntityResponseErrorData$outboundSchema.parse(
      unprocessableEntityResponseErrorData,
    ),
  );
}

export function unprocessableEntityResponseErrorDataFromJSON(
  jsonString: string,
): SafeParseResult<UnprocessableEntityResponseErrorData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UnprocessableEntityResponseErrorData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnprocessableEntityResponseErrorData' from JSON`,
  );
}
