/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 005e2873e353
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AgentMcpServer,
  AgentMcpServer$Outbound,
  AgentMcpServer$outboundSchema,
} from "./agentmcpserver.js";

export type UpdateAgentContextRequest = {
  /**
   * Replacement set of knowledge entries.
   */
  knowledge?: Array<string> | undefined;
  /**
   * Replacement set of MCP server URLs.
   */
  mcpServers?: Array<AgentMcpServer> | undefined;
  /**
   * Updated human-readable name.
   */
  name?: string | undefined;
};

/** @internal */
export type UpdateAgentContextRequest$Outbound = {
  knowledge?: Array<string> | undefined;
  mcp_servers?: Array<AgentMcpServer$Outbound> | undefined;
  name?: string | undefined;
};

/** @internal */
export const UpdateAgentContextRequest$outboundSchema: z.ZodType<
  UpdateAgentContextRequest$Outbound,
  UpdateAgentContextRequest
> = z.object({
  knowledge: z.array(z.string()).optional(),
  mcpServers: z.array(AgentMcpServer$outboundSchema).optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    mcpServers: "mcp_servers",
  });
});

export function updateAgentContextRequestToJSON(
  updateAgentContextRequest: UpdateAgentContextRequest,
): string {
  return JSON.stringify(
    UpdateAgentContextRequest$outboundSchema.parse(updateAgentContextRequest),
  );
}
