/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 173c7e014c24
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

export type WebFetchServerToolOpenRouterParameters = {
  /**
   * Maximum content length in approximate tokens. Content exceeding this limit is truncated.
   */
  maxContentTokens?: number | undefined;
  /**
   * Maximum number of web fetches per request. Once exceeded, the tool returns an error.
   */
  maxUses?: number | undefined;
};

/**
 * OpenRouter built-in server tool: fetches full content from a URL (web page or PDF)
 */
export type WebFetchServerToolOpenRouter = {
  parameters?: WebFetchServerToolOpenRouterParameters | undefined;
  type: "openrouter:web_fetch";
};

/** @internal */
export type WebFetchServerToolOpenRouterParameters$Outbound = {
  max_content_tokens?: number | undefined;
  max_uses?: number | undefined;
};

/** @internal */
export const WebFetchServerToolOpenRouterParameters$outboundSchema: z.ZodType<
  WebFetchServerToolOpenRouterParameters$Outbound,
  WebFetchServerToolOpenRouterParameters
> = z.object({
  maxContentTokens: z.int().optional(),
  maxUses: z.int().optional(),
}).transform((v) => {
  return remap$(v, {
    maxContentTokens: "max_content_tokens",
    maxUses: "max_uses",
  });
});

export function webFetchServerToolOpenRouterParametersToJSON(
  webFetchServerToolOpenRouterParameters:
    WebFetchServerToolOpenRouterParameters,
): string {
  return JSON.stringify(
    WebFetchServerToolOpenRouterParameters$outboundSchema.parse(
      webFetchServerToolOpenRouterParameters,
    ),
  );
}

/** @internal */
export type WebFetchServerToolOpenRouter$Outbound = {
  parameters?: WebFetchServerToolOpenRouterParameters$Outbound | undefined;
  type: "openrouter:web_fetch";
};

/** @internal */
export const WebFetchServerToolOpenRouter$outboundSchema: z.ZodType<
  WebFetchServerToolOpenRouter$Outbound,
  WebFetchServerToolOpenRouter
> = z.object({
  parameters: z.lazy(() =>
    WebFetchServerToolOpenRouterParameters$outboundSchema
  ).optional(),
  type: z.literal("openrouter:web_fetch"),
});

export function webFetchServerToolOpenRouterToJSON(
  webFetchServerToolOpenRouter: WebFetchServerToolOpenRouter,
): string {
  return JSON.stringify(
    WebFetchServerToolOpenRouter$outboundSchema.parse(
      webFetchServerToolOpenRouter,
    ),
  );
}
