/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 99dffefc1c11
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  WebSearchServerToolConfig,
  WebSearchServerToolConfig$inboundSchema,
  WebSearchServerToolConfig$Outbound,
  WebSearchServerToolConfig$outboundSchema,
} from "./websearchservertoolconfig.js";

export const WebSearchServerToolOpenRouterType = {
  OpenrouterWebSearch: "openrouter:web_search",
} as const;
export type WebSearchServerToolOpenRouterType = ClosedEnum<
  typeof WebSearchServerToolOpenRouterType
>;

/**
 * OpenRouter built-in server tool: searches the web for current information
 */
export type WebSearchServerToolOpenRouter = {
  /**
   * Configuration for the openrouter:web_search server tool
   */
  parameters?: WebSearchServerToolConfig | undefined;
  type: WebSearchServerToolOpenRouterType;
};

/** @internal */
export const WebSearchServerToolOpenRouterType$inboundSchema: z.ZodEnum<
  typeof WebSearchServerToolOpenRouterType
> = z.enum(WebSearchServerToolOpenRouterType);
/** @internal */
export const WebSearchServerToolOpenRouterType$outboundSchema: z.ZodEnum<
  typeof WebSearchServerToolOpenRouterType
> = WebSearchServerToolOpenRouterType$inboundSchema;

/** @internal */
export const WebSearchServerToolOpenRouter$inboundSchema: z.ZodType<
  WebSearchServerToolOpenRouter,
  unknown
> = z.object({
  parameters: WebSearchServerToolConfig$inboundSchema.optional(),
  type: WebSearchServerToolOpenRouterType$inboundSchema,
});
/** @internal */
export type WebSearchServerToolOpenRouter$Outbound = {
  parameters?: WebSearchServerToolConfig$Outbound | undefined;
  type: string;
};

/** @internal */
export const WebSearchServerToolOpenRouter$outboundSchema: z.ZodType<
  WebSearchServerToolOpenRouter$Outbound,
  WebSearchServerToolOpenRouter
> = z.object({
  parameters: WebSearchServerToolConfig$outboundSchema.optional(),
  type: WebSearchServerToolOpenRouterType$outboundSchema,
});

export function webSearchServerToolOpenRouterToJSON(
  webSearchServerToolOpenRouter: WebSearchServerToolOpenRouter,
): string {
  return JSON.stringify(
    WebSearchServerToolOpenRouter$outboundSchema.parse(
      webSearchServerToolOpenRouter,
    ),
  );
}
export function webSearchServerToolOpenRouterFromJSON(
  jsonString: string,
): SafeParseResult<WebSearchServerToolOpenRouter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebSearchServerToolOpenRouter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebSearchServerToolOpenRouter' from JSON`,
  );
}
