/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 478da2f8e455
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

export type WebSearchServerToolParameters = {
  /**
   * Maximum number of search results to return. Defaults to 5.
   */
  maxResults?: number | undefined;
};

/**
 * OpenRouter built-in server tool: searches the web for current information
 */
export type WebSearchServerTool = {
  type: "openrouter:web_search";
  parameters?: WebSearchServerToolParameters | undefined;
};

/** @internal */
export type WebSearchServerToolParameters$Outbound = {
  max_results?: number | undefined;
};

/** @internal */
export const WebSearchServerToolParameters$outboundSchema: z.ZodType<
  WebSearchServerToolParameters$Outbound,
  WebSearchServerToolParameters
> = z.object({
  maxResults: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    maxResults: "max_results",
  });
});

export function webSearchServerToolParametersToJSON(
  webSearchServerToolParameters: WebSearchServerToolParameters,
): string {
  return JSON.stringify(
    WebSearchServerToolParameters$outboundSchema.parse(
      webSearchServerToolParameters,
    ),
  );
}

/** @internal */
export type WebSearchServerTool$Outbound = {
  type: "openrouter:web_search";
  parameters?: WebSearchServerToolParameters$Outbound | undefined;
};

/** @internal */
export const WebSearchServerTool$outboundSchema: z.ZodType<
  WebSearchServerTool$Outbound,
  WebSearchServerTool
> = z.object({
  type: z.literal("openrouter:web_search"),
  parameters: z.lazy(() => WebSearchServerToolParameters$outboundSchema)
    .optional(),
});

export function webSearchServerToolToJSON(
  webSearchServerTool: WebSearchServerTool,
): string {
  return JSON.stringify(
    WebSearchServerTool$outboundSchema.parse(webSearchServerTool),
  );
}
